var words = [
    {"name":"Sucinto","descrp":"Que está expresado de manera breve, concisa y precisa.","tags":["sustantivo"]},
    {"name":"Prefacio","descrp":"Cosa que se dice o se escribe como introducción para lo que es el asunto principal de un discurso o tratado.","tags":["sustantivo"]},
    {"name":"Medrar","descrp":"Mejorar [una persona] en posición económica o social.@Crecer o desarrollarse [una planta o un animal].","tags":["verbo"]},
    {"name":"Escrudiñar","descrp":"Examinar, inquirir y averiguar cuidadosamente algo y sus circunstancias.","tags":["verbo"]},
    {"name":"Crinado","descrp":"Que tiene largo el cabello.","tags":["adjetivo"]},
    {"name":"Inope","descrp":"Pobre, indigente.","tags":["adjetivo"]},
    {"name":"Paupérrimo","descrp":"Superlativo de pobre.","tags":["adjetivo"]},
    {"name":"Tuanis","descrp":"Dicho de una cosa de excelente calidad.","tags":["adjetivo"]},
    {"name":"Paquetear","descrp":"Vestir ropa refinada y elegante.","tags":["verbo"]},
    {"name":"Anonadar","descrp":"Abrumar o dejar muy desconcertado a alguien.","tags":["verbo"]},
    {"name":"Letrado","descrp":"Que es instruido y tiene muchos conocimientos culturales.@Persona legalmente autorizada para asesorar y defender los derechos e intereses de otra persona en materia jurídica y representarla en un pleito.","tags":["adjetivo"]},
    {"name":"Rutilar","descrp":"Brillar como oro o resplandecer despidiendo rayos de luz.","tags":["verbo"]},
    {"name":"Bisoño","descrp":"Que es nuevo e inexperto en un trabajo o actividad.","tags":["verbo"]},
    {"name":"Hierático","descrp":"Que es solemne e inexpresivo, se mueve poco y no exterioriza sentimientos.","tags":["adjetivo"]},
    {"name":"Flirtear","descrp":"Conversar o tratarse [dos personas] de manera cariñosa con la intención de iniciar una relación amorosa superficial o duradera.@Intentar agradar o atraer [una persona] a otra u otras con medios estudiados y generalmente por mera vanidad.","tags":["verbo"]},
    {"name":"Coartar","descrp":"Restringir algo no material, especialmente la libertad, la voluntad, etc.","tags":["verbo"]},
    {"name":"Neófito","descrp":"Persona que se ha convertido recientemente a una religión, especialmente la que acaba de ser bautizada.@Persona que se ha adherido recientemente a una causa, una ideología, una colectividad, un partido político, etc.","tags":["sustantivo"]},
    {"name":"Semblante","descrp":"Cara de una persona.@Expresión que tienen las facciones de una persona y que revelan su estado de ánimo.","tags":["sustantivo"]},
    {"name":"Efigie","descrp":"Imagen o representación de una persona, generalmente reproducida en una moneda, una pintura o una escultura.","tags":["sustantivo"]},
    {"name":"Elucubrar","descrp":"Reflexionar acerca de algo con atención y cuidado para estudiarlo o comprenderlo bien o para llegar a alguna conclusión o solución.@Especular o imaginar cosas sin tener mucho fundamento racional.","tags":["verbo"]},
    {"name":"Vergatario","descrp":"Que se destaca o sobresale por alguna cualidad, sobre todo por su valor o su fuerza.","tags":["adjetivo"]},
    {"name":"Abigeo","descrp":"Persona que hurta el ganado.","tags":["sustantivo"]},
    {"name":"Abrupto","descrp":"[lugar, terreno] Que tiene pendientes muy pronunciadas o fuertes desniveles. Que es áspero, rudo o sin educación e inesperado.","tags":["adjetivo"]},
    {"name":"Abstemio","descrp":"Que nunca toma bebidas alcohólicas.","tags":["adjetivo"]},
    {"name":"Abstraído","descrp":"Que dirige toda su atención a una actividad o pensamiento, aislándose de lo que lo rodea. Que acostumbra a abstraerse de lo que lo rodea para sumirse en sus propios pensamientos.","tags":["adjetivo"]},
    {"name":"Acápite","descrp":"Párrafo aparte, especialmente de un texto legal.","tags":["sustantivo"]},
    {"name":"Acervo","descrp":"Conjunto de bienes o valores morales o culturales que pertenecen a un grupo.","tags":["sustantivo"]},
    {"name":"Acotación","descrp":"Delimitación visible de un terreno, especialmente para indicar que está reservado para uso y aprovechamiento particular. Delimitación de algo material o inmaterial, o restricción en el uso de algo.","tags":["sustantivo"]},
    {"name":"Ademán","descrp":"Conjunto de expresiones, gestos, movimientos, actitudes, etc., que una persona utiliza para comportarse en público y con las demás personas, especialmente según ciertas reglas sociales comúnmente admitidas.","tags":["sustantivo"]},
    {"name":"Adular","descrp":"Alabar de forma exagerada y generalmente interesada a una persona para conseguir un favor o ganar su voluntad.","tags":["verbo"]},
    {"name":"Afligir","descrp":"Causar molestia o sufrimiento físico.","tags":["verbo"]},
    {"name":"Agibílibus","descrp":"Persona con habilidad, ingenio, a veces pícaro, para desenvolverse en la vida.","tags":["sustantivo"]},
    {"name":"Agorero","descrp":"Que anuncia o predice males o desgracias.","tags":["adjetivo"]},
    {"name":"Algarada","descrp":"Alboroto o vocerío formado por un grupo de personas que habla, discute o protesta.","tags":["sustantivo"]},
    {"name":"Amainar","descrp":"Perder fuerza o intensidad un fenómeno atmosférico. Perder fuerza o intensidad un deseo, pasión o sentimiento violento o impetuoso.","tags":["verbo"]},
    {"name":"Ambivalente","descrp":"Que puede tener dos valores distintos o que puede entenderse o interpretarse de dos maneras distintas y opuestas.","tags":["adjetivo"]},
    {"name":"Amedrentar","descrp":"Atemorizar, hacer que alguien sienta miedo o temor.","tags":["verbo"]},
    {"name":"Amnistía","descrp":"Perdón de penas decretado por el Estado como medida excepcional para todos los presos condenados por determinados tipos de delitos, generalmente políticos.","tags":["sustantivo"]},
    {"name":"Anacrónico","descrp":"Que adolece de anacronismo.@Que es propio o característico del pasado y sin embargo se da en la actualidad.","tags":["sustantivo"]},
    {"name":"Anagrama","descrp":"Es una palabra o frase que resulta de la transposición de letras de otra palabra o frase.","tags":["sustantivo"]},
    {"name":"Analogía","descrp":"Relación de semejanza entre cosas distintas.@Procedimiento lingüístico mediante el cual se crean palabras o expresiones nuevas, o se transforman otras que ya existen, con el fin de acomodarlas a un determinado modelo, en especial morfológico.","tags":["sustantivo"]},
    {"name":"Apatía","descrp":"Estado de desinterés y falta de motivación o entusiasmo en que se encuentra una persona y que comporta indiferencia ante cualquier estímulo externo.","tags":["sustantivo"]},
    {"name":"Apofenia","descrp":"Fenómeno que consiste en percibir la existencia de patrones o conexiones, allí donde no las hay.","tags":["personalidad"]},
    {"name":"Arduo","descrp":"Que es muy difícil o exige mucho esfuerzo.","tags":["adjetivo"]},
    {"name":"Arquetipo","descrp":"Modelo original que sirve como pauta para imitarlo, reproducirlo o copiarlo, o prototipo ideal que sirve como ejemplo de perfección de algo.","tags":["sustantivo"]},
    {"name":"Arrogancia","descrp":"Que carece de humildad, o que se siente o se cree superior a los demás. Es un adjetivo usado para expresar una característica negativa o un defecto de la personalidad.","tags":["adjetivo"]},
    {"name":"Asiduo","descrp":"[persona] que realiza con constancia y con cierta continuidad o frecuencia alguna cosa.@[actividad] que se hace de forma constante y con cierta continuidad o frecuencia.","tags":["sustantivo"]},
    {"name":"Atosigar","descrp":"Hacer que una persona se agobie pidiéndole muchas cosas a la vez, insistiéndole en algo o metiéndole prisa.","tags":["verbo"]},
    {"name":"Austero","descrp":"[cosa] Que es sencillo y sin alardes ni adornos superfluos.@[persona] Que vive u obra conforme a lo que le es necesario, apartado de lo superfluo o lo placentero.@[persona] Que es estricto en el cumplimiento de las normas morales.","tags":["adjetivo"]},
    {"name":"Avidez / codicia","descrp":"Deseo fuerte e intenso de tener, hacer o conseguir algo.","tags":["adjetivo"]},
    {"name":"Banal / trivial","descrp":"Que no tiene importancia, trascendencia o interés. Que es común y sabido por todos.","tags":["adjetivo"]},
    {"name":"Benévolo","descrp":"Que tiene buena voluntad o afecto hacia alguien sobre el que tiene poder o autoridad; en especial, que se muestra indulgente o tolerante. [benevolencia].","tags":["adjetivo"]},
    {"name":"Bohemio","descrp":"[persona] Que lleva un tipo de vida libre y poco organizada; en especial, el artista de vida poco convencional.","tags":["adjetivo"]},
    {"name":"Boicotear","descrp":"Impedir o interrumpir el desarrollo normal de un proceso o de un acto como medida de protesta o como medio de presión para conseguir algo.","tags":["verbo"]},
    {"name":"Bunning—Kruger [Efecto]","descrp":"Es un sesgo cognitivo por el cual los individuos incompetentes tienden a sobreestimar su habilidad, mientras que los competentes a subestimarla.","tags":["personalidad"]},
    {"name":"Cabalidad [A]","descrp":"[Cumplir] completamente","tags":["sustantivo"]},
    {"name":"Campante","descrp":"Que está tranquilo y despreocupado a pesar de encontrarse en una situación de peligro o riesgo o de tener motivos para estar preocupado y nervioso. Que está orgulloso o satisfecho de sí mismo.","tags":["adjetivo"]},
    {"name":"Candente","descrp":"Que despierta la atención y el interés general, especialmente por ser de actualidad y por considerarse polémico.","tags":["adjetivo"]},
    {"name":"Caótico","descrp":"Que es absolutamente desordenado o confuso. Del caos o relacionado con él.","tags":["adjetivo"]},
    {"name":"Catagelofobia","descrp":"Fobia que consiste en que el sujeto que la padece experimenta un miedo enfermizo o temor a hacer el ridículo.","tags":["personalidad"]},
    {"name":"Catalizar","descrp":"Causar o provocar un proceso o una reacción de cualquier tipo. Atraer, conformar y agrupar fuerzas, opiniones, sentimientos, etc.","tags":["verbo"]},
    {"name":"Causalidad","descrp":"Relación entre causa y efecto. Principio u origen de alguna cosa.","tags":["sustantivo"]},
    {"name":"Cavilación","descrp":"Reflexión profunda y minuciosa.","tags":["verbo"]},
    {"name":"Ceñido","descrp":"Que rodea algo apretándolo o ajustándose mucho a su superficie y sin dejar apenas espacio.","tags":["adjetivo"]},
    {"name":"Cimbrar","descrp":"Hacer vibrar una vara u otro objeto flexible asiéndolo por un extremo.@Mover el cuerpo o una parte del cuerpo con garbo o gracia al caminar.@Golpear a alguien con una vara o un palo, de manera que le haga doblar el cuerpo.","tags":["verbo"]},
    {"name":"Circundar","descrp":"Estar alrededor de algo o alguien.","tags":["adjetivo"]},
    {"name":"Cisma","descrp":"Desacuerdo o discordia en una colectividad a causa de las diferencias de opinión entre sus miembros. Doctrina que profesan o defienden los que abandonan una organización o un movimiento, especialmente una iglesia, porque no están de acuerdo con la ideología o doctrina dominante.","tags":["sustantivo"]},
    {"name":"Cloroformo","descrp":"Líquido incoloro, de olor fuerte y característico, que se usaba antiguamente como anestésico por inhalación.","tags":["sustantivo"]},
    {"name":"Cofradía","descrp":"Asociación de personas con unos mismos intereses, especialmente si estos son profesionales o altruistas.","tags":["sustantivo"]},
    {"name":"Comicios","descrp":"Actos previos a una votación cuya finalidad es informar y convencer a los votantes de las ideas de una candidatura. Mecanismo a través del cual los miembros de una comunidad eligen por votación representantes o cargos políticos, sindicales.","tags":["sustantivo"]},
    {"name":"Compendio","descrp":"Resumen breve, conciso y sustancial de una materia amplia.","tags":["sustantivo"]},
    {"name":"Condescendencia","descrp":"El deseo de complacer, dar gusto y acomodarse a la voluntad del otro. En sentido negativo se refiere a una amabilidad forzada que nace del sentimiento de superioridad hacia otra persona.","tags":["sustantivo"]},
    {"name":"Condiscípulo","descrp":"Persona que estudia o ha estudiado con otra u otras en el mismo centro docente o que recibe o ha recibido las enseñanzas de un mismo maestro.","tags":["sustantivo"]},
    {"name":"Confabular","descrp":"Ponerse de acuerdo para emprender algún plan, generalmente ilícito.","tags":["verbo"]},
    {"name":"Conjetura","descrp":"Juicio u opinión formado a partir de indicios o datos incompletos o supuestos.","tags":["sustantivo"]},
    {"name":"Consigna","descrp":"Orden que se da a los subordinados o que se transmite de unas personas a otras en una misión.","tags":["sustantivo"]},
    {"name":"Contraproducente","descrp":"[acto, dicho] Que produce un efecto contrario al que conviene o se pretende.","tags":["adjetivo"]},
    {"name":"Coprofagia","descrp":"Inclinación morbosa a comer excrementos u otras inmundicias.@Ingestión de excrementos u otras inmundicias.","tags":["sustantivo"]},
    {"name":"Corsé","descrp":"Prenda interior de tejido fuerte, elástico y a menudo con ballenas que comprime y moldea el cuerpo desde el pecho hasta la cadera.@Aquello que constriñe o limita las ideas, el pensamiento, la libertad de acción, etc.","tags":["sustantivo"]},
    {"name":"Covacha","descrp":"Cueva pequeña. Vivienda o habitación pequeña, pobre, oscura y sucia.","tags":["sustantivo"]},
    {"name":"Cribar","descrp":"Seleccionar o elegir entre varias cosas o personas para separar las que se consideran buenas o apropiadas para algo de las que no lo son.","tags":["verbo"]},
    {"name":"Cutre","descrp":"Que es pobre, barato, de mala calidad, de mal gusto, de aspecto descuidado o sucio.","tags":["adjetivo"]},
    {"name":"Decadencia","descrp":"Pérdida progresiva de la fuerza, intensidad, importancia o perfección de una cosa o una persona. Período histórico en el que un movimiento artístico o cultural, un estado, una sociedad, etc., va perdiendo la fuerza o los valores que lo constituyen y se debilita hasta desintegrarse.","tags":["sustantivo"]},
    {"name":"Demagogo","descrp":"Persona que practica la demagogia: [dominación tiránica del pueblo. Empleo de halagos, falsas promesas que son populares pero difíciles de cumplir y otros procedimientos similares para convencer al pueblo y convertirlo en instrumento de la propia ambición política.]","tags":["adjetivo"]},
    {"name":"Denigrante","descrp":"Que ataca, daña o menoscaba el buen nombre, la fama o el honor de una persona.","tags":["adjetivo"]},
    {"name":"Dentífrico","descrp":"Que sirve para limpiar los dientes.","tags":["sustantivo"]},
    {"name":"Deplorable","descrp":"Que es capaz de levantar críticas o quejas.","tags":["adjetivo"]},
    {"name":"Derrocar","descrp":"Hacer caer un gobierno o un régimen político. Desposeer a una persona de su cargo, normalmente por medios violentos. Derribar un edificio u otro tipo de construcción.","tags":["verbo"]},
    {"name":"Digresión","descrp":"Hecho de apartarse en un relato, discurso o exposición del asunto principal para tratar de algo que surge relacionado con él. Parte de un discurso, exposición, etc., que no tiene relación directa con el asunto principal que se está tratando.","tags":["adjetivo"]},
    {"name":"Dilucidar","descrp":"Explicar, aclarar o resolver un asunto o una materia.","tags":["verbo"]},
    {"name":"Dioxina","descrp":"Compuesto químico orgánico muy tóxico. Veneno","tags":["sustantivo"]},
    {"name":"Dirimir","descrp":"Resolver o solucionar un desacuerdo o una discusión. Deshacer la unidad de un grupo, especialmente de aquel en el que sus miembros están unidos por un acuerdo o contrato.","tags":["verbo"]},
    {"name":"Discernir","descrp":"Distinguir por medio del intelecto una cosa de otra o varias cosas entre ellas.@Conceder u otorgar a una persona un honor, un premio, un cargo honorífico, etc.","tags":["verbo"]},
    {"name":"Disidente","descrp":"[persona] que se separa del partido, la religión, el gobierno o el colectivo ideológico al que pertenece, por no estar de acuerdo con su doctrina, creencia, sistema, etc.@Que es propio y característico de estas personas.","tags":["sustantivo"]},
    {"name":"Dislexia","descrp":"Trastorno del aprendizaje caracterizado por la dificultad para leer. Alteración de la capacidad de leer por la que se confunden o se altera el orden de letras, sílabas o palabras.","tags":["personalidad"]},
    {"name":"Divagar","descrp":"Hablar, escribir o pensar desordenadamente, sin ajustarse a un tema determinado y sin tener un objetivo para el discurso. Apartarse del asunto principal sobre el que se habla o se escribe.","tags":["verbo"]},
    {"name":"Dócil","descrp":"[persona, animal] Que acepta con agrado hacer lo que se le manda y que es fácil de educar. Que implica o denota docilidad.","tags":["adjetivo"]},
    {"name":"Dogma","descrp":"Punto esencial de una religión, una doctrina o un sistema de pensamiento que se tiene por cierto y que no puede ponerse en duda dentro de su sistema.","tags":["sustantivo"]},
    {"name":"Dogmático","descrp":"Que afirma o presenta como verdad innegable o como un hecho establecido lo que es discutible.","tags":["sustantivo"]},
    {"name":"Dosificar","descrp":"Establecer la cantidad de un medicamento o de otra sustancia que ha de ingerirse en una toma. Graduar la cantidad o proporción de algo.","tags":["verbo"]},
    {"name":"Dualidad","descrp":"Existencia de dos caracteres o fenómenos distintos en una misma persona o cosa.","tags":["sustantivo"]},
    {"name":"Ecuánime","descrp":"Que obra con rectitud, justicia e imparcialidad o está dotado de ellas.@[persona] Que no suele dejarse llevar por la pasión.@La ecuanimidad es un estado de estabilidad y compostura psicológica que no se ve perturbado por la experiencia o exposición a emociones, dolor u otros fenómenos que pueden causar la pérdida del equilibrio de la mente.","tags":["adjetivo"]},
    {"name":"Efusividad","descrp":"Muestra intensa de sentimientos de alegría o afecto.","tags":["verbo"]},
    {"name":"Elocuencia","descrp":"Facultad de hablar bien con fluidez, propiedad y de manera efectiva para convencer a quien escucha.","tags":["sustantivo"]},
    {"name":"Embaucar","descrp":"Engañar a una persona para algo malo aprovechándose de su falta de experiencia o de su ingenuidad.","tags":["verbo"]},
    {"name":"Embelesar","descrp":"Producir [algo] un sentimiento de placer o admiración tan intenso que enfrasca en su disfrute a la persona que lo contempla, oye, etc., y le hace olvidarse de todo lo demás.","tags":["verbo"]},
    {"name":"Embustero","descrp":"Que dice mentiras, en especial que son muy grandes o evidentes.","tags":["adjetivo"]},
    {"name":"Enajenar","descrp":"Vender, donar o ceder el derecho o el dominio que se tiene sobre un bien o una propiedad. Hacer que una persona pierda la razón o los sentidos, especialmente a causa de un sentimiento intenso de miedo, enfado o dolor.","tags":["verbo"]},
    {"name":"Encomiable / loable","descrp":"[hecho, acto humano] Que merece ser loado o alabado.","tags":["adjetivo"]},
    {"name":"Endeble","descrp":"Que es muy débil y tiene poca solidez, fuerza o resistencia.","tags":["adjetivo"]},
    {"name":"Endogamia","descrp":"Matrimonio entre personas de la misma casta, raza, comunidad o condición social.@Selección de profesionales entre los mismos de la profesión o entre los que les son muy cercanos, de manera que no se permite la entrada de personas ajenas al mismo.","tags":["verbo"]},
    {"name":"Enervar","descrp":"Poner nervioso.@Causar [una cosa] que alguien o algo quede debilitado, sin fuerza o energía.","tags":["verbo"]},
    {"name":"Ensañar","descrp":"Causar un intenso daño, de manera deliberada e innecesaria, a alguien o algo en concreto, especialmente una víctima inocente e indefensa.","tags":["verbo"]},
    {"name":"Entrañable","descrp":"[persona, cosa] Que inspira un gran afecto. Que es profundo y afectuoso.","tags":["adjetivo"]},
    {"name":"Epifanía","descrp":"Manifestación de una cosa.","tags":["sustantivo"]},
    {"name":"Epítome","descrp":"Resumen de una obra extensa en el que se exponen las ideas o las nociones fundamentales del tema que trata esta.@Ejemplo ideal o paradigmático de una cosa.","tags":["verbo"]},
    {"name":"Esbozo","descrp":"Diseño o proyecto provisional de una obra artística, que solamente contiene los elementos esenciales.@Exposición de una idea o plan en sus líneas generales.","tags":["verbo"]},
    {"name":"Escatimar","descrp":"Dar o emplear la menor cantidad posible de cierta cosa.","tags":["verbo"]},
    {"name":"Escrúpulo","descrp":"Duda e inseguridad que una persona sufre acerca de la bondad o licitud de una acción. Aprensión física a tomar un alimento o hacer uso de alguna cosa por temor a la suciedad o al contagio.","tags":["sustantivo"]},
    {"name":"Escrutar","descrp":"Reconocer y computar los votos dados en una elección o los boletos presentados en una apuesta.@Observar o examinar algo o a alguien con mucha atención y minuciosidad.","tags":["verbo"]},
    {"name":"Espabilar","descrp":"Hacer pasar a alguien del estado de modorra o sueño al de vigilia y actividad. Hacer que aumente la inteligencia, la agilidad mental y la capacidad de una persona para relacionarse con el mundo que la rodea.","tags":["verbo"]},
    {"name":"Espasmo","descrp":"Contracción brusca, involuntaria y persistente de las fibras musculares.","tags":["sustantivo"]},
    {"name":"Espigado","descrp":"Persona lata y delgada.","tags":["adjetivo"]},
    {"name":"Estigma","descrp":"En sociología, estigma es una condición, atributo, rasgo o comportamiento que hace que la persona portadora sea incluida en una categoría social hacia cuyos miembros se genera una respuesta negativa y se les ve como culturalmente inaceptables o inferiores.","tags":["sustantivo"]},
    {"name":"Estío","descrp":"Verano","tags":["sustantivo"]},
    {"name":"Estoicismo","descrp":"Escuela filosófica griega y grecorromana fundada por zenón de citio en el siglo IV aC.@Concepción ética de esta escuela según la cual el bien no está en los objetos externos, sino en la sabiduría y dominio del alma, que permite liberarse de las pasiones y deseos que perturban la vida.","tags":["verbo"]},
    {"name":"Estruendoso","descrp":"Que es muy fuerte y ensordecedor.","tags":["adjetivo"]},
    {"name":"Estupefacta","descrp":"[persona] Que está muy sorprendido, asombrado o desconcertado ante algo poco habitual, y no comprende lo que pasa ni sabe cómo reaccionar.","tags":["sustantivo"]},
    {"name":"Exacerbar","descrp":"Provocar gran irritación o enfado. Hacer más fuerte un sentimiento o dolor o agravar una enfermedad.","tags":["verbo"]},
    {"name":"Exento","descrp":"Que está o queda libre o de una carga, obligación, culpa o compromiso.@Que está libre de algo perjudicial o molesto.","tags":["adjetivo"]},
    {"name":"Exhibicionismo","descrp":"Deseo persistente y excesivo de exhibirse. Tendencia patológica a mostrar los propios órganos genitales en público.","tags":["personalidad"]},
    {"name":"Explayar","descrp":"Extender la vista o el pensamiento. Extenderse al hablar de cierta cosa.","tags":["verbo"]},
    {"name":"Fáctico","descrp":"Que está basado en los hechos o limitado a ellos, y no en lo teórico o imaginario.","tags":["adjetivo"]},
    {"name":"Fastuoso","descrp":"Que está hecho con gran fasto o lujo. Que causa admiración por su grandeza, lujo o perfección.","tags":["adjetivo"]},
    {"name":"Fehaciente","descrp":"Que prueba o da fe de algo de forma indudable.","tags":["adjetivo"]},
    {"name":"Filantropía / Altruismo","descrp":"Tendencia a procurar el bien de las personas de manera desinteresada, incluso a costa del interés propio.","tags":["sustantivo"]},
    {"name":"Filología","descrp":"Ciencia que estudia los textos escritos y, en ellos, la estructura y la evolución de una lengua y su desarrollo histórico y literario, así como la literatura y la cultura del pueblo o grupo de pueblos que los han producido.","tags":["sustantivo"]},
    {"name":"Flagrante","descrp":"Que ocurre o se realiza en el momento presente. Que es muy claro y evidente.","tags":["adjetivo"]},
    {"name":"Fogoso","descrp":"Que se muestra entusiasmado o apasionado en lo que hace.","tags":["adjetivo"]},
    {"name":"Fonomímica","descrp":"(sincronización de labios), es el arte que ostenta un individuo de mover la boca fingiendo la reproducción de una voz, propia o ajena, previamente grabada.","tags":["sustantivo"]},
    {"name":"Forúnculo","descrp":"Inflamación localizada en la piel, debida a la infección de un folículo piloso; presenta forma abultada o puntiaguda, color rojo y es doloroso.","tags":["sustantivo"]},
    {"name":"Frenesí","descrp":"Exaltación violenta del ánimo, especialmente de una pasión. Ímpetu o violencia desproporcionados con que alguien o algo se mueve.","tags":["sustantivo"]},
    {"name":"Funesto","descrp":"Que es origen de tristezas o de desgracias.","tags":["adjetivo"]},
    {"name":"Furtivo","descrp":"Que se hace a escondidas o de manera disimulada. [persona] Que caza o pesca sin permiso o cuando está prohibido.","tags":["adjetivo"]},
    {"name":"Fútil","descrp":"Que carece de importancia o interés por su falta de fundamento.","tags":["adjetivo"]},
    {"name":"Gallardía","descrp":"Buen aspecto o presencia y elegancia en el movimiento. Valor y decisión en la forma de actuar o enfrentarse a personas o situaciones.","tags":["adjetivo"]},
    {"name":"Gandalla","descrp":"Que es abusivo y tiene malas intenciones.","tags":["adjetivo"]},
    {"name":"Gremio","descrp":"Asociación profesional formada por personas que tienen el mismo oficio.","tags":["sustantivo"]},
    {"name":"Halotano","descrp":"Es un vapor para inhalación usado en la anestesia general.","tags":["sustantivo"]},
    {"name":"Hediondo","descrp":"Que despide hedor. Molesto, enfadoso e insufrible. Sucio, repugnante y obsceno.","tags":["adjetivo"]},
    {"name":"Hegemonía","descrp":"Supremacía de una organización, una empresa, etc., sobre otras. Supremacía que un estado o un pueblo ejerce sobre otro.","tags":["sustantivo"]},
    {"name":"Hincapié","descrp":"Palabra que se utiliza en la expresión hacer hincapié, que significa ‘dar importancia a una cosa, destacándola o insistiendo en ella’.","tags":["sustantivo"]},
    {"name":"Hipo-poto-monstro-sesqui-padaliofobia","descrp":"Se define como un persistente, anormal e injustificado miedo a las palabras largas.","tags":["sustantivo"]},
    {"name":"Histriónico","descrp":"Patrón general de excesiva e inestable emotividad. Necesidad de ser el centro de la atención.","tags":["personalidad"]},
    {"name":"Hodierno","descrp":"Que pertenece o está relacionado al día de hoy o al tiempo presente.","tags":["adjetivo"]},
    {"name":"Hosco","descrp":"[color] Moreno muy oscuro. Que tiene un carácter cerrado, desagradable y que no gusta de relacionarse con los demás. [tiempo, lugar, ambiente] Que es poco acogedor, que es desagradable, amenazador, etc.","tags":["adjetivo"]},
    {"name":"Idóneo","descrp":"Que reúne las condiciones necesarias u óptimas para una función o fin determinados.","tags":["adjetivo"]},
    {"name":"Impávido","descrp":"[persona] Que hace frente a una situación de peligro o riesgo sin dejarse dominar por el miedo o la angustia.@[persona] Que no se altera, perturba o muestra emoción alguna ante una impresión o estímulo externo que normalmente producen turbación, desencadenan una emoción o inducen a determinada acción.","tags":["adjetivo"]},
    {"name":"Impostura","descrp":"Engaño con apariencia de verdad.","tags":["sustantivo"]},
    {"name":"Inadmisible","descrp":"Que no puede ser admitido.","tags":["adjetivo"]},
    {"name":"Índole","descrp":"Carácter o condición natural propia de cada persona, que la distingue de los demás.@Naturaleza propia de cada cosa, que la distingue de las demás.","tags":["sustantivo"]},
    {"name":"Inefable","descrp":"[cosa] Que no puede ser dicho, explicado o descrito con palabras, generalmente por tener cualidades excelsas o por ser muy sutil o difuso.","tags":["adjetivo"]},
    {"name":"Ineludible","descrp":"Que no puede ser eludido.","tags":["adjetivo"]},
    {"name":"Inescrutable","descrp":"Que no puede ser averiguado o comprendido.","tags":["adjetivo"]},
    {"name":"Inexorable","descrp":"Que no se puede evitar, eludir o detener.@[persona] Que no se deja convencer o ablandar por ruegos o súplicas.","tags":["adjetivo"]},
    {"name":"Inmiscuir","descrp":"Poner una sustancia en otra para que resulte una mezcla.@Entremeterse, tomar parte en un asunto o negocio, especialmente cuando no hay razón o autoridad para ello.","tags":["verbo"]},
    {"name":"Insidia","descrp":"Engaño oculto o disimulado para perjudicar a alguien.","tags":["sustantivo"]},
    {"name":"Intempestivo","descrp":"Que se hace u ocurre fuera del tiempo adecuado o conveniente. Que es inadecuado o inconveniente para hacer determinada cosa, especialmente por ser demasiado temprano o demasiado tarde.","tags":["adjetivo"]},
    {"name":"Inviable","descrp":"Que no puede ocurrir o ser realizado. [lugar] Que está en tan malas condiciones que resulta difícil o imposible recorrerlo o transitar por él.","tags":["sustantivo"]},
    {"name":"Júbilo","descrp":"Gozo o alegría muy intensa que se hace ostensible.","tags":["sustantivo"]},
    {"name":"Labia","descrp":"Habilidad para hablar con gracia y convencer.","tags":["sustantivo"]},
    {"name":"Lacayo","descrp":"Criado uniformado que acompañaba a su señor para prestarle ciertos servicios, como abrirle y cerrarle la puerta del automóvil cuando este viajaba. Soldado de a pie que, junto con otro, acompañaba a un caballero en la guerra e iba armado con una ballesta.","tags":["sustantivo"]},
    {"name":"Longevo","descrp":"Que ha alcanzado o puede alcanzar una edad muy avanzada.","tags":["adjetivo"]},
    {"name":"Magnánima","descrp":"[persona] Que tiene noble temperamento y grandeza de espíritu y se comporta con generosidad.","tags":["adjetivo"]},
    {"name":"Maniqueísmo","descrp":"Actitud o interpretación de la realidad que tiende a valorar las cosas como buenas o como malas, sin términos medios.","tags":["sustantivo"]},
    {"name":"Mártir","descrp":"Persona que sufre o muere por defender su religión o sus ideales. Persona que padece sufrimientos, injusticias o privaciones por alguien o por algo, especialmente si los padece con resignación.","tags":["sustantivo"]},
    {"name":"Megalomanía","descrp":"Trastorno mental que padece la persona que se cree socialmente muy importante, poseedora de enormes riquezas y capaz de hacer grandes cosas.","tags":["personalidad"]},
    {"name":"Melindroso","descrp":"[persona] Que muestra una delicadeza o escrúpulo excesivos en sus palabras, gestos y acciones.","tags":["adjetivo"]},
    {"name":"Minucioso / Meticuloso","descrp":"Que hace las cosas con detenimiento y cuidando los más pequeños detalles.","tags":["adjetivo"]},
    {"name":"Misoginia","descrp":"Aversión a las mujeres o falta de confianza en ellas.","tags":["sustantivo"]},
    {"name":"Mitigar","descrp":"Atenuar o suavizar una cosa negativa, especialmente una enfermedad.","tags":["verbo"]},
    {"name":"Mobbing","descrp":"El acoso laboral o mobbing es un tipo de violencia psicológica que se ejerce en el lugar de trabajo.","tags":["sustantivo"]},
    {"name":"Monólogo","descrp":"Discurso que mantiene una persona consigo misma, como si pensase en voz alta. Escena u obra dramática en que habla un solo personaje.","tags":["sustantivo"]},
    {"name":"Morbosidad","descrp":"Sensación que produce algo que puede resultar desagradable, cruel, prohibido o que va contra la moral establecida.","tags":["sustantivo"]},
    {"name":"Mortificar","descrp":"Lastimar el propio cuerpo o una parte de él como penitencia. Hacer que una persona o una parte de su cuerpo padezca o sufra algún dolor de forma continuada.","tags":["verbo"]},
    {"name":"Muletilla","descrp":"Palabra o expresión que se repite o intercala en el discurso con excesiva frecuencia, como si se tratara de un tic de la persona que habla o escribe.","tags":["sustantivo"]},
    {"name":"Nefario","descrp":"Que es malvado.","tags":["adjetivo"]},
    {"name":"Nefasto","descrp":"Que causa desgracia o va acompañado de ella. Que es extraordinariamente malo.","tags":["adjetivo"]},
    {"name":"Nefelibata","descrp":"Dicho de una persona: Soñadora, que no se apercibe de la realidad.","tags":["adjetivo"]},
    {"name":"Némesis","descrp":"Castigo o venganza.","tags":["adjetivo"]},
    {"name":"Neologismo","descrp":"Un neologismo es una palabra o expresión empleada para nombrar un nuevo concepto. Una palabra nace generalmente cuando surge una nueva realidad que exige ser nombrada: inventos, descubrimientos, situaciones, etc. un término nuevo es un neologismo con respecto a la época en que surge; luego, por supuesto deja de serlo.","tags":["sustantivo"]},
    {"name":"Neotenia","descrp":"Fenómeno que presentan algunos animales, por el cual persisten en ellos caracteres larvarios cuando ya han alcanzado la madurez sexual, como en ciertos anfibios que mantienen las branquias en estado adulto.","tags":["personalidad"]},
    {"name":"Neuroticismo","descrp":"El neuroticismo o inestabilidad emocional es un rasgo psicológico relativamente estable y que define una parte de la personalidad, el cual conlleva, para quien puntúa alto en este rasgo: inestabilidad e inseguridad emocional, tasas elevadas de ansiedad, estado continuo de preocupación y tensión, con tendencia a la ...","tags":["personalidad"]},
    {"name":"Ninfómano","descrp":"Obsesión con pensamientos o comportamientos sexuales, o ganas irresistibles de ejecutar el acto sexual.","tags":["personalidad"]},
    {"name":"Nostalgia","descrp":"Sentimiento de pena por la lejanía, la ausencia, la privación o la pérdida de alguien o algo queridos.","tags":["sustantivo"]},
    {"name":"Odalisca","descrp":"Mujer esclava en el harén de un sultán y que está al servicio de las otras mujeres del harén.@Mujer que se ofrece a los hombres mostrando sensualidad.","tags":["sustantivo"]},
    {"name":"Ofuscar","descrp":"Hacer perder a una persona, de forma pasajera, el entendimiento y la capacidad de razonar o de darse cuenta con claridad de las cosas. Encubrir el significado de una comunicación haciéndola más confusa y complicada de interpretar.","tags":["verbo"]},
    {"name":"Opulencia","descrp":"Gran riqueza. Abundancia o desarrollo extraordinario.","tags":["adjetivo"]},
    {"name":"Orate","descrp":"Persona que ha perdido el juicio. Persona que tiene trastornadas o perturbadas las facultades mentales.","tags":["adjetivo"]},
    {"name":"Oriundo","descrp":"Que es originario del lugar que se especifica.","tags":["adjetivo"]},
    {"name":"Osada","descrp":"[persona] Que se atreve a afrontar situaciones difíciles o peligrosas con valentía y entereza.","tags":["adjetivo"]},
    {"name":"Ostensible","descrp":"Que se ve o percibe con facilidad.","tags":["adjetivo"]},
    {"name":"Ovación","descrp":"Demostración de admiración que un grupo de personas hace en honor de alguien, generalmente mediante aplausos, gritos, etc.","tags":["sustantivo"]},
    {"name":"Paliativo","descrp":"Que sirve para atenuar o suavizar los efectos de una cosa negativa, como un dolor, un sufrimiento o un castigo. Que sirve para disimular o encubrir una cosa.","tags":["adjetivo"]},
    {"name":"Pangrama","descrp":"Un pangrama o frase holoalfabética es un texto que usa todas las letras posibles del alfabeto de un idioma.","tags":["sustantivo"]},
    {"name":"Paradigma","descrp":"Ejemplo o modelo de algo.","tags":["sustantivo"]},
    {"name":"Parafernalia","descrp":"Conjunto de instrumentos o aparatos que se necesitan para un fin determinado.@Exhibición gratuita o alarde de medios que denotan riqueza o importancia, especialmente la que acompaña un acto o una ceremonia.","tags":["sustantivo"]},
    {"name":"Paralogismo","descrp":"Razonamiento falso o incorrecto.","tags":["sustantivo"]},
    {"name":"Paranoia","descrp":"Enfermedad mental que se caracteriza por la aparición de ideas fijas, obsesivas y absurdas, basadas en hechos falsos o infundados, junto a una personalidad bien conservada, sin pérdida de la conciencia ni alucinaciones.","tags":["personalidad"]},
    {"name":"Pareidolia","descrp":"Es un fenómeno psicológico donde un estímulo vago y aleatorio (habitualmente una imagen) es percibido erróneamente como una forma reconocible.","tags":["personalidad"]},
    {"name":"Paripé","descrp":"Engaño o fingimiento para guardar las apariencias o para conseguir lo que se desea.@fingimiento, simulación o acto hipócrita.","tags":["sustantivo"]},
    {"name":"Paulatino","descrp":"Que se produce o se realiza de forma lenta y gradual.","tags":["adjetivo"]},
    {"name":"Pavonearse","descrp":"Mostrar [alguien] con su actitud que está satisfecho de sí mismo.@Presumir de algo que se posee o que se ha hecho.","tags":["verbo"]},
    {"name":"Pendolista","descrp":"Persona que escribe con muy buena letra.@Persona que tiene por oficio escribir cartas, memorias y otros documentos por encargo.","tags":["sustantivo"]},
    {"name":"Penumbroso","descrp":"Que está oscuro o en la penumbra","tags":["adjetivo"]},
    {"name":"Permuta","descrp":"Intercambio de una cosa por otra sin mediación de dinero, salvo excepciones.@Intercambio de empleo entre dos personas que ocupan un puesto público.","tags":["sustantivo"]},
    {"name":"Perogrullesco","descrp":"Que es tan evidente que resulta una tontería decirlo.","tags":["adjetivo"]},
    {"name":"Perorata","descrp":"Discurso largo y poco oportuno que se hace con cierto apasionamiento y vehemencia.","tags":["sustantivo"]},
    {"name":"Pigmalión","descrp":"Efecto que se refiere a la potencial influencia de la creencia que tiene una persona acerca de otra ejerce en el rendimiento de esta última.","tags":["personalidad"]},
    {"name":"Platea","descrp":"Planta baja de un teatro donde se disponen las butacas en filas frente al escenario.","tags":["sustantivo"]},
    {"name":"Pragmático","descrp":"Que se refiere a la práctica, la ejecución o la realización de las acciones y no a la teoría o a la especulación.@[persona] Que piensa o actúa dando prioridad o mucha importancia a las consideraciones prácticas.","tags":["adjetivo"]},
    {"name":"Presagiar","descrp":"Anunciar [alguien] un hecho futuro por simple intuición o por conjeturas a partir de ciertos indicios.@Ser [algo] un indicio que permite conjeturar un hecho futuro.","tags":["verbo"]},
    {"name":"Presuntuoso","descrp":"[persona] Que muestra presunción, vanidad u orgullo.","tags":["adjetivo"]},
    {"name":"Primacía","descrp":"Superioridad o ventaja de una persona o una cosa sobre otras de su misma especie.","tags":["sustantivo"]},
    {"name":"Proeza","descrp":"Acción de gran esfuerzo y valor.","tags":["sustantivo"]},
    {"name":"Promiscua","descrp":"Que está mezclado de forma confusa o indiferente. Que denota promiscuidad: conducta o comportamiento de la persona que cambia con frecuencia de pareja sexual buscando únicamente el placer.","tags":["adjetivo"]},
    {"name":"Prospecto","descrp":"Papel impreso que acompaña a ciertos productos y que contiene información sobre su composición, características y modo de empleo.","tags":["sustantivo"]},
    {"name":"Proxeneta","descrp":"Persona que induce a otra a ejercer la prostitución y se beneficia de las ganancias económicas que se obtienen de esta actividad.","tags":["sustantivo"]},
    {"name":"Pseudopsicólogo","descrp":"Son quienes aplican pseudoterapias que muchas veces son empleadas incluso por psicólogos colegiados, que no han demostrado eficacia ninguna en los estudios.","tags":["personalidad"]},
    {"name":"Pudor","descrp":"Vergüenza de exhibir el propio cuerpo desnudo o de tratar temas relacionados con el sexo. Sentimiento que mueve a ocultar o evitar hablar con otras personas sobre ciertos sentimientos, pensamientos o actos que se consideran íntimos.","tags":["sustantivo"]},
    {"name":"Pulcro","descrp":"Que es o está extremadamente limpio y cuidado.@[persona] Que hace las cosas, especialmente su trabajo, con mucho cuidado, limpieza y delicadeza.@[cosa] Que está hecho con mucho cuidado y delicadeza y no tiene defectos.","tags":["adjetivo"]},
    {"name":"Punzar","descrp":"Clavar algo con punta en algún sitio. Molestar o provocar a una persona hasta conseguir que se enfade. Avivarse [un dolor] intermitentemente, dando pinchazos momentáneos.","tags":["verbo"]},
    {"name":"Quimera","descrp":"Sueño o ilusión que es producto de la imaginación y que se anhela o se persigue pese a ser muy improbable que se realice.@Monstruo fabuloso que se representa con cabeza de león, cuerpo de cabra y cola de dragón.","tags":["sustantivo"]},
    {"name":"Raído","descrp":"[tela, vestido] Que está muy gastado o estropeado por el uso, aunque sin llegar a romperse.","tags":["adjetivo"]},
    {"name":"Reacio","descrp":"Que muestra oposición o resistencia a hacer algo, a recibir una influencia, etc.","tags":["adjetivo"]},
    {"name":"Recabar","descrp":"Conseguir una cosa que se desea con instancias o súplicas.@Solicitar o pedir una cosa por considerar que se tiene derecho a ella.@Recoger información o datos sobre algo.","tags":["verbo"]},
    {"name":"Regodeo","descrp":"Sentimiento de complacencia ante un percance o desgracia sufrido por alguien. Avidez y desmesura en algo.","tags":["sustantivo"]},
    {"name":"Remanso","descrp":"Lugar de una corriente de agua donde esta fluye lentamente o se detiene. Lugar muy tranquilo.","tags":["sustantivo"]},
    {"name":"Remozar","descrp":"Dar un aspecto nuevo o moderno a una cosa haciendo reformas en ella.","tags":["verbo"]},
    {"name":"Rescindir","descrp":"Dejar sin efecto un contrato u otra obligación legal.","tags":["verbo"]},
    {"name":"Resiliencia","descrp":"En psicología, capacidad que tiene una persona para superar circunstancias traumáticas como la muerte de un ser querido, un accidente, etc.","tags":["personalidad"]},
    {"name":"Retórica","descrp":"Conjunto de reglas o principios que se refieren al arte de hablar o escribir de forma elegante y con corrección con el fin de deleitar, conmover o persuadir. Disciplina que estudia la forma y las propiedades de un discurso.","tags":["sustantivo"]},
    {"name":"Revulsivo","descrp":"Que produce un cambio importante, generalmente favorable.@[sustancia, medicamento] Que produce o provoca revulsión (congestión o inflamación).","tags":["adjetivo"]},
    {"name":"Rezongar","descrp":"Emitir [una persona] sonidos no articulados o palabras murmuradas entre dientes en señal de enfado o desagrado.","tags":["verbo"]},
    {"name":"Ruborizar","descrp":"Producir un sentimiento de vergüenza a una persona.","tags":["verbo"]},
    {"name":"Sagaz","descrp":"[persona] Que tiene facilidad para comprender las cosas y de percibir con claridad lo que conllevan.","tags":["adjetivo"]},
    {"name":"Saprofilia / sapiofilia","descrp":"Atracción sexual en base al intelecto.","tags":["personalidad"]},
    {"name":"Sátira","descrp":"Composición poética u otro escrito cuyo objeto es censurar acremente o poner en ridículo a alguien o algo.@Discurso o composición literaria en prosa o verso en que se critican agudamente las costumbres o vicios de alguien con intención moralizadora, lúdica o meramente burlesca.","tags":["sustantivo"]},
    {"name":"Sinergología","descrp":"disciplina del área de la comunicación no verbal. Su objetivo es mejorar la decodificación del funcionamiento de la mente humana a través de su lenguaje corporal","tags":["personalidad"]},
    {"name":"Siniestro","descrp":"Que está hecho con perversidad o mala intención. Que causa cierto temor o angustia por su carácter sombrío o macabro o por su relación con la muerte.","tags":["adjetivo"]},
    {"name":"Sodomizar","descrp":"Practicar la sodomía en una persona.","tags":["verbo"]},
    {"name":"Sofisma","descrp":"Argumento falso o capcioso que se pretende hacer pasar por verdadero.@Razón o argumento aparente con que se quiere defender o persuadir lo que es falso.","tags":["sustantivo"]},
    {"name":"Somatización","descrp":"Acto de [somatizar] convertir los trastornos psíquicos en síntomas orgánicos y funcionales.","tags":["verbo"]},
    {"name":"Sopor","descrp":"Estado intermedio entre el sueño y la vigilia en el que todavía no se ha perdido la conciencia.","tags":["sustantivo"]},
    {"name":"Sórdido","descrp":"Que es miserable o sucio.","tags":["adjetivo"]},
    {"name":"Souvenir","descrp":"Objeto característico de un lugar que sirve como recuerdo del viaje a dicho lugar.","tags":["sustantivo"]},
    {"name":"Súbitamente","descrp":"De forma repentina o inesperada.","tags":["adjetivo"]},
    {"name":"Sucumbir","descrp":"Morir en ciertas circunstancias extraordinarias, como una catástrofe o una guerra. Rendirse o ceder ante una presión, dejando de oponer resistencia.","tags":["verbo"]},
    {"name":"Superfluo","descrp":"Que no cumple ni desempeña una función.","tags":["adjetivo"]},
    {"name":"Supremacía","descrp":"Superioridad absoluta o grado más alto en una jerarquía o clasificación.","tags":["sustantivo"]},
    {"name":"Suspicaz","descrp":"[persona] Que es propenso a sospechar o ver mala intención en lo que dicen o hacen los demás.","tags":["adjetivo"]},
    {"name":"Tajante","descrp":"Que no admite discusión o que corta cualquier posibilidad de réplica.@Que es claro y no admite un término medio.@Que no admite discusión: siempre expone sus ideas de un modo muy tajante.","tags":["adjetivo"]},
    {"name":"Táser","descrp":"Arma de electroshock, diseñada para incapacitar a una persona o animal.","tags":["sustantivo"]},
    {"name":"Transigir","descrp":"Admitir o aceptar una persona la opinión o las ideas de otra en contra de las suyas propias, a fin de llegar a un acuerdo. Soportar, admitir o permitir una cosa que no gusta o que va en contra de los principios de uno mismo.","tags":["verbo"]},
    {"name":"Trillado","descrp":"[camino] Que es muy frecuentado.@[tema, recurso] Que ha sido tratado o utilizado en muchas ocasiones, por lo cual puede resultar vulgar o falto de originalidad.","tags":["adjetivo"]},
    {"name":"Uebo","descrp":"Necesidad, cosa necesaria.","tags":["sustantivo"]},
    {"name":"Ufano","descrp":"[persona] Que presume de sí mismo o se muestra orgulloso de poseer cierta cosa o de ser algo.","tags":["adjetivo"]},
    {"name":"Ultrajar","descrp":"Ofender a alguien con hechos o insultos atentando contra su dignidad, su honor, su credibilidad, etc., especialmente cuando se humilla a alguien en público y con cierta violencia.","tags":["verbo"]},
    {"name":"Vehemente","descrp":"Que obra de forma irreflexiva y apasionada, dejándose llevar por los sentimientos o los impulsos.","tags":["adjetivo"]},
    {"name":"Vejar","descrp":"Maltratar a una persona o hacerla pasar por una situación humillante o vergonzosa.","tags":["verbo"]},
    {"name":"Verdugo","descrp":"Persona que se encarga de ejecutar a los condenados a muerte o, antiguamente, de aplicar los castigos corporales que dictaba la justicia. Persona muy cruel que maltrata o tortura a los demás.","tags":["sustantivo"]},
    {"name":"Verosímil","descrp":"Que parece verdadero o que es creíble.","tags":["adjetivo"]},
    {"name":"Versátil","descrp":"Que se vuelve o se puede volver fácilmente. Capaz de adaptarse con facilidad y rapidez a diversas funciones","tags":["adjetivo"]},
    {"name":"Vilipendiar","descrp":"Despreciar con las palabras, los actos o los gestos a otra persona.","tags":["verbo"]},
    {"name":"Vituperio","descrp":"Censura o desaprobación que una persona hace con mucha dureza contra algo o alguien.","tags":["sustantivo"]},
    {"name":"Vociferar","descrp":"Hablar con un tono de voz más alto de lo que se considera normal.","tags":["verbo"]},
    {"name":"Zangolotear","descrp":"Estar constantemente moviéndose de un lugar a otro sin ningún propósito o fin","tags":["verbo"]},
    {"name":"Eufemismo","descrp":"Palabra o expresión más suave o decorosa con que se sustituye otra considerada tabú, de mal gusto, grosera o demasiado franca.","tags":["sustantivo"]},
    {"name":"Flemático","descrp":"De la flema o que participa de su naturaleza.@[persona] que tiene un temperamento apático y se comporta o actúa con tranquilidad excesiva.","tags":["adjetivo"]},
    {"name":"Gerontología","descrp":"Disciplina científica que estudia el envejecimiento, la vejez y al adulto mayor bajo la perspectiva biológica, psicológica y social.","tags":["sustantivo"]},
    {"name":"Léxico","descrp":"Del léxico o vocabulario, o que tiene relación con él.@Conjunto de las palabras de una lengua.","tags":["sustantivo"]},
    {"name":"Meollo","descrp":"Aspecto o parte central y más sustanciosa de algo.@Masa de tejido nervioso que se encuentra en el interior del cráneo.","tags":["sustantivo"]},
    {"name":"Mesura","descrp":"Contención o freno en la conducta.@Actitud de la persona que actúa con mesura o contención.","tags":["sustantivo"]},
    {"name":"Modismo","descrp":"Expresión característica de una lengua, formada por un conjunto de palabras con una estructura fija y con un significado que no se puede deducir del significado de las palabras que lo forman.","tags":["sustantivo"]},
    {"name":"Monograma","descrp":"Dibujo o figura hechos con las iniciales u otras letras del nombre de una persona o una institución, que se emplea como abreviatura, símbolo o emblema.","tags":["sustantivo"]},
    {"name":"Pirómano","descrp":"[persona] que tiene una tendencia patológica o enfermiza a provocar incendios.","tags":["adjetivo"]},
    {"name":"Pleonasmo","descrp":"Figura retórica de construcción que consiste en añadir enfáticamente a una frase más palabras de las necesarias para su comprensión con el fin de embellecer o añadir expresividad a lo que se dice.","tags":["sustantivo"]},
    {"name":"Poligamia","descrp":"Régimen familiar que permite tener más de una esposa al mismo tiempo.","tags":["sustantivo"]},
    {"name":"Polímata","descrp":"Individuo que estudia o sabe muchas ciencias; polígrafo, erudito.","tags":["sustantivo"]},
    {"name":"Polimórfico","descrp":"Que tiene o puede tener varias formas.","tags":["adjetivo"]},
    {"name":"Procacidad","descrp":"Desvergüenza o atrevimiento, en especial en el aspecto sexual.@Acción o dicho desvergonzado, insolente o atrevido.","tags":["sustantivo"]},
    {"name":"Quimera","descrp":"Sueño o ilusión que es producto de la imaginación y que se anhela o se persigue pese a ser muy improbable que se realice.@Monstruo fabuloso que se representa con cabeza de león, cuerpo de cabra y cola de dragón.","tags":["sustantivo"]},
    {"name":"Reticentes","descrp":"[persona] que actúa con reticencia, desconfianza o cautela.@Que denota o implica reticencia.","tags":["adjetivo"]},
    {"name":"Retrograda","descrp":"Que retrocede.@[persona] que es partidario de ideas o instituciones políticas o sociales propias de tiempos pasados.","tags":["adjetivo"]},
    {"name":"Rimbombante","descrp":"De aspecto llamativo","tags":["adjetivo"]},
    {"name":"Socavar","descrp":"Excavar alguna cosa por debajo, dejándola sin apoyo y expuesta a hundirse.@Debilitar la fuerza moral de una ideología o un valor espiritual, o de la persona que la defiende o representa.","tags":["verbo"]},    
]