var json_data_serie = {
    data_serie: {
        serie: 'Daria',
        tipo: "Temporada",
        favic: 'https://pbs.twimg.com/profile_images/3079459724/e4cf9bf671fc8868eea33cc9f9523dc9.png',
        logot: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/DariaLogo.png/1024px-DariaLogo.png',
        exter: 'https://www.d-animados.com/serie/daria/',
        prima: 'rgb(20, 123, 189)',
        secun: 'rgb(178, 116, 50)',
        porta: 'https://m.media-amazon.com/images/M/MV5BYmI3NzlkYzItMWI0OC00NjM2LWI4ZTUtMDhkYmNmYjkxYzIxXkEyXkFqcGdeQXVyMTA3MzQ4MTc0._V1_QL75_UX190_CR0,28,190,281_.jpg',
        ath: 'skt'
    },
    caps: [
        {url: "https://uqload.com/embed-11u4emwdq26o.html",tem: 1,epi: 1,tit: "Cuidado con la autoestima"},
        {url: "https://uqload.com/embed-3hly6rp6nv8m.html",tem: 1,epi: 2,tit: "La invitación"},
        {url: "https://uqload.com/embed-gq7te1pj7wp0.html",tem: 1,epi: 3,tit: "La universidad"},
        {url: "https://uqload.com/embed-vy9cow9dwwlw.html",tem: 1,epi: 4,tit: "El café del desplante"},
        {url: "https://uqload.com/embed-n16qrcr1ltk8.html",tem: 1,epi: 5,tit: "La macroplaza"},
        {url: "https://uqload.com/embed-4gpxbe70e2rw.html",tem: 1,epi: 6,tit: "La modelo del año"},
        {url: "https://uqload.com/embed-uw1by06rfi0c.html",tem: 1,epi: 7,tit: "Ratones de laboratorio"},
        {url: "https://uqload.com/embed-kv1miujofrhg.html",tem: 1,epi: 8,tit: "Cuidado con la niñera"},
        {url: "https://uqload.com/embed-y1kljwz3ns57.html",tem: 1,epi: 9,tit: "Demasiado linda"},
        {url: "https://uqload.com/embed-0pboc6pzl8cm.html",tem: 1,epi: 10,tit: "La justicia es ciega"},
        {url: "https://uqload.com/embed-ptyzlili1ip1.html",tem: 1,epi: 11,tit: "Peripecias del camino"},
        {url: "https://uqload.com/embed-n9lhkl2skf5v.html",tem: 1,epi: 12,tit: "Las enseñanzas de Don Jake"},
        {url: "https://uqload.com/embed-h3e0w55imy7i.html",tem: 1,epi: 13,tit: "La chica miseria"},
        {url: "https://uqload.com/embed-cm9ls8f7pf83.html",tem: 2,epi: 1,tit: "Arte y descarte"},
        {url: "https://uqload.com/embed-a486quuyg0c1.html",tem: 2,epi: 2,tit: "El cazador de Daria"},
        {url: "https://uqload.com/embed-w1q89quflkjj.html",tem: 2,epi: 3,tit: "Quinn, la cerebrito"},
        {url: "https://uqload.com/embed-ib8vc4itn1sk.html",tem: 2,epi: 4,tit: "Una boda ejemplar"},
        {url: "https://uqload.com/embed-jyxtf0jz0wks.html",tem: 2,epi: 5,tit: "Eso fue entonces, ahora es peor"},
        {url: "https://uqload.com/embed-uzq0syfclxl5.html",tem: 2,epi: 6,tit: "He creado un monstruo"},
        {url: "https://uqload.com/embed-bd4bqakc4t21.html",tem: 2,epi: 7,tit: "El nuevo chico"},
        {url: "https://uqload.com/embed-hvogsjl19kxu.html",tem: 2,epi: 8,tit: "Los superdotados"},
        {url: "https://uqload.com/embed-71jwtoh48utv.html",tem: 2,epi: 9,tit: "La peste"},
        {url: "https://uqload.com/embed-ylv6pksbk39m.html",tem: 2,epi: 10,tit: "La feria y el fastidio"},
        {url: "https://uqload.com/embed-f6ot5y6jt6br.html",tem: 2,epi: 11,tit: "Corre, Jane, corre"},
        {url: "https://uqload.com/embed-we0dqr5t4owj.html",tem: 2,epi: 12,tit: "La piel perforada"},
        {url: "https://uqload.com/embed-8zt87gnhctmy.html",tem: 2,epi: 13,tit: "La letra con sangre entra"},
        {url: "https://uqload.com/embed-32bkq3sysh2u.html",tem: 3,epi: 1,tit: "Todo depende del cristal con que se mira"},
        {url: "https://uqload.com/embed-6vy8b9xyoto0.html",tem: 3,epi: 2,tit: "La bella y los viejos"},
        {url: "https://uqload.com/embed-r18dcpit1jyw.html",tem: 3,epi: 3,tit: "Los prófugos días de fiesta"},
        {url: "https://uqload.com/embed-mxj1xfte1ls7.html",tem: 3,epi: 4,tit: "Daria de rumba"},
        {url: "https://uqload.com/embed-kmrq23d9jefg.html",tem: 3,epi: 5,tit: "Las chicas perdidas"},
        {url: "https://uqload.com/embed-25kc9el5qjig.html",tem: 3,epi: 6,tit: "Mucho ruido y pocas nueces"},
        {url: "https://uqload.com/embed-avaym9a7ipmx.html",tem: 3,epi: 7,tit: "La zarzuela del ciclón"},
        {url: "https://uqload.com/embed-xely9r59zf3r.html",tem: 3,epi: 8,tit: "Las desdichas de los Lane"},
        {url: "https://uqload.com/embed-rumoopnegvd1.html",tem: 3,epi: 9,tit: "Corazón de padre"},
        {url: "https://uqload.com/embed-bgi5pbpt7a5q.html",tem: 3,epi: 10,tit: "La ley es la ley"},
        {url: "https://uqload.com/embed-86nt1pcg0mr5.html",tem: 3,epi: 11,tit: "Los expedientes Lawndale"},
        {url: "https://uqload.com/embed-xk4impy6vpo9.html",tem: 3,epi: 12,tit: "Sólo añádale agua (Inglés)"},
        {url: "https://uqload.com/embed-b62n34cwsgm8.html",tem: 3,epi: 13,tit: "Jane y su adición"},
        {url: "https://uqload.com/embed-16zqmpjq9w69.html",tem: 4,epi: 1,tit: "Agravios de parejas"},
        {url: "https://uqload.com/embed-9p7yq4ghuqyo.html",tem: 4,epi: 2,tit: "Abajo los arribistas"},
        {url: "https://uqload.com/embed-tez43o6no0t5.html",tem: 4,epi: 3,tit: "Crece un árbol en Lawndale"},
        {url: "https://uqload.com/embed-f4rzxdntfy19.html",tem: 4,epi: 4,tit: "Entre ronquidos, un crimen"},
        {url: "https://uqload.com/embed-t16dxdtedkyh.html",tem: 4,epi: 5,tit: "La celebración del fracaso"},
        {url: "https://uqload.com/embed-8zfeyuloj3h5.html",tem: 4,epi: 6,tit: "Un desfile desfigurado"},
        {url: "https://uqload.com/embed-ht3wftwvkbec.html",tem: 4,epi: 7,tit: "Las cadenas de la intimidad"},
        {url: "https://uqload.com/embed-g18mkqb5sjnh.html",tem: 4,epi: 8,tit: "Mi familia es todo un caso"},
        {url: "https://uqload.com/embed-wi8euyb7ofy2.html",tem: 4,epi: 9,tit: "El consumo en las tinieblas"},
        {url: "https://uqload.com/embed-yc1aai0dvhmo.html",tem: 4,epi: 10,tit: "Espectros suburbanos"},
        {url: "https://uqload.com/embed-82v9ct2zh7ug.html",tem: 4,epi: 11,tit: "El ángel desengañador"},
        {url: "https://uqload.com/embed-k9ecxfoxv578.html",tem: 4,epi: 12,tit: "¡Fuego!"},
        {url: "https://uqload.com/embed-hhd1mwfe2jy1.html",tem: 4,epi: 13,tit: "Amores tigres"},
        {url: "https://uqload.com/embed-xk54u9mrahln.html",tem: 5,epi: 1,tit: "Gasificados"},
        {url: "https://uqload.com/embed-phn8n627qo7u.html",tem: 5,epi: 2,tit: "Un aniversario ordinario"},
        {url: "https://uqload.com/embed-rv1q5x2et2z1.html",tem: 5,epi: 3,tit: "Gorda como yo"},
        {url: "https://uqload.com/embed-1lnwwflfe8yb.html",tem: 5,epi: 4,tit: "Me dan miedo los campamentos"},
        {url: "https://uqload.com/embed-ajikb1zcyag1.html",tem: 5,epi: 5,tit: "El cuento de D"},
        {url: "https://uqload.com/embed-n09agzb6in90.html",tem: 5,epi: 6,tit: "Un golpe de suerte"},
        {url: "https://uqload.com/embed-5088ku1dctx9.html",tem: 5,epi: 7,tit: "La llamada del arte"},
        {url: "https://uqload.com/embed-9cczc3bu15q4.html",tem: 5,epi: 8,tit: "Sólo un novio a la vez"},
        {url: "https://uqload.com/embed-7kj5vfqr9e6y.html",tem: 5,epi: 9,tit: "El viaje que Jane hizo al pasado"},
        {url: "https://uqload.com/embed-mxt5pxwqgks6.html",tem: 5,epi: 10,tit: "Hasta hartarse"},
        {url: "https://uqload.com/embed-or3iqcsjx58q.html",tem: 5,epi: 11,tit: "Rivales por una beca"},
        {url: "https://uqload.com/embed-gy6lyp4sgyv3.html",tem: 5,epi: 12,tit: "Mi noche con Daria"},
        {url: "https://uqload.com/embed-0mx5uu9y1adq.html",tem: 5,epi: 13,tit: "Daria encerrada en su caja"},
    ]
}
//http://latinoseriestv.blogspot.com/2014/09/daria-4-x-09-el-consumo-en-la-tinieblas.html