var json_data_serie = {
    data_serie: {
        serie: 'Mentes Criminales',
        tipo: "Temporada",
        favic: 'https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/f9/f2/f6/f9f2f6af-4eba-57b5-7e51-ee849c488a82/universal-0-1x_U007emarketing-0-85-220-0-9.png/246x0w.jpg',
        logot: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Criminal-Minds.svg',
        exter: 'https://pelisplus.me/serie/mentes-criminales',
        prima: 'rgb(174, 91, 76)',
        secun: 'rgb(189, 41, 27)',
        porta: 'https://m.media-amazon.com/images/M/MV5BNGE2ZmFkZTYtNjRiOS00ZjE3LThjOWMtZTViZjRmNDFjNTQwXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg',
        ath: 'skt'
    },
    caps: [/*
        {url: "https://feurl.com/v/mzoklxd519q", tem: 1, epi: 1,tit: "Agresor Cruel"},
        {url: "https://feurl.com/v/05oll805no6", tem: 1, epi: 2,tit: "Obligación"},
        {url: "https://uqload.com/embed-x9exig63zbs4.html", tem: 1, epi: 3,tit: "No me Engañarás Otra Vez"},
        {url: "https://feurl.com/v/pm957k8j8ol", tem: 1, epi: 4,tit: "A Simple Vista"},
        {url: "https://feurl.com/v/4lo0kd8jxvq", tem: 1, epi: 5,tit: "Espejo Roto"},
        {url: "https://feurl.com/v/05oll80xno6", tem: 1, epi: 6,tit: "Asesinos a Larga Distancia"},
        {url: "https://feurl.com/v/8xopewkxq97", tem: 1, epi: 7,tit: "El Zorro"},
        {url: "https://feurl.com/v/2w9mlke4lo6", tem: 1, epi: 8,tit: "Asesino Nato"},
        {url: "https://feurl.com/v/1x9ql7p-xv4", tem: 1, epi: 9,tit: "Descarrilado"},
        {url: "https://uqload.com/embed-kaddo5me8w9r.html", tem: 1, epi: 10,tit: "Los Niños Buenos"},
        {url: "https://feurl.com/v/mzoklxd-19q", tem: 1, epi: 11,tit: "Hambriento de Sangre"},
        {url: "https://feurl.com/v/zyvnlnpp8o1", tem: 1, epi: 12,tit: "Lo Que Faltaba"},
        {url: "https://feurl.com/v/5j946287xo0", tem: 1, epi: 13,tit: "Veneno"},
        {url: "https://uqload.com/embed-838blh5pzktw.html", tem: 1, epi: 14,tit: "Alcanzar el Relámpago"},
        {url: "https://feurl.com/v/40oxq2z7yv8", tem: 1, epi: 15,tit: "Asuntos Pendientes"},
        {url: "https://uqload.com/embed-vj8qqwkz62xi.html", tem: 1, epi: 16,tit:" La Tribu"},
        {url: "https://feurl.com/v/zyonl3mk891", tem: 1, epi: 17,tit: "Lluvia de Verdad"},
        {url: "https://feurl.com/v/yxv34myxqol", tem: 1, epi: 18,tit: "Alguien te Vigila"},
        {url: "https://feurl.com/v/8g9drdxgpoy", tem: 1, epi: 19,tit: "Machismo"},
        {url: "https://uqload.com/embed-18cvbmdfphye.html", tem: 1, epi: 20,tit: "Daño y encanto"},
        {url: "https://feurl.com/v/8g9zq3ery9d", tem: 1, epi: 21, tit: "Secretos y Mentiras"},
        {url: "https://feurl.com/v/2wvmlke1l96", tem: 1, epi: 22, tit: "El Rey Pescador (parte 1)"},
        {url: "https://feurl.com/v/7qv70qz2w9g", tem: 2, epi: 1, tit: "El Rey Pescador: Parte 2"},
        {url: "https://feurl.com/v/2w9mlkenlo6", tem: 2, epi: 2, tit: "P911"},
        {url: "https://feurl.com/v/7zo-r0xp2ox", tem: 2, epi: 3, tit: "La tormenta perfecta"},
        {url: "https://feurl.com/v/eno8rjz3091", tem: 2, epi: 4, tit: "Psicodrama"},
        {url: "https://feurl.com/v/80oepgyn7vj", tem: 2, epi: 5, tit: "Secuelas"},
        {url: "https://feurl.com/v/5jo46kz8xv0", tem: 2, epi: 6, tit: "The Boogeyman"},
        {url: "https://feurl.com/v/7y9wqmk5x9j", tem: 2, epi: 7, tit: "Norte de Mammon"},
        {url: "https://feurl.com/v/2w9mlgrrlo6", tem: 2, epi: 8, tit: "Planeta vacío"},
        {url: "https://feurl.com/v/mzokl2md19q", tem: 2, epi: 9, tit: "La última palabra"},
        {url: "https://feurl.com/v/5jv46-j0x90", tem: 2, epi: 10, tit: "Lecciones Aprendidas"},
        {url: "https://feurl.com/v/eno8rjz8091", tem: 2, epi: 11, tit: "Sexo, Nacimiento, Muerte"},
        {url: "https://feurl.com/v/7z9-r0xe29x", tem: 2, epi: 12, tit: "Profiler, perfilado"},
        {url: "https://feurl.com/v/7y9wqmk7x9j", tem: 2, epi: 13, tit: "No hay salida"},
        {url: "https://feurl.com/v/zyvnl3mp8o1", tem: 2, epi: 14, tit: "El gran juego"},
        {url: "https://feurl.com/v/yxv34my6qol", tem: 2, epi: 15, tit: "Revelaciones"},
        {url: "https://uqload.com/embed-fasi7k8x3u5o.html", tem: 2, epi: 16, tit: "Miedo y odio"},
        {url: "https://uqload.com/embed-ipp14suztsm4.html", tem: 2, epi: 17, tit: "Angustia"},
        {url: "https://feurl.com/v/1lo6dl24l95", tem: 2, epi: 18, tit: "Jones"},
        {url: "https://feurl.com/v/2wvm1-pmlv6", tem: 2, epi: 19, tit: "Cenizas y Polvo"},
        {url: "https://feurl.com/v/059llkmnn96", tem: 2, epi: 20, tit: "Honor entre Ladrones"},
        {url: "https://feurl.com/v/1x9ql7pyxv4", tem: 2, epi: 21, tit: "Temporada Abierta"},
        {url: "https://feurl.com/v/4dvj2em-yo1", tem: 2, epi: 22, tit: "Legado"},
        {url: "https://feurl.com/v/549yq4ngxvl", tem: 3, epi: 1, tit: "Duda"},
        {url: "https://feurl.com/v/2womlkqklv6", tem: 3, epi: 2, tit: "En Nombre y Sangre"},
        {url: "https://feurl.com/v/pmo57mgm8vl", tem: 3, epi: 3, tit: "Muerto de Miedo"},
        {url: "https://feurl.com/v/54oyq47mx9l", tem: 3, epi: 4, tit: "Niños de la Oscuridad"},
        {url: "https://feurl.com/v/40oxq8w6yv8", tem: 3, epi: 5, tit: "Siete segundos"},
        {url: "https://feurl.com/v/4d9j2eqwyv1", tem: 3, epi: 6, tit: "Acerca de Face"},
        {url: "https://feurl.com/v/7yowqmkrxoj", tem: 3, epi: 7, tit: "Identidad"},
        {url: "https://uqload.com/embed-ty92mxmp3upb.html", tem: 3, epi: 8, tit: "Suerte"},
        {url: "https://feurl.com/v/4doj2emyy91", tem: 3, epi: 9, tit: "Penélope"},
        {url: "https://feurl.com/v/8xvpe5mwqo7", tem: 3, epi: 10, tit: "True Night"},
        {url: "https://feurl.com/v/dworl0p4pog", tem: 3, epi: 11, tit: "Patrimonio"},
        {url: "https://feurl.com/v/7qv70q1ew9g", tem: 3, epi: 12, tit: "Tercera Vida"},
        {url: "https://feurl.com/v/3qv1zpgl2oy", tem: 3, epi: 13, tit: "Luz de calcio"},
        {url: "https://feurl.com/v/5j946kgexo0", tem: 3, epi: 14, tit: "Dañado"},
        {url: "https://feurl.com/v/05ollkqwno6", tem: 3, epi: 15, tit: "Un Poder Superior"},
        {url: "https://feurl.com/v/6m923mgpdvr", tem: 3, epi: 16, tit: "La Memoria del Elefante"},
        {url: "https://uqload.com/embed-q8ik1rnjlbif.html", tem: 3, epi: 17, tit: "En calor"},
        {url: "https://feurl.com/v/8godrd7rpvy", tem: 3, epi: 18, tit: "El cruce"},
        {url: "https://feurl.com/v/1lo6dlgdl95", tem: 3, epi: 19, tit: "Tabula Rasa"},
        {url: "https://feurl.com/v/40oxq26qyv8", tem: 3, epi: 20, tit: "Lo-Fi"},
        {url: "https://feurl.com/v/7z9-r0lj29x", tem: 4, epi: 1, tit: "Violencia "},
        {url: "https://feurl.com/v/3q91zpgj2vy", tem: 4, epi: 2, tit: "El Angel Maker"},
        {url: "https://feurl.com/v/dworl01gpog", tem: 4, epi: 3, tit: "Pérdida Mínima"},
        {url: "https://feurl.com/v/7yvwqm47xvj", tem: 4, epi: 4, tit: "Paraíso"},
        {url: "https://feurl.com/v/pmo57mgd8vl", tem: 4, epi: 5, tit: "Catching Out"},
        {url: "https://feurl.com/v/p6ogkwrmx9j", tem: 4, epi: 6, tit: "Los Instintos"},
        {url: "https://feurl.com/v/mzvkl2qg1oq", tem: 4, epi: 7, tit: "Memoriam"},
        {url: "https://feurl.com/v/pm957mgw8ol", tem: 4, epi: 8, tit: "Obra Maestra"},
        {url: "https://feurl.com/v/mzvkl2531oq", tem: 4, epi: 9, tit: "52 Recogida"},
        {url: "https://feurl.com/v/80oepgry7vj", tem: 4, epi: 10, tit: "Compañeros de Armas"},
        {url: "https://feurl.com/v/zyvnl3538o1", tem: 4, epi: 11, tit: "Normal"},
        {url: "https://feurl.com/v/7yvwqmy2xvj", tem: 4, epi: 12, tit: "Almas Gemelas"},
        {url: "https://feurl.com/v/mzokl25219q", tem: 4, epi: 13, tit: "Bloodline"},
        {url: "https://feurl.com/v/2w9mlk5klo6", tem: 4, epi: 14, tit: "Confort Frío"},
        {url: "https://feurl.com/v/80oepgrg7vj", tem: 4, epi: 15, tit: "Reprise de Zoe"},
        {url: "https://feurl.com/v/05ollk56no6", tem: 4, epi: 16, tit: "El Placer es Mi Negocio"},
        {url: "https://feurl.com/v/6mo23m7md9r", tem: 4, epi: 17, tit: "Demonología"},
        {url: "https://feurl.com/v/1lo6dlpnl95", tem: 4, epi: 18, tit: "Omnívoro"},
        {url: "https://feurl.com/v/1xoql75nx94", tem: 4, epi: 19, tit: "Casa en Llamas"},
        {url: "https://feurl.com/v/4d9j2e53yv1", tem: 4, epi: 20, tit: "Conflicto"},
        {url: "https://feurl.com/v/mzokl25419q", tem: 4, epi: 21, tit: "Una Sombra de Gris"},
        {url: "https://feurl.com/v/4dvj2d8lyo1", tem: 4, epi: 22, tit: "La Gran Rueda"},
        {url: "https://feurl.com/v/80oepgrd7vj", tem: 4, epi: 23, tit: "Roadkill"},
        {url: "https://feurl.com/v/eno8rj4l091", tem: 4, epi: 24, tit: "Amplificación"},
        {url: "https://feurl.com/v/7y9wqmynx9j", tem: 4, epi: 25, tit: "Al Infierno y de Regreso"},
        {url: "https://feurl.com/v/7qv70q45w9g", tem: 5, epi: 1, tit: "Sin Rostro, Sin Nombre "},
        {url: "https://feurl.com/v/mzokl21119q", tem: 5, epi: 2, tit: "Obsesionado"},
        {url: "https://feurl.com/v/54oyq4ddx9l", tem: 5, epi: 3, tit: "Calculadora"},
        {url: "https://feurl.com/v/pm957m158ol", tem: 5, epi: 4, tit: "Sin Esperanza"},
        {url: "https://feurl.com/v/5jo46kp5xv0", tem: 5, epi: 5, tit: "Cuna a la Tumba"},
        {url: "https://feurl.com/v/8xope5d-q97", tem: 5, epi: 6, tit: "Los Ojos lo Tienen"},
        {url: "https://feurl.com/v/8g9zq300y9d", tem: 5, epi: 7, tit: "El Artista"},
        {url: "https://feurl.com/v/2w9mlk44lo6", tem: 5, epi: 8, tit: "Outfoxed"},
        {url: "https://feurl.com/v/8g9zq30yy9d", tem: 5, epi: 9, tit: "100 (Parte 2)"},
        {url: "https://feurl.com/v/pm957m118ol", tem: 5, epi: 10, tit: "El Esclavo del Deber"},
        {url: "https://feurl.com/v/1x9ql70lxv4", tem: 5, epi: 11, tit: "Represalias"},
        {url: "https://feurl.com/v/05ollk2pno6", tem: 5, epi: 12, tit: "El Valle de Uncanny"},
        {url: "https://uqload.com/embed-1cdm84z8p5l9.html", tem: 5, epi: 13, tit: "Negocio Arriesgado"},
        {url: "https://feurl.com/v/80oepg667vj", tem: 5, epi: 14, tit: "Parásito"},
        {url: "https://feurl.com/v/40oxq277yv8", tem: 5, epi: 15, tit: "Enemigo Público"},
        {url: "https://feurl.com/v/zyvnl3668o1", tem: 5, epi: 16, tit: "Mosley Lane"},
        {url: "https://uqload.com/embed-848v0u5jkers.html", tem: 5, epi: 17, tit: "Hombre Solitario"},
        {url: "https://uqload.com/embed-b0y3830oxse3.html", tem: 5, epi: 18, tit: "La pelea"},
        {url: "https://uqload.com/embed-b93vx2ecs8ig.html", tem: 5, epi: 19, tit: "Un rito de pasaje"},
        {url: "https://feurl.com/v/p6ogkwddx9j", tem: 5, epi: 20, tit: "Más que Mil Palabras"},
        {url: "https://feurl.com/v/en98rj6r0v1", tem: 5, epi: 21, tit: "Herida Abierta"},
        {url: "https://feurl.com/v/zyvnl36k8o1", tem: 5, epi: 22, tit: "Internet es para Siempre"},
        {url: "https://feurl.com/v/1xoql70-x94", tem: 5, epi: 23, tit: "Nuestra hora más Oscura"},
        {url: "https://feurl.com/v/4dvj2emdyo1", tem: 6, epi: 1, tit: "La noche mas larga"},
        {url: "https://uqload.com/embed-dvvhvhm2jkrh.html", tem: 6, epi: 2, tit: "JJ"},
        {url: "https://feurl.com/v/mzvkl2mx1oq", tem: 6, epi: 3, tit: "El recuerdo de las cosas pasadas"},
        {url: "https://feurl.com/v/1lo6dl2ql95", tem: 6, epi: 4, tit: "Situaciones comprometidas"},
        {url: "https://feurl.com/v/8godrdx1pvy", tem: 6, epi: 5, tit: "Beneficencia"},
        {url: "https://feurl.com/v/5jo46kgrxv0", tem: 6, epi: 6, tit: "Cerca del diablo"},
        {url: "https://feurl.com/v/5j946kgxxo0", tem: 6, epi: 7, tit: "Intermediario"},
        {url: "https://uqload.com/embed-19r81wf7shrv.html", tem: 6, epi: 8, tit: "Reflexión de deseo"},
        {url: "https://feurl.com/v/40oxq260yv8", tem: 6, epi: 9, tit: "En el bosque"},
        {url: "https://feurl.com/v/80oepkz87vj", tem: 6, epi: 10, tit: "¿Qué pasa en el hogar?"},
        {url: "https://uqload.com/embed-sjc0ql2v1ltk.html", tem: 6, epi: 11, tit: "25 a la vida"},
        {url: "https://feurl.com/v/40vxqe5ly98", tem: 6, epi: 12, tit: "Corazón"},
        {url: "https://feurl.com/v/8g9zqx50y9d", tem: 6, epi: 13, tit: "La decimotercera etapa"},
        {url: "https://uqload.com/embed-7xl6sxoqh0ck.html", tem: 6, epi: 14, tit: "El sentido de la memoria"},
        {url: "https://feurl.com/v/7qv70q10w9g", tem: 6, epi: 15, tit: "Hoy tengo que hacer"},
        {url: "https://feurl.com/v/8godrd7wpvy", tem: 6, epi: 16, tit: "Coda"},
        {url: "https://feurl.com/v/4lo0klgjxvq", tem: 6, epi: 17, tit: "Valhalla"},
        {url: "https://feurl.com/v/40oxq265yv8", tem: 6, epi: 18, tit: "Lauren"},
        {url: "https://feurl.com/v/5jo46kgjxv0", tem: 6, epi: 19, tit: "Con amigos como estos"},
        {url: "https://feurl.com/v/7qv70q1jw9g", tem: 6, epi: 20, tit: "Aguas de Hanley"},
        {url: "https://feurl.com/v/2wvmlkq0l96", tem: 6, epi: 21, tit: "El extraño"},
        {url: "https://feurl.com/v/05vllkqgnv6", tem: 6, epi: 22, tit: "Desde la luz"},
        {url: "https://feurl.com/v/7qo70q18wvg", tem: 6, epi: 23, tit: "El mar inmenso"},
        {url: "https://uqload.com/embed-0zerd5jhcsrd.html", tem: 6, epi: 24, tit: "Oferta y demanda"},
        {url: "https://feurl.com/v/yx934m6rqvl", tem: 7, epi: 1, tit: "Se necesita a todo un pueblo"},
        {url: "https://feurl.com/v/1lo6dl06l95", tem: 7, epi: 2, tit: "Prueba"},
        {url: "https://feurl.com/v/8godrdk2pvy", tem: 7, epi: 3, tit: "Dorado Falls"},
        {url: "https://feurl.com/v/7qv70qr7w9g", tem: 7, epi: 4, tit: "Sin dolor"},
        {url: "https://feurl.com/v/8g9zq37zy9d", tem: 7, epi: 5, tit: "Desde la infancia"},
        {url: "https://feurl.com/v/80oepg2k7vj", tem: 7, epi: 6, tit: "Epílogo"},
        {url: "https://feurl.com/v/6mo23m4dd9r", tem: 7, epi: 7, tit: "No hay nada como el hogar"},
        {url: "https://feurl.com/v/549yq4jpxvl", tem: 7, epi: 8, tit: "Esperanza"},
        {url: "https://feurl.com/v/p6ogkwqmx9j", tem: 7, epi: 9, tit: "Premonición autocumplida"},
        {url: "https://feurl.com/v/yx934m67qvl", tem: 7, epi: 10, tit: "La ciencia agridulce"},
        {url: "https://feurl.com/v/3q91zp342vy", tem: 7, epi: 11, tit: "La verdadera genialidad"},
        {url: "https://feurl.com/v/8xope5y4q97", tem: 7, epi: 12, tit: "Sujeto desconocido"},
        {url: "https://feurl.com/v/1lo6dl0rl95", tem: 7, epi: 13, tit: "Ojos de serpiente"},
        {url: "https://feurl.com/v/7qv70qrpw9g", tem: 7, epi: 14, tit: "Hora de cierre"},
        {url: "https://feurl.com/v/3qv1zpm72oy", tem: 7, epi: 15, tit: "Poca cosa"},
        {url: "https://feurl.com/v/1l96dl08lv5", tem: 7, epi: 16, tit: "Un asunto familiar"},
        {url: "https://feurl.com/v/7z9-r0z229x", tem: 7, epi: 17, tit: "Te quiero, Tommy Brown"},
        {url: "https://feurl.com/v/pmv57mdx89l", tem: 7, epi: 18, tit: "Cimientos"},
        {url: "https://feurl.com/v/80oepg2j7vj", tem: 7, epi: 19, tit: "Heathridge Manor"},
        {url: "https://feurl.com/v/40oxq24kyv8", tem: 7, epi: 20, tit: "La compañía"},
        {url: "https://feurl.com/v/8g9drdknpoy", tem: 7, epi: 21, tit: "Varita de zahorí"},
        {url: "https://feurl.com/v/zyonl3qz891", tem: 7, epi: 22, tit: "Criminología básica"},
        {url: "https://feurl.com/v/eno8rjp1091", tem: 7, epi: 23, tit: "Impacto"},
        {url: "https://feurl.com/v/dwvrl0y2pvg", tem: 8, epi:1, tit: "El silenciador"},
        {url: "https://feurl.com/v/5j946k7yxo0", tem: 8, epi: 2, tit: "El pacto"},
        {url: "https://feurl.com/v/4l90kl5qxoq", tem: 8, epi: 3, tit: "A través del espejo"},
        {url: "https://feurl.com/v/549yq42gxvl", tem: 8, epi: 4, tit: "Complejo de Dios"},
        {url: "https://feurl.com/v/7qo70qrgwvg", tem: 8, epi: 5, tit: "La buena Tierra"},
        {url: "https://feurl.com/v/3qv1zp352oy", tem: 8, epi: 6, tit: "El aprendizaje"},
        {url: "https://feurl.com/v/8x9pe5yzqv7", tem: 8, epi: 7, tit: "Los caídos"},
        {url: "https://feurl.com/v/1x9ql7ymxv4", tem: 8, epi: 8, tit: "Las ruedas del autobús"},
        {url: "https://feurl.com/v/2wvmlkm7l96", tem: 8, epi: 9, tit: "Gloriosa luz"},
        {url: "https://feurl.com/v/mz9kl2k31vq", tem: 8, epi: 10, tit: "La lección"},
        {url: "https://feurl.com/v/8gvzq37nyvd", tem: 8, epi: 11, tit: "Perennes"},
        {url: "https://feurl.com/v/2wvmlkypl96", tem: 8, epi: 12, tit: "Zugzwang"},
        {url: "https://feurl.com/v/p6ogk53mx9j", tem: 8, epi: 13, tit: "Obra maestra"},
        {url: "https://uqload.com/embed-y8gd8yho7v2g.html", tem: 8, epi: 14, tit: "Lo único que queda"},
        {url: "https://feurl.com/v/059llrj6n96", tem: 8, epi: 15, tit: "Roto"},
        {url: "https://feurl.com/v/3qo1zp3029y", tem: 8, epi: 16, tit: "Duplicado"},
        {url: "https://feurl.com/v/p6vgkwq5xoj", tem: 8, epi: 17, tit: "La reunión"},
        {url: "https://feurl.com/v/8gvdrd6xp9y", tem: 8, epi: 18, tit: "Restauración"},
        {url: "https://feurl.com/v/env8rjpq0o1", tem: 8, epi: 19, tit: "Devuelve el favor"},
        {url: "https://feurl.com/v/zy9nl3yn8v1", tem: 8, epi: 20, tit: "Alquimia"},
        {url: "https://uqload.com/embed-ichchgdq4wtz.html", tem: 8, epi: 21, tit: "Mi querida niñera"},
        {url: "https://feurl.com/v/7z9-r0pl29x", tem: 8, epi: 22, tit: "Número seis"},
        {url: "https://feurl.com/v/1l96dlx3lv5", tem: 8, epi: 23, tit: "Hermanos Hotchner"},
        {url: "https://feurl.com/v/env8r-340o1", tem: 9, epi:1, tit: "La inspiración (Parte 1)"},
        {url: "https://feurl.com/v/8godrd4gpvy", tem: 9, epi: 2, tit: "Los inspirados (Parte 2)"},
        {url: "https://feurl.com/v/6mo23m0yd9r", tem: 9, epi: 3, tit: "Tiro de gracia"},
        {url: "https://uqload.com/embed-9haxaq1g40pj.html", tem: 9, epi: 4, tit: "Dar testimonio"},
        {url: "https://feurl.com/v/3q91zx6w2vy", tem: 9, epi: 5, tit: "Ruta 66"},
        {url: "https://feurl.com/v/80oepg637vj", tem: 9, epi: 6, tit: "En la sangre"},
        {url: "https://feurl.com/v/3q91zpd82vy", tem: 9, epi: 7, tit: "Portero"},
        {url: "https://uqload.com/embed-2d81b6cg9tg2.html", tem: 9, epi: 8, tit: "El regreso"},
        {url: "https://uqload.com/embed-m9msdehxzg7s.html", tem: 9, epi: 9, tit: "Fruta extraña"},
        {url: "https://uqload.com/embed-4p9dkjr3bl7n.html", tem: 9, epi: 10, tit: "El anónimo"},
        {url: "https://feurl.com/v/pm957-j18ol", tem: 9, epi: 11, tit: "Matón"},
        {url: "https://feurl.com/v/8gvzq30qyvd", tem: 9, epi: 12, tit: "La reina negra"},
        {url: "https://uqload.com/embed-sv6989rmj7p0.html", tem: 9, epi: 13, tit: "El camino a casa"},
        {url: "https://uqload.com/embed-3awtcccqn34o.html", tem: 9, epi: 14, tit: "200"},
        {url: "https://feurl.com/v/8xvpe5dxqo7", tem: 9, epi: 15, tit: "El Sr. y la Sra. Anderson"},
        {url: "https://feurl.com/v/mzvkl21-1oq", tem: 9, epi: 16, tit: "Gabby"},
        {url: "https://feurl.com/v/7z9-r03z29x", tem: 9, epi: 17, tit: "Persuasión"},
        {url: "https://feurl.com/v/5j946kplxo0", tem: 9, epi: 18, tit: "Rabioso"},
        {url: "https://feurl.com/v/1l96dl3xlv5", tem: 9, epi: 19, tit: "Al filo del invierno"},
        {url: "https://uqload.com/embed-hkv6hyt0ov7a.html", tem: 9, epi: 20, tit: "Parentescos de sangre"},
        {url: "https://feurl.com/v/dwvrl0rjpvg", tem: 9, epi: 21, tit: "Lo que pasa en Mecklinburg..."},
        {url: "https://feurl.com/v/pmv57m1w89l", tem: 9, epi: 22, tit: "Fatal"},
        {url: "https://feurl.com/v/059llk2zn96", tem: 9, epi: 23, tit: "Ángeles (1)"},
        {url: "https://feurl.com/v/8x9pe5dlqv7", tem: 9, epi: 24, tit: "Demonios (2)"},
        {url: "https://feurl.com/v/549yq4djxvl", tem: 10, epi:1, tit: "X"},
        {url: "https://feurl.com/v/4dvj2ep1yo1", tem: 10, epi: 2, tit: "Quemar"},
        {url: "https://feurl.com/v/7qv70q4pw9g", tem: 10, epi: 3, tit: "Mil soles"},
        {url: "https://feurl.com/v/zyonl36q891", tem: 10, epi: 4, tit: "El picor"},
        {url: "https://feurl.com/v/7z9-r03q29x", tem: 10, epi: 5, tit: "En caja"},
        {url: "https://uqload.com/embed-cp1l8bzk75b9.html", tem: 10, epi: 6, tit: "Si el zapato calza"},
        {url: "https://feurl.com/v/40oxq27gyv8", tem: 10, epi: 7, tit: "Hashtag"},
        {url: "https://feurl.com/v/mz9kl2161vq", tem: 10, epi: 8, tit: "The Boys of Sudworth Place"},
        {url: "https://feurl.com/v/5jo46kpdxv0", tem: 10, epi: 9, tit: "Destino"},
        {url: "https://feurl.com/v/5jo46kpwxv0", tem: 10, epi: 10, tit: "Amelia Porter"},
        {url: "https://feurl.com/v/7qv70q46w9g", tem: 10, epi: 11, tit: "La gente para siempre"},
        {url: "https://feurl.com/v/6mo23m0wd9r", tem: 10, epi: 12, tit: "Anónimo"},
        {url: "https://feurl.com/v/05ollk2dno6", tem: 10, epi: 13, tit: "Gorrión de Nelson"},
        {url: "https://uqload.com/embed-68ipz42uvh9k.html", tem: 10, epi: 14, tit: "Culto a los héroes"},
        {url: "https://feurl.com/v/1xoql7-rx94", tem: 10, epi: 15, tit: "Gritar"},
        {url: "https://feurl.com/v/80oepg307vj", tem: 10, epi: 16, tit: "Lockdown"},
        {url: "https://feurl.com/v/5jo46k5xxv0", tem: 10, epi: 17, tit: "Breath Play"},
        {url: "https://feurl.com/v/1lo6dly1l95", tem: 10, epi: 18, tit: "Rock Creek Park"},
        {url: "https://feurl.com/v/dw9rl0-5p9g", tem: 10, epi: 19, tit: "Más allá de las fronteras"},
        {url: "https://feurl.com/v/8g9zq3y6y9d", tem: 10, epi: 20, tit: "Un lugar en la mesa"},
        {url: "https://feurl.com/v/1x9ql7--xv4", tem: 10, epi: 21, tit: "Sr. Scratch"},
        {url: "https://feurl.com/v/2w9mlk15lo6", tem: 10, epi: 22, tit: "Proteccion"},
        {url: "https://feurl.com/v/54vyq48rxol", tem: 10, epi: 23, tit: "La caza"},
        {url: "https://feurl.com/v/8godr37gpvy", tem: 11, epi: 22, tit: "La Tormenta"},
        {url: "https://feurl.com/v/yxo34m2jq9l", tem: 11, epi: 1, tit: "El trabajo"},
        {url: "https://feurl.com/v/6mo2j71jdvr", tem: 11, epi: 2, tit: "El testigo"},
        {url: "https://uqload.com/embed-tlri3a5jrylh.html", tem: 11, epi: 3, tit: "Hasta que la muerte nos separe"},
        {url: "https://feurl.com/v/4lv0kl7jx9q", tem: 11, epi: 4, tit: "Fuera de la ley"},
        {url: "https://feurl.com/v/4d9j2ep-yv1", tem: 11, epi: 5, tit: "Vigilancia nocturna"},
        {url: "https://feurl.com/v/8g9drd46poy", tem: 11, epi: 6, tit: "Villa Paria"},
        {url: "https://feurl.com/v/1xoql706x94", tem: 11, epi: 7, tit: "Abundancia de objetivos"},
        {url: "https://feurl.com/v/3qv1zpdm2oy", tem: 11, epi: 8, tit: "Despiertos"},
        {url: "https://feurl.com/v/mz9kl21k1vq", tem: 11, epi: 9, tit: "Asuntos Internos"},
        {url: "https://feurl.com/v/dworl0r8pog", tem: 11, epi: 10, tit: "Futuro Perfecto"},
        {url: "https://feurl.com/v/1x9ql70jxv4", tem: 11, epi: 11, tit: "Entropía"},
        {url: "https://feurl.com/v/6m923m0qdvr", tem: 11, epi: 12, tit: "Conduce"},
        {url: "https://feurl.com/v/809epg677oj", tem: 11, epi: 13, tit: "El lazo"},
        {url: "https://feurl.com/v/1lv6dl35lo5", tem: 11, epi: 14, tit: "Rehén"},
        {url: "https://feurl.com/v/7zv-r03p2vx", tem: 11, epi: 15, tit: "Una placa y una pistola"},
        {url: "https://feurl.com/v/1lv6dyyxlo5", tem: 11, epi: 16, tit: "Derek"},
        {url: "https://uqload.com/embed-wlrfxk6w2hf9.html", tem: 11, epi: 17, tit: "El hombre de arena"},
        {url: "https://feurl.com/v/5jo46ng4xv0", tem: 11, epi: 18, tit: "Un Bonito Desastre"},
        {url: "https://feurl.com/v/env8rqx60o1", tem: 11, epi: 19, tit: "Tributo"},
        {url: "https://feurl.com/v/80oep4d37vj", tem: 11, epi: 20, tit: "Belleza interior"},
        {url: "https://feurl.com/v/8g9zqp2yy9d", tem: 11, epi: 21, tit: "El espinazo del diablo"},
        {url: "https://feurl.com/v/8godr37gpvy", tem: 11, epi: 22, tit: "La Tormenta"},*/
        {url: "https://uqload.com/embed-780rkzqcvr1z.html", tem: 1, epi: 1, tit: "Agresor Cruel"},
        {url: "https://uqload.com/embed-zsss3nhzhnj9.html", tem: 1, epi: 2, tit: "Obligación"},
        {url: "https://uqload.com/embed-x9exig63zbs4.html", tem: 1, epi: 3, tit: "No me Engañarás Otra Vez"},
        {url: "https://uqload.com/embed-qq7wj2fr1izp.html", tem: 1, epi: 4, tit: "A Simple Vista"},
        {url: "https://uqload.com/embed-clu67tap0vyu.html", tem: 1, epi: 5, tit: "Espejo Roto"},
        {url: "https://uqload.com/embed-p4rwsdk7ndoi.html", tem: 1, epi: 6, tit: "Asesinos a Larga Distancia"},
        {url: "https://uqload.com/embed-qqj4jeuacn1b.html", tem: 1, epi: 7, tit: "El Zorro"},
        {url: "https://feurl.com/v/2w9mlke4lo6", tem: 1, epi: 8, tit: "Asesino Nato"},
        {url: "https://uqload.com/embed-tx9l41qb2ojw.html", tem: 1, epi: 9, tit: "Descarrilado"},
        {url: "https://uqload.com/embed-kaddo5me8w9r.html", tem: 1, epi: 10, tit: "Los Niños Buenos"},
        {url: "https://uqload.com/embed-mli2yxsp1why.html", tem: 1, epi: 11, tit: "Hambriento de Sangre"},
        {url: "https://uqload.com/embed-4r7bo3d3bxbm.html", tem: 1, epi: 12, tit: "Lo Que Faltaba"},
        {url: "https://uqload.com/embed-f0cwa5z7c2lf.html", tem: 1, epi: 13, tit: "Veneno"},
        {url: "https://uqload.com/embed-838blh5pzktw.html", tem: 1, epi: 14, tit: "Alcanzar el Relámpago"},
        {url: "https://uqload.com/embed-vj8qqwkz62xi.html", tem: 1, epi: 16, tit: "La Tribu"},
        {url: "https://uqload.com/embed-5fptq5o65ksp.html", tem: 1, epi: 18, tit: "Alguien te Vigila"},
        {url: "https://uqload.com/embed-tldehgybtxac.html", tem: 1, epi: 19, tit: "Machismo"},
        {url: "https://uqload.com/embed-18cvbmdfphye.html", tem: 1, epi: 20, tit: "Daño y encanto"},
        {url: "https://uqload.com/embed-8dqoe9dqovv1.html", tem: 1, epi: 21, tit: "Secretos y Mentiras"},
        {url: "https://uqload.com/embed-yqz504dr4tr4.html", tem: 1, epi: 22, tit: "El Rey Pescador (parte 1)"},
        {url: "https://uqload.com/embed-niuqqmue9ipt.html", tem: 2, epi: 2, tit: "P911"},
        {url: "https://uqload.com/embed-cnw5roa439ck.html", tem: 2, epi: 3, tit: "La tormenta perfecta"},
        {url: "https://uqload.com/embed-ya6q122p40kg.html", tem: 2, epi: 4, tit: "Psicodrama"},
        {url: "https://uqload.com/embed-eunlqkgtm7po.html", tem: 2, epi: 5, tit: "Secuelas"},
        {url: "https://uqload.com/embed-tdcjs2hdinkz.html", tem: 2, epi: 6, tit: "The Boogeyman"},
        {url: "https://uqload.com/embed-qwigtaao2fj9.html", tem: 2, epi: 7, tit: "Norte de Mammon"},
        {url: "https://uqload.com/embed-yb1orl1iaf8c.html", tem: 2, epi: 9, tit: "La última palabra"},
        {url: "https://uqload.com/embed-psq2j4coy6fs.html", tem: 2, epi: 10, tit: "Lecciones Aprendidas"},
        {url: "https://uqload.com/embed-tu2ovl7wko3x.html", tem: 2, epi: 11, tit: "Sexo, Nacimiento, Muerte"},
        {url: "https://feurl.com/v/7z9-r0xe29x", tem: 2, epi: 12, tit: "Profiler, perfilado"},
        {url: "https://uqload.com/embed-6rk7momqoj8m.html", tem: 2, epi: 14, tit: "El gran juego"},
        {url: "https://uqload.com/embed-fasi7k8x3u5o.html", tem: 2, epi: 16, tit: "Miedo y odio"},
        {url: "https://uqload.com/embed-ipp14suztsm4.html", tem: 2, epi: 17, tit: "Angustia"},
        {url: "https://uqload.com/embed-hl25a4wdbv3c.html", tem: 2, epi: 18, tit: "Jones"},
        {url: "https://uqload.com/embed-vxzlaxyclkpz.html", tem: 2, epi: 19, tit: "Cenizas y Polvo"},
        {url: "https://uqload.com/embed-dpcue6ppgp8k.html", tem: 2, epi: 20, tit: "Honor entre Ladrones"},
        {url: "https://uqload.com/embed-5zxwzmaig74d.html", tem: 3, epi: 1, tit: "Duda"},
        {url: "https://uqload.com/embed-5f3rx1ssghai.html", tem: 3, epi: 2, tit: "En Nombre y Sangre"},
        {url: "https://feurl.com/v/pmo57mgm8vl", tem: 3, epi: 3, tit: "Muerto de Miedo"},
        {url: "https://uqload.com/embed-2w9j74y8u1i2.html", tem: 3, epi: 4, tit: "Niños de la Oscuridad"},
        {url: "https://uqload.com/embed-jik3fxlj046u.html", tem: 3, epi: 5, tit: "Siete segundos"},
        {url: "https://feurl.com/v/4d9j2eqwyv1", tem: 3, epi: 6, tit: "Acerca de Face"},
        {url: "https://uqload.com/embed-7ilsxoqde0tx.html", tem: 3, epi: 7, tit: "Identidad"},
        {url: "https://uqload.com/embed-ty92mxmp3upb.html", tem: 3, epi: 8, tit: "Suerte"},
        {url: "https://uqload.com/embed-rlb2lxv0x7bf.html", tem: 3, epi: 9, tit: "Penélope"},
        {url: "https://uqload.com/embed-3aqy4jokao95.html", tem: 3, epi: 11, tit: "Patrimonio"},
        {url: "https://uqload.com/embed-npxuwxtfhc9q.html", tem: 3, epi: 13, tit: "Luz de calcio"},
        {url: "https://uqload.com/embed-6cpwcvmgopls.html", tem: 3, epi: 14, tit: "Dañado"},
        {url: "https://uqload.com/embed-8alk6m3daygw.html", tem: 3, epi: 15, tit: "Un Poder Superior"},
        {url: "https://uqload.com/embed-8ryloisn1mgu.html", tem: 3, epi: 16, tit: "La Memoria del Elefante"},
        {url: "https://uqload.com/embed-q8ik1rnjlbif.html", tem: 3, epi: 17, tit: "En calor"},
        {url: "https://uqload.com/embed-bnjh4k3qjsn0.html", tem: 3, epi: 19, tit: "Tabula Rasa"},
        {url: "https://uqload.com/embed-3pptbje4imcw.html", tem: 3, epi: 20, tit: "Lo-Fi"},
        {url: "https://feurl.com/v/3q91zpgj2vy", tem: 4, epi: 2, tit: "El Angel Maker"},
        {url: "https://uqload.com/embed-op407ader3z3.html", tem: 4, epi: 3, tit: "Pérdida Mínima"},
        {url: "https://uqload.com/embed-4qmcddf4lofl.html", tem: 4, epi: 4, tit: "Paraíso"},
        {url: "https://uqload.com/embed-83q464ax6qrh.html", tem: 4, epi: 5, tit: "Catching Out"},
        {url: "https://uqload.com/embed-govqcfdtmou4.html", tem: 4, epi: 6, tit: "Los Instintos"},
        {url: "https://uqload.com/embed-7du6wekkmvs3.html", tem: 4, epi: 7, tit: "Memoriam"},
        {url: "https://uqload.com/embed-tgz2zenus6ry.html", tem: 4, epi: 8, tit: "Obra Maestra"},
        {url: "https://uqload.com/embed-qm147oj6gghz.html", tem: 4, epi: 9, tit: "52 Recogida"},
        {url: "https://uqload.com/embed-seb6sllha8c9.html", tem: 4, epi: 10, tit: "Compañeros de Armas"},
        {url: "https://uqload.com/embed-l8qpnie1ynmh.html", tem: 4, epi: 11, tit: "Normal"},
        {url: "https://feurl.com/v/7yvwqmy2xvj", tem: 4, epi: 12, tit: "Almas Gemelas"},
        {url: "https://uqload.com/embed-kggmhfm8k9lh.html", tem: 4, epi: 13, tit: "Bloodline"},
        {url: "https://uqload.com/embed-shgc9bft9h0i.html", tem: 4, epi: 14, tit: "Confort Frío"},
        {url: "https://uqload.com/embed-vzgxv8ngw9zs.html", tem: 4, epi: 15, tit: "Reprise de Zoe"},
        {url: "https://feurl.com/v/05ollk56no6", tem: 4, epi: 16, tit: "El Placer es Mi Negocio"},
        {url: "https://uqload.com/embed-cdha6ke7ehwl.html", tem: 4, epi: 17, tit: "Demonología"},
        {url: "https://uqload.com/embed-986ukcqxghbe.html", tem: 4, epi: 18, tit: "Omnívoro"},
        {url: "https://uqload.com/embed-rvydwgc7q7bj.html", tem: 4, epi: 19, tit: "Casa en Llamas"},
        {url: "https://uqload.com/embed-s0hd4o18z5ab.html", tem: 4, epi: 20, tit: "Conflicto"},
        {url: "https://uqload.com/embed-80evlo6l0ruz.html", tem: 4, epi: 21, tit: "Una Sombra de Gris"},
        {url: "https://uqload.com/embed-1obftz31xlvq.html", tem: 4, epi: 22, tit: "La Gran Rueda"},
        {url: "https://uqload.com/embed-u3a4xnfwlg5q.html", tem: 4, epi: 23, tit: "Roadkill"},
        {url: "https://uqload.com/embed-3o0z7cyex7gi.html", tem: 4, epi: 24, tit: "Amplificación"},
        {url: "https://uqload.com/embed-la2r1czyta5f.html", tem: 4, epi: 25, tit: "Al Infierno y de Regreso"},
        {url: "https://uqload.com/embed-un4dur4s6e3l.html", tem: 5, epi: 1, tit: "Sin Rostro, Sin Nombre"},
        {url: "https://uqload.com/embed-63z6qbmc1mj6.html", tem: 5, epi: 2, tit: "Obsesionado"},
        {url: "https://uqload.com/embed-xkv68y9n8kue.html", tem: 5, epi: 3, tit: "Calculadora"},
        {url: "https://uqload.com/embed-vek1hgqwbdrd.html", tem: 5, epi: 4, tit: "Sin Esperanza"},
        {url: "https://uqload.com/embed-2be4k8t5ybn3.html", tem: 5, epi: 6, tit: "Los Ojos lo Tienen"},
        {url: "https://feurl.com/v/8g9zq300y9d", tem: 5, epi: 7, tit: "El Artista"},
        {url: "https://uqload.com/embed-6sf1qp9ckwgo.html", tem: 5, epi: 8, tit: "Outfoxed"},
        {url: "https://uqload.com/embed-nq6izyjwgqkb.html", tem: 5, epi: 9, tit: "100 (Parte 2)"},
        {url: "https://uqload.com/embed-dagqla6wfvwn.html", tem: 5, epi: 10, tit: "El Esclavo del Deber"},
        {url: "https://uqload.com/embed-wwk3y51gshi0.html", tem: 5, epi: 12, tit: "El Valle de Uncanny"},
        {url: "https://uqload.com/embed-1cdm84z8p5l9.html", tem: 5, epi: 13, tit: "Negocio Arriesgado"},
        {url: "https://uqload.com/embed-5thg61dgy3m2.html", tem: 5, epi: 14, tit: "Parásito"},
        {url: "https://uqload.com/embed-q4lkcfdrf0ol.html", tem: 5, epi: 15, tit: "Enemigo Público"},
        {url: "https://uqload.com/embed-yrhz2gpjxqvo.html", tem: 5, epi: 16, tit: "Mosley Lane"},
        {url: "https://uqload.com/embed-848v0u5jkers.html", tem: 5, epi: 17, tit: "Hombre Solitario"},
        {url: "https://uqload.com/embed-b93vx2ecs8ig.html", tem: 5, epi: 19, tit: "Un rito de pasaje"},
        {url: "https://uqload.com/embed-br6lv79op9oi.html", tem: 5, epi: 20, tit: "Más que Mil Palabras"},
        {url: "https://uqload.com/embed-9c59mbeo88d6.html", tem: 5, epi: 21, tit: "Herida Abierta"},
        {url: "https://uqload.com/embed-o65vqeofukmd.html", tem: 5, epi: 22, tit: "Internet es para Siempre"},
        {url: "https://uqload.com/embed-7fk7meamr5eq.html", tem: 5, epi: 23, tit: "Nuestra hora más Oscura"},
        {url: "https://uqload.com/embed-up2utxy4aip6.html", tem: 6, epi: 1, tit: "La noche mas larga"},
        {url: "https://uqload.com/embed-dvvhvhm2jkrh.html", tem: 6, epi: 2, tit: "JJ"},
        {url: "https://uqload.com/embed-rlrxd63txg13.html", tem: 6, epi: 4, tit: "Situaciones comprometidas"},
        {url: "https://uqload.com/embed-jeo8ynxro32x.html", tem: 6, epi: 5, tit: "Beneficencia"},
        {url: "https://uqload.com/embed-9s4p7xp6crk4.html", tem: 6, epi: 6, tit: "Cerca del diablo"},
        {url: "https://uqload.com/embed-8vzv5u0jxbsl.html", tem: 6, epi: 7, tit: "Intermediario"},
        {url: "https://uqload.com/embed-19r81wf7shrv.html", tem: 6, epi: 8, tit: "Reflexión de deseo"},
        {url: "https://uqload.com/embed-b4tbyt9eqvvw.html", tem: 6, epi: 9, tit: "En el bosque"},
        {url: "https://uqload.com/embed-4hf8maav3l9v.html", tem: 6, epi: 10, tit: "¿Qué pasa en el hogar?"},
        {url: "https://uqload.com/embed-sjc0ql2v1ltk.html", tem: 6, epi: 11, tit: "25 a la vida"},
        {url: "https://uqload.com/embed-5a26o8958urj.html", tem: 6, epi: 12, tit: "Corazón"},
        {url: "https://uqload.com/embed-izp72y7flgu2.html", tem: 6, epi: 13, tit: "La decimotercera etapa"},
        {url: "https://uqload.com/embed-7xl6sxoqh0ck.html", tem: 6, epi: 14, tit: "El sentido de la memoria"},
        {url: "https://uqload.com/embed-ha2ub50ulc8y.html", tem: 6, epi: 15, tit: "Hoy tengo que hacer"},
        {url: "https://uqload.com/embed-lt48zibrr88p.html", tem: 6, epi: 16, tit: "Coda"},
        {url: "https://uqload.com/embed-nbrlihugvx2h.html", tem: 6, epi: 17, tit: "Valhalla"},
        {url: "https://uqload.com/embed-fdzsb919gxjf.html", tem: 6, epi: 18, tit: "Lauren"},
        {url: "https://feurl.com/v/5jo46kgjxv0", tem: 6, epi: 19, tit: "Con amigos como estos"},
        {url: "https://feurl.com/v/7qv70q1jw9g", tem: 6, epi: 20, tit: "Aguas de Hanley"},
        {url: "https://uqload.com/embed-jt6pdul15yc9.html", tem: 6, epi: 21, tit: "El extraño"},
        {url: "https://feurl.com/v/05vllkqgnv6", tem: 6, epi: 22, tit: "Desde la luz"},
        {url: "https://uqload.com/embed-aq418yecno6g.html", tem: 6, epi: 23, tit: "El mar inmenso"},
        {url: "https://uqload.com/embed-0zerd5jhcsrd.html", tem: 6, epi: 24, tit: "Oferta y demanda"},
        {url: "https://uqload.com/embed-217g84v19bz1.html", tem: 7, epi: 1, tit: "Se necesita a todo un pueblo"},
        {url: "https://uqload.com/embed-21au13zm8ume.html", tem: 7, epi: 2, tit: "Prueba"},
        {url: "https://uqload.com/embed-st4b8uxm833d.html", tem: 7, epi: 3, tit: "Dorado Falls"},
        {url: "https://uqload.com/embed-do2rb1v9mikk.html", tem: 7, epi: 4, tit: "Sin dolor"},
        {url: "https://uqload.com/embed-aec1spkapcvl.html", tem: 7, epi: 5, tit: "Desde la infancia"},
        {url: "https://uqload.com/embed-q6bql7s2hord.html", tem: 7, epi: 6, tit: "Epílogo"},
        {url: "https://uqload.com/embed-4kmwkv7ujaeb.html", tem: 7, epi: 8, tit: "Esperanza"},
        {url: "https://uqload.com/embed-26e1z47mzp01.html", tem: 7, epi: 9, tit: "Premonición autocumplida"},
        {url: "https://uqload.com/embed-cis702lmkm5c.html", tem: 7, epi: 10, tit: "La ciencia agridulce"},
        {url: "https://uqload.com/embed-1oimf0z1w8ws.html", tem: 7, epi: 13, tit: "Ojos de serpiente"},
        {url: "https://uqload.com/embed-6pdxtaf3zesx.html", tem: 7, epi: 16, tit: "Un asunto familiar"},
        {url: "https://uqload.com/embed-wa4ab5a2q0ms.html", tem: 7, epi: 19, tit: "Heathridge Manor"},
        {url: "https://uqload.com/embed-1w902a0bberm.html", tem: 7, epi: 20, tit: "La compañía"},
        {url: "https://uqload.com/embed-v0icfnw0q6lr.html", tem: 7, epi: 21, tit: "Varita de zahorí"},
        {url: "https://feurl.com/v/zyonl3qz891", tem: 7, epi: 22, tit: "Criminología básica"},
        {url: "https://uqload.com/embed-yasju80mx150.html", tem: 7, epi: 23, tit: "Impacto"},
        {url: "https://uqload.com/embed-yu5ok5qdaqyc.html", tem: 8, epi: 1, tit: "El silenciador"},
        {url: "https://uqload.com/embed-39gg0w3m72j1.html", tem: 8, epi: 2, tit: "El pacto"},
        {url: "https://uqload.com/embed-fho2bb3zyw96.html", tem: 8, epi: 3, tit: "A través del espejo"},
        {url: "https://uqload.com/embed-5a0amdslvjgl.html", tem: 8, epi: 4, tit: "Complejo de Dios"},
        {url: "https://uqload.com/embed-6sz7kf1k9cjg.html", tem: 8, epi: 9, tit: "Gloriosa luz"},
        {url: "https://uqload.com/embed-hscqx1qi9qh1.html", tem: 8, epi: 10, tit: "La lección"},
        {url: "https://uqload.com/embed-xbt9clry1wqq.html", tem: 8, epi: 12, tit: "Zugzwang"},
        {url: "https://uqload.com/embed-dohq0wbc6bgu.html", tem: 8, epi: 13, tit: "Obra maestra"},
        {url: "https://uqload.com/embed-y8gd8yho7v2g.html", tem: 8, epi: 14, tit: "Lo único que queda"},
        {url: "https://uqload.com/embed-5ic0ddnyho18.html", tem: 8, epi: 15, tit: "Roto"},
        {url: "https://uqload.com/embed-p49luk1gnfgs.html", tem: 8, epi: 16, tit: "Duplicado"},
        {url: "https://uqload.com/embed-yeo0xfjv03sf.html", tem: 8, epi: 17, tit: "La reunión"},
        {url: "https://uqload.com/embed-f69kkimzotwv.html", tem: 8, epi: 18, tit: "Restauración"},
        {url: "https://uqload.com/embed-2tab1gx8afzp.html", tem: 8, epi: 19, tit: "Devuelve el favor"},
        {url: "https://uqload.com/embed-pjradr0hk381.html", tem: 8, epi: 20, tit: "Alquimia"},
        {url: "https://uqload.com/embed-ichchgdq4wtz.html", tem: 8, epi: 21, tit: "Mi querida niñera"},
        {url: "https://uqload.com/embed-4vc59lth835s.html", tem: 8, epi: 23, tit: "Hermanos Hotchner"},
        {url: "https://feurl.com/v/env8r-340o1", tem: 9, epi: 1, tit: "La inspiración (Parte 1)"},
        {url: "https://uqload.com/embed-aa6kc44p3e7x.html", tem: 9, epi: 2, tit: "Los inspirados (Parte 2)"},
        {url: "https://uqload.com/embed-s2zfxc09dj2t.html", tem: 9, epi: 3, tit: "Tiro de gracia"},
        {url: "https://uqload.com/embed-9haxaq1g40pj.html", tem: 9, epi: 4, tit: "Dar testimonio"},
        {url: "https://uqload.com/embed-sv7pzwooak2x.html", tem: 9, epi: 5, tit: "Ruta 66"},
        {url: "https://uqload.com/embed-v2ys8bhx1691.html", tem: 9, epi: 6, tit: "En la sangre"},
        {url: "https://uqload.com/embed-4x5497fzat3x.html", tem: 9, epi: 7, tit: "Portero"},
        {url: "https://uqload.com/embed-2d81b6cg9tg2.html", tem: 9, epi: 8, tit: "El regreso"},
        {url: "https://uqload.com/embed-m9msdehxzg7s.html", tem: 9, epi: 9, tit: "Fruta extraña"},
        {url: "https://uqload.com/embed-4p9dkjr3bl7n.html", tem: 9, epi: 10, tit: "El anónimo"},
        {url: "https://uqload.com/embed-pjrdepl562r1.html", tem: 9, epi: 11, tit: "Matón"},
        {url: "https://uqload.com/embed-yior0c0fvbj3.html", tem: 9, epi: 12, tit: "La reina negra"},
        {url: "https://uqload.com/embed-sv6989rmj7p0.html", tem: 9, epi: 13, tit: "El camino a casa"},
        {url: "https://uqload.com/embed-3awtcccqn34o.html", tem: 9, epi: 14, tit: "200"},
        {url: "https://uqload.com/embed-o5hks0rigde2.html", tem: 9, epi: 15, tit: "El Sr. y la Sra. Anderson"},
        {url: "https://uqload.com/embed-0ejsi6e5ojna.html", tem: 9, epi: 16, tit: "Gabby"},
        {url: "https://uqload.com/embed-qhxk18jllwuv.html", tem: 9, epi: 17, tit: "Persuasión"},
        {url: "https://uqload.com/embed-zfog8081gehb.html", tem: 9, epi: 18, tit: "Rabioso"},
        {url: "https://uqload.com/embed-3pmsb1x3k4lx.html", tem: 9, epi: 19, tit: "Al filo del invierno"},
        {url: "https://uqload.com/embed-hkv6hyt0ov7a.html", tem: 9, epi: 20, tit: "Parentescos de sangre"},
        {url: "https://feurl.com/v/dwvrl0rjpvg", tem: 9, epi: 21, tit: "Lo que pasa en Mecklinburg..."},
        {url: "https://uqload.com/embed-01ewbi9gsy25.html", tem: 9, epi: 22, tit: "Fatal"},
        {url: "https://uqload.com/embed-tkw8zavj19uo.html", tem: 9, epi: 23, tit: "Ángeles (1)"},
        {url: "https://uqload.com/embed-qb0ncq5b664c.html", tem: 9, epi: 24, tit: "Demonios (2)"},
        {url: "https://uqload.com/embed-eiy07wuyxb3x.html", tem: 10, epi: 1, tit: "X"},
        {url: "https://uqload.com/embed-kch6jv49e0y7.html", tem: 10, epi: 2, tit: "Quemar"},
        {url: "https://uqload.com/embed-ig27ifzjkrmu.html", tem: 10, epi: 3, tit: "Mil soles"},
        {url: "https://uqload.com/embed-2uwt3mjcc1il.html", tem: 10, epi: 4, tit: "El picor"},
        {url: "https://uqload.com/embed-41au0mtv9siz.html", tem: 10, epi: 5, tit: "En caja"},
        {url: "https://uqload.com/embed-cp1l8bzk75b9.html", tem: 10, epi: 6, tit: "Si el zapato calza"},
        {url: "https://uqload.com/embed-dfy7l8fgh78l.html", tem: 10, epi: 7, tit: "Hashtag"},
        {url: "https://uqload.com/embed-3v1y4meebi5p.html", tem: 10, epi: 10, tit: "Amelia Porter"},
        {url: "https://feurl.com/v/7qv70q46w9g", tem: 10, epi: 11, tit: "La gente para siempre"},
        {url: "https://uqload.com/embed-bsmvucjv8jab.html", tem: 10, epi: 15, tit: "Gritar"},
        {url: "https://uqload.com/embed-hbwb1aguos4u.html", tem: 10, epi: 17, tit: "Breath Play"},
        {url: "https://uqload.com/embed-6fef5m4wiyej.html", tem: 10, epi: 18, tit: "Rock Creek Park"},
        {url: "https://uqload.com/embed-5w5up7j77rtr.html", tem: 10, epi: 19, tit: "Más allá de las fronteras"},
        {url: "https://uqload.com/embed-45qfyip6wdyv.html", tem: 10, epi: 20, tit: "Un lugar en la mesa"},
        {url: "https://uqload.com/embed-zvi8emjkmqyc.html", tem: 10, epi: 21, tit: "Sr. Scratch"},
        {url: "https://uqload.com/embed-rg4eyounlwu8.html", tem: 10, epi: 22, tit: "Proteccion"},
        {url: "https://uqload.com/embed-sogn5sfhq5nr.html", tem: 10, epi: 23, tit: "La caza"},
        {url: "https://uqload.com/embed-a666pfxkt9hb.html", tem: 11, epi: 1, tit: "El trabajo"},
        {url: "https://uqload.com/embed-geqr12ysvx3s.html", tem: 11, epi: 2, tit: "El testigo"},
        {url: "https://uqload.com/embed-pqucuabnlczu.html", tem: 11, epi: 4, tit: "Fuera de la ley"},
        {url: "https://uqload.com/embed-d9vy9bwgatan.html", tem: 11, epi: 5, tit: "Vigilancia nocturna"},
        {url: "https://uqload.com/embed-6hb3v7bawm3n.html", tem: 11, epi: 6, tit: "Villa Paria"},
        {url: "https://uqload.com/embed-eue7u5s0ztx9.html", tem: 11, epi: 7, tit: "Abundancia de objetivos"},
        {url: "https://uqload.com/embed-ndi837wpl9eh.html", tem: 11, epi: 8, tit: "Despiertos"},
        {url: "https://uqload.com/embed-7zd6hyu98w7l.html", tem: 11, epi: 9, tit: "Asuntos Internos"},
        {url: "https://uqload.com/embed-do00531xjd29.html", tem: 11, epi: 10, tit: "Futuro Perfecto"},
        {url: "https://feurl.com/v/1x9ql70jxv4", tem: 11, epi: 11, tit: "Entropía"},
        {url: "https://uqload.com/embed-uz27jnlm2esr.html", tem: 11, epi: 12, tit: "Conduce"},
        {url: "https://uqload.com/embed-brtna2i50i5p.html", tem: 11, epi: 13, tit: "El lazo"},
        {url: "https://uqload.com/embed-l05vv01czgq7.html", tem: 11, epi: 14, tit: "Rehén"},
        {url: "https://uqload.com/embed-wwgoeiy8aiym.html", tem: 11, epi: 15, tit: "Una placa y una pistola"},
        {url: "https://uqload.com/embed-4uw0e2proomg.html", tem: 11, epi: 16, tit: "Derek"},
        {url: "https://uqload.com/embed-wlrfxk6w2hf9.html", tem: 11, epi: 17, tit: "El hombre de arena"},
        {url: "https://uqload.com/embed-2pg4g5q6yrz4.html", tem: 11, epi: 18, tit: "Un Bonito Desastre"},
        {url: "https://uqload.com/embed-qrlut9yo3ghw.html", tem: 11, epi: 20, tit: "Belleza interior"},
        {url: "https://uqload.com/embed-mvtl5xh5awdc.html", tem: 11, epi: 21, tit: "El espinazo del diablo"},
        {url: "https://uqload.com/embed-rcwfi9zmnoi5.html", tem: 11, epi: 22, tit: "La Tormenta"},
        {url: "https://uqload.com/embed-a666pfxkt9hb.html", tem: 11, epi: 1, tit: "El trabajo"},
        {url: "https://uqload.com/embed-geqr12ysvx3s.html", tem: 11, epi: 2, tit: "El testigo"},
        {url: "https://uqload.com/embed-pqucuabnlczu.html", tem: 11, epi: 4, tit: "Fuera de la ley"},
        {url: "https://uqload.com/embed-d9vy9bwgatan.html", tem: 11, epi: 5, tit: "Vigilancia nocturna"},
        {url: "https://uqload.com/embed-6hb3v7bawm3n.html", tem: 11, epi: 6, tit: "Villa Paria"},
        {url: "https://uqload.com/embed-eue7u5s0ztx9.html", tem: 11, epi: 7, tit: "Abundancia de objetivos"},
        {url: "https://uqload.com/embed-ndi837wpl9eh.html", tem: 11, epi: 8, tit: "Despiertos"},
        {url: "https://uqload.com/embed-7zd6hyu98w7l.html", tem: 11, epi: 9, tit: "Asuntos Internos"},
        {url: "https://uqload.com/embed-do00531xjd29.html", tem: 11, epi: 10, tit: "Futuro Perfecto"},
        {url: "https://feurl.com/v/1x9ql70jxv4", tem: 11, epi: 11, tit: "Entropía"},
        {url: "https://uqload.com/embed-uz27jnlm2esr.html", tem: 11, epi: 12, tit: "Conduce"},
        {url: "https://uqload.com/embed-brtna2i50i5p.html", tem: 11, epi: 13, tit: "El lazo"},
        {url: "https://uqload.com/embed-l05vv01czgq7.html", tem: 11, epi: 14, tit: "Rehén"},
        {url: "https://uqload.com/embed-wwgoeiy8aiym.html", tem: 11, epi: 15, tit: "Una placa y una pistola"},
        {url: "https://uqload.com/embed-4uw0e2proomg.html", tem: 11, epi: 16, tit: "Derek"},
        {url: "https://uqload.com/embed-wlrfxk6w2hf9.html", tem: 11, epi: 17, tit: "El hombre de arena"},
        {url: "https://uqload.com/embed-2pg4g5q6yrz4.html", tem: 11, epi: 18, tit: "Un Bonito Desastre"},
        {url: "https://uqload.com/embed-qrlut9yo3ghw.html", tem: 11, epi: 20, tit: "Belleza interior"},
        {url: "https://uqload.com/embed-mvtl5xh5awdc.html", tem: 11, epi: 21, tit: "El espinazo del diablo"},
        {url: "https://uqload.com/embed-rcwfi9zmnoi5.html", tem: 11, epi: 22, tit: "La Tormenta"},
        {url: "https://uqload.com/embed-rcwfi9zmnoi5.html", tem: 11, epi: 22, tit: "La Tormenta"},
    ]
}