var json_data_serie = {
    data_serie: {
        serie: 'Lie To Me',
        tipo: "Temporada",
        favic: 'https://misterslimm.files.wordpress.com/2009/04/folder5.jpg?w=256',
        logot: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Lie_to_Me.svg',
        exter: 'https://pelisplushd.net/serie/mienteme',
        prima: 'rgb(168, 179, 234)',
        secun: 'rgb(68, 79, 134)',
        porta: 'https://2.bp.blogspot.com/-OqLDHhnM4lc/VaL1Gg8kR6I/AAAAAAAAMdY/EQ_kLCoVtuQ/s1600/Lie%2Bto%2Bme.jpg',
        ath: 'skt'
    },
    caps: [/*
        {url: "https://suzihaza.com/v/4l90kq11xoq",tem: 1,epi: 1,tit: "Piloto"},
        {url: "https://suzihaza.com/v/4d9j2jnnyv1",tem: 1,epi: 2,tit: "Renuncia moral"},
        {url: "https://suzihaza.com/v/7y9wq1wwx9j",tem: 1,epi: 3,tit: "Una puntuación perfecta"},
        {url: "https://suzihaza.com/v/p6ogk4j6x9j",tem: 1,epi: 4,tit: "Amor siempre"},
        {url: "https://suzihaza.com/v/8gozqn-6yod",tem: 1,epi: 5,tit: "Desencadenado"},
        {url: "https://suzihaza.com/v/6mv23l1pdor",tem: 1,epi: 6,tit: "No hace daño"},
        {url: "https://suzihaza.com/v/3qo1z5n729y",tem: 1,epi: 7,tit: "La mejor política"},
        {url: "https://suzihaza.com/v/8godrnqdpvy",tem: 1,epi: 8,tit: "Corazón depravado"},
        {url: "https://suzihaza.com/v/8xopezr5q97",tem: 1,epi: 9,tit: "La vida no tiene precio"},
        {url: "https://suzihaza.com/v/eno8rnwj091",tem: 1,epi: 10,tit: "Mejor mitad"},
        {url: "https://suzihaza.com/v/7z9-rk2g29x",tem: 1,epi: 11,tit: "El secreto"},
        {url: "https://suzihaza.com/v/7y9wqx1-x9j",tem: 1,epi: 12,tit: "Cegado"},
        {url: "https://suzihaza.com/v/4d9j2dj0yv1",tem: 1,epi: 13,tit: "Sacrificio"},
        {url: "https://suzihaza.com/v/059llrjln96",tem: 2,epi: 1,tit: "El quid de la cuestión"},
        {url: "https://suzihaza.com/v/4d9j2dw3yv1",tem: 2,epi: 2,tit: "Verdad o consecuencia"},
        {url: "https://suzihaza.com/v/7yvwqxd2xvj",tem: 2,epi: 3,tit: "Factor de control"},
        {url: "https://suzihaza.com/v/pmo57xyl8vl",tem: 2,epi: 4,tit: "Cariño"},
        {url: "https://suzihaza.com/v/p69gk4jkxvj",tem: 2,epi: 5,tit: "Lesiones corporales graves"},
        {url: "https://suzihaza.com/v/pmv57x0789l",tem: 2,epi: 6,tit: "Sin franqueza"},
        {url: "https://suzihaza.com/v/2w9mlp2elo6",tem: 2,epi: 7,tit: "Viernes negro"},
        {url: "https://suzihaza.com/v/zyvnl17m8o1",tem: 2,epi: 8,tit: "La fiesta de navidad"},
        {url: "https://suzihaza.com/v/en98rn1r0v1",tem: 2,epi: 9,tit: "Equidad"},
        {url: "https://suzihaza.com/v/yxv34eqdqol",tem: 2,epi: 10,tit: "El hombre del tractor"},
        {url: "https://suzihaza.com/v/809ep-jp7oj",tem: 2,epi: 11,tit: "Vencer al diablo"},
        {url: "https://suzihaza.com/v/p69gk4e-xvj",tem: 2,epi: 12,tit: "Dulces diesicéis"},
        {url: "https://suzihaza.com/v/7yvwqx1qxvj",tem: 2,epi: 13,tit: "Toda la verdad"},
        {url: "https://suzihaza.com/v/5jv46yrpx90",tem: 2,epi: 14,tit: "Reacción instantánea"},
        {url: "https://suzihaza.com/v/6m923l17dvr",tem: 2,epi: 15,tit: "Maestros y alumnos"},
        {url: "https://suzihaza.com/v/2womlp24lv6",tem: 2,epi: 16,tit: "Delincuente"},
        {url: "https://suzihaza.com/v/p6vgk4edxoj",tem: 2,epi: 17,tit: "Impacto y bala"},
        {url: "https://suzihaza.com/v/env8rnw60o1",tem: 2,epi: 18,tit: "Cabeza aprisionada"},
        {url: "https://suzihaza.com/v/1lo6d8myl95",tem: 2,epi: 19,tit: "El flautista"},
        {url: "https://suzihaza.com/v/6mv23l10dor",tem: 2,epi: 20,tit: "Expuesto"},
        {url: "https://suzihaza.com/v/zy9nl1768v1",tem: 2,epi: 21,tit: "Oscuridad y luz"},
        {url: "https://suzihaza.com/v/mzokl0nr19q",tem: 2,epi: 22,tit: "Blanco y negro"},
        {url: "https://suzihaza.com/v/54oyqgm8x9l",tem: 3,epi: 1,tit: "En número rojos"},
        {url: "https://suzihaza.com/v/1xvqlme2xo4",tem: 3,epi: 2,tit: "Plural mayestático"},
        {url: "https://suzihaza.com/v/1lo6d8mdl95",tem: 3,epi: 3,tit: "Lealtad ciega"},
        {url: "https://suzihaza.com/v/7y9wqxd-x9j",tem: 3,epi: 4,tit: "Investigación a ciegas"},
        {url: "https://suzihaza.com/v/mzokl0nl19q",tem: 3,epi: 5,tit: "La canción del canario"},
        {url: "https://suzihaza.com/v/7zv-rk2r2vx",tem: 3,epi: 6,tit: "Más allá de la creencia"},
        {url: "https://suzihaza.com/v/80oep-0p7vj",tem: 3,epi: 7,tit: "Veronica"},
        {url: "https://suzihaza.com/v/p6ogk4ekx9j",tem: 3,epi: 8,tit: "Asesinato a sangre fría"},
        {url: "https://suzihaza.com/v/8xvpez0kqo7",tem: 3,epi: 9,tit: "Casa de diversión"},
        {url: "https://suzihaza.com/v/dwvrl2dxpvg",tem: 3,epi: 10,tit: "Despecho"},
        {url: "https://suzihaza.com/v/yxv34eqjqol",tem: 3,epi: 11,tit: "Salvado"},
        {url: "https://suzihaza.com/v/mz9kl0n-1vq",tem: 3,epi: 12,tit: "Desaparecido"},
        {url: "https://suzihaza.com/v/8gvdrnq-p9y",tem: 3,epi: 13,tit: "Aplicación asesina"},*/
        {url: "https://uqload.com/embed-thkikwr1i0cs.html", tem: 1, epi: 1, tit: "Piloto"},
        {url: "https://uqload.com/embed-8lttev6ki9f5.html", tem: 1, epi: 2, tit: "Renuncia moral"},
        {url: "https://uqload.com/embed-ej8fq325qshr.html", tem: 1, epi: 3, tit: "Una puntuación perfecta"},
        {url: "https://uqload.com/embed-2fyg9g5gjcm9.html", tem: 1, epi: 4, tit: "Amor siempre"},
        {url: "https://uqload.com/embed-nlhrjdm6c549.html", tem: 1, epi: 5, tit: "Desencadenado"},
        {url: "https://uqload.com/embed-kq1glvehz637.html", tem: 1, epi: 6, tit: "No hace daño"},
        {url: "https://uqload.com/embed-kokoxcroyjfm.html", tem: 1, epi: 7, tit: "La mejor política"},
        {url: "https://uqload.com/embed-x6ma9hsp6hw5.html", tem: 1, epi: 8, tit: "Corazón depravado"},
        {url: "https://uqload.com/embed-ko57ity0nppa.html", tem: 1, epi: 9, tit: "La vida no tiene precio"},
        {url: "https://uqload.com/embed-5pa3hyuziilx.html", tem: 1, epi: 10, tit: "Mejor mitad"},
        {url: "https://uqload.com/embed-dwqs4ewb6527.html", tem: 1, epi: 11, tit: "Secreto"},
        {url: "https://uqload.com/embed-5qrmezm1mslo.html", tem: 1, epi: 12, tit: "Cegado"},
        {url: "https://uqload.com/embed-1h8uv3l69yqj.html", tem: 1, epi: 13, tit: "Sacrificio"},
        {url: "https://uqload.com/embed-3oc8h68bgnqb.html", tem: 2, epi: 1, tit: "El quid de la cuestión"},
        {url: "https://uqload.com/embed-cgcrsvdnxnur.html", tem: 2, epi: 2, tit: "Verdad o consecuencia"},
        {url: "https://uqload.com/embed-4t3087oii5ah.html", tem: 2, epi: 4, tit: "Cariño"},
        {url: "https://uqload.com/embed-ay644c0cdlso.html", tem: 2, epi: 5, tit: "Lesiones corporales graves"},
        {url: "https://uqload.com/embed-u9uikftvpqs1.html", tem: 2, epi: 6, tit: "Sin franqueza"},
        {url: "https://uqload.com/embed-ttzjeqzyz3r0.html", tem: 2, epi: 7, tit: "Viernes negro"},
        {url: "https://uqload.com/embed-pe1gl1n2vup0.html", tem: 2, epi: 8, tit: "La fiesta de Navidad"},
        {url: "https://uqload.com/embed-0oqe49xigyvw.html", tem: 2, epi: 9, tit: "Equidad"},
        {url: "https://uqload.com/embed-fv2i6jijawdl.html", tem: 2, epi: 10, tit: "El hombre del tractor"},
        {url: "https://uqload.com/embed-yb33k8satg22.html", tem: 2, epi: 11, tit: "Vencer al Diablo"},
        {url: "https://uqload.com/embed-gnx67s0exivd.html", tem: 2, epi: 12, tit: "Dulces dieciséis"},
        {url: "https://uqload.com/embed-6n6urto1wiwp.html", tem: 2, epi: 13, tit: "Toda la verdad"},
        {url: "https://uqload.com/embed-8ywxdnhzndbp.html", tem: 2, epi: 14, tit: "Reacción instantánea"},
        {url: "https://uqload.com/embed-q7cvdoymlmqj.html", tem: 2, epi: 15, tit: "Maestro y alumnos"},
        {url: "https://uqload.com/embed-vqmdo5x87t74.html", tem: 2, epi: 16, tit: "Delincuente"},
        {url: "https://uqload.com/embed-9hg68soh5cg6.html", tem: 2, epi: 17, tit: "Impacto de bala"},
        {url: "https://uqload.com/embed-kuaq4e1tcyji.html", tem: 2, epi: 18, tit: "Cabeza aprisionada"},
        {url: "https://uqload.com/embed-tmr6pdbfwf6y.html", tem: 2, epi: 19, tit: "El flautista"},
        {url: "https://uqload.com/embed-rxy6fpr5s41e.html", tem: 2, epi: 20, tit: "Expuesto"},
        {url: "https://uqload.com/embed-c0g61jltc0pq.html", tem: 2, epi: 21, tit: "Oscuridad y luz"},
        {url: "https://uqload.com/embed-ylwu1noerfy2.html", tem: 2, epi: 22, tit: "Blanco y negro"},
        {url: "https://uqload.com/embed-imxsu94ouviz.html", tem: 3, epi: 2, tit: "Plural mayestático"},
        {url: "https://uqload.com/embed-uul6v0ecmk94.html", tem: 3, epi: 3, tit: "Lealtad ciega"},
        {url: "https://uqload.com/embed-eeta9wrt8glg.html", tem: 3, epi: 4, tit: "Investigación a ciegas"},
        {url: "https://uqload.com/embed-jh04caossbbw.html", tem: 3, epi: 5, tit: "La canción del canario"},
        {url: "https://uqload.com/embed-vtodi3xkam6k.html", tem: 3, epi: 6, tit: "Más allá de la creencia"},
        {url: "https://uqload.com/embed-m23kxbuks4ek.html", tem: 3, epi: 8, tit: "Asesinato a sangre fría"},
        {url: "https://uqload.com/embed-sozyu0qjr8yz.html", tem: 3, epi: 9, tit: "Casa de diversión"},
        {url: "https://uqload.com/embed-4v0qz7ttlcoo.html", tem: 3, epi: 11, tit: "Salvado"},
        {url: "https://uqload.com/embed-gtr0loi4fi4a.html", tem: 3, epi: 12, tit: "Desaparecido"},
        {url: "https://uqload.com/embed-aix1kerb6l6k.html", tem: 3, epi: 13, tit: "Aplicación asesina"},
    ],
}