const __apps__ = [
    {name: 'Links', fav: 'links', url: '@links', sec: false},
    {name: 'Main', fav: 'main', url: '@off', sec: false},
    {name: 'My App', fav: 'task', url: '@off/note', sec: true},
    {name: 'Extensions', fav: 'chrome', url: '@off/save/extensions', sec: false},
    {name: 'Bookmarks', fav: 'marks', url: '@links/bookmaps', sec: true},
    {name: 'Firenote', fav: 'firenote', url: '@off/firenote', sec: true},
    {name: 'bloc', fav: 'note', url: '@off/note/bloc.html', sec: false},
    {name: 'Notas', fav: 'note', url: '@off/note/notas.html', sec: false},
    {name: 'Notepad', fav: 'note', url: '@off/pad.html', sec: false},
    {name: 'FontView', fav: 'words', url: '@off/fontview', sec: false},
    {name: 'Words', fav: 'words', url: '@off/save/words', sec: false},
    {name: 'Markdown viewer', fav: 'note', url: '@off/md', sec: false},
    {name: 'Monaco', fav: 'monaco', url: '@off/code', sec: false},
    {name: 'Mono', fav: 'mono', url: '@off/note/mono.html', sec: false},
    {name: 'CARI', fav: 'cari', url: '@off/cari', sec: true},
    {name: 'Bookmarlets', fav: 'commands', url: '@off/save', sec: false},
    {name: 'Regex tool', fav: 'write', url: '@off/rgx', sec: false},
    {name: 'String edit', fav: 'write', url: '@off/save/strings', sec: false},
    {name: 'Tree marks', fav: 'json', url: '@links/tree', sec: true},
    {name: 'YouTube', fav: 'youtube', url: '@links/youtu-be.html', sec: true},
    {name: 'YTPL Viewer', fav: 'youtube', url: '@links/social/ytpl-view/', sec: false},
    {name: 'Music', fav: 'music', url: '@links/music', sec: true},
    {name: 'CodeMarks', fav: 'codepen', url: '@links/codepen.html', sec: false},
    {name: 'ClPH€R', fav: 'hash', url: '@off/save/hash', sec: false},
    {name: 'History', fav: 'key', url: '@off/save/pa55', sec: false},
    {name: 'JSON', fav: 'json', url: '@off/save/json', sec: false},
    {name: 'Open urls', fav: 'open', url: '@off/save/href', sec: false},
    {name: 'Url scan', fav: 'scan', url: '@off/save/url', sec: false},
    {name: 'Web2', fav: 'scan', url: '@off/save/web2', sec: false},
    {name: 'Speedtest', fav: 'speed', url: '@off/speedtest', sec: false},
    {name: 'Diff files', fav: 'diff', url: '@off/filesdiff', sec: false},
    {name: 'Multi viewer', fav: 'files', url: '@off/view', sec: false},
    {name: 'Movie search', fav: 'movie', url: '@off/movie', sec: false},
    {name: 'Share screen', fav: 'screen', url: '@off/screen', sec: false},
    {name: 'View img', fav: 'images', url: '@off/vimg', sec: false},
    {name: 'Read Text', fav: 'read', url: '@off/tasks/voice', sec: false},
    {name: 'Old read', fav: 'speech', url: '@off/tasks/voice/old_read.html', sec: false},
    {name: 'Reference', fav: 'reference', url: '@off/tasks', sec: false},
    {name: 'video view', fav: 'player', url: '@off/mp4', sec: false},
    {name: 'Wait room', fav: 'wait-room', url: '@off/mp4/wait.html', sec: false},
    {name: 'Awake', fav: 'moon', url: '@off/awake', sec: false},
    {name: 'Tech Apps', fav: 'tech', url: '@links/tech', sec: false},
    {name: 'Nihan', fav: 'nihan', url: 'https://espinozamnj.github.io/nihan/', sec: false},
]