const sss = [
{"name":"YouTube::app","url":"https://www.youtube.com/","path":"/lib/Social/Video"},
{"name":"Vimeo","url":"https://vimeo.com/es/","path":"/lib/Social/Video"},
{"name":"Movistar Play","url":"https://www.movistarplay.com.pe/","path":"/lib/Social/Video"},
{"name":"Netflix","url":"https://netflix.com/pe/","path":"/lib/Social/Video"},
{"name":"Clarovideo","url":"https://www.clarovideo.com/peru/homeuser","path":"/lib/Social/Video"},
{"name":"PhotoCall","url":"https://photocall.tv/","path":"/lib/Social/Video"},
{"name":"TVIP | TDT Channels","url":"https://tdtchannels.com/listas","path":"/lib/Social/Video"},
{"name":"Veed","url":"https://www.veed.io/","path":"/lib/Social/Video"},
{"name":"@Songs::main","url":"https://music.youtube.com/channel/UCSFMRGTyAcCHgE2Fp0xsD_A/playlists","path":"/lib/Social/Music"},
{"name":"lofi.cafe","url":"https://lofi.cafe/","path":"/lib/Social/Music"},
{"name":"Chillhop Music","url":"https://chillhop.com/","path":"/lib/Social/Music"},
{"name":"Spotify Web::app","url":"https://open.spotify.com/","path":"/lib/Social/Music"},
{"name":"Youtube Music::app","url":"https://music.youtube.com/","path":"/lib/Social/Music"},
{"name":"Soundiiz","url":"https://soundiiz.com/","path":"/lib/Social/Music"},
{"name":"MiMp3 Club","url":"https://w31.mimp3.club/","path":"/lib/Social/Music"},
{"name":"Lastfm","url":"https://www.last.fm/","path":"/lib/Social/Music"},
{"name":"Tune my music","url":"https://www.tunemymusic.com/es/Deezer-to-File.php#step3","path":"/lib/Social/Music"},
{"name":"Musify","url":"https://musify.club/","path":"/lib/Social/Music"},
{"name":"Codepen","url":"https://codepen.io/","path":"/lib/Social/Dev"},
{"name":"npmjs","url":"https://www.npmjs.com/","path":"/lib/Social/Dev"},
{"name":"Github","url":"https://github.com/","path":"/lib/Social/Dev"},
{"name":"Stackoverflow","url":"https://stackoverflow.com/","path":"/lib/Social/Dev"},
{"name":"HTML Save","url":"https://htmlsave.com/","path":"/lib/Social/Dev"},
{"name":"Daily dev","url":"https://app.daily.dev/","path":"/lib/Social/Dev"},
{"name":"Netlify","url":"https://www.netlify.com/","path":"/lib/Social/Dev"},
{"name":"cmd.to","url":"https://cmd.to/","path":"/lib/Social/Dev"},
{"name":"W3schools","url":"https://www.w3schools.com/","path":"/lib/Social/Dev"},
{"name":"DEV Community","url":"https://dev.to/","path":"/lib/Social/Dev"},
{"name":"Git","url":"https://git-scm.com/","path":"/lib/Social/Dev"},
{"name":"OpenAI","url":"https://platform.openai.com/","path":"/lib/Social/Dev"},
{"name":"Hacker Noon","url":"https://hackernoon.com/","path":"/lib/Social/Dev/hacker"},
{"name":"root me","url":"https://www.root-me.org/?lang=es","path":"/lib/Social/Dev/hacker"},
{"name":"Facebook","url":"https://www.facebook.com/","path":"/lib/Social/People"},
{"name":"Discord::app","url":"https://discord.com/","path":"/lib/Social/People"},
{"name":"Twitter","url":"https://twitter.com/","path":"/lib/Social/People"},
{"name":"LinkedIn","url":"https://www.linkedin.com/","path":"/lib/Social/People"},
{"name":"Telegram Web K","url":"https://web.telegram.org/k","path":"/lib/Social/People"},
{"name":"WhatsApp Web::main,app","url":"https://web.whatsapp.com/","path":"/lib/Social/People"},
{"name":"Slack","url":"https://slack.com/","path":"/lib/Social/People"},
{"name":"wk3.org","url":"https://wk3.org/","path":"/lib/Social/People"},
{"name":"iviv","url":"https://iviv.hu/","path":"/lib/Social/People"},
{"name":"MEGA","url":"https://mega.io/","path":"/lib/Social/Drive"},
{"name":"TeraBox","url":"https://www.terabox.com/","path":"/lib/Social/Drive"},
{"name":"Yandex.Disk","url":"https://disk.yandex.com/","path":"/lib/Social/Drive"},
{"name":"OneDrive Live","url":"https://onedrive.live.com/","path":"/lib/Social/Drive"},
{"name":"Bitrix::main","url":"https://locked.bitrix24.es/","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Notion::main,app","url":"https://notion.so/","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Bitdefender","url":"https://www.bitdefender.com/solutions/digital-identity-protection.html","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Trello::app","url":"https://trello.com/","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Bitwarden","url":"https://vault.bitwarden.com/#/","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Microsoft Live","url":"https://live.com/","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Wickr","url":"https://wickr.com/","path":"/lib/Social/Data/BOSS/advanc"},
{"name":"Telegram Developers","url":"https://tg.dev/","path":"/lib/Social/Data/BOSS"},
{"name":"Mail","url":"https://www.mail.com/","path":"/lib/Social/Data/BOSS"},
{"name":"Facebook Data","url":"https://www.facebook.com/your_information","path":"/lib/Social/Data/BOSS"},
{"name":"Firefox","url":"https://www.mozilla.org/es-ES/firefox/new/","path":"/lib/Social/Data/BOSS"},
{"name":"Evernote","url":"https://evernote.com/intl/es-latam/","path":"/lib/Social/Data/BOSS"},
{"name":"Toby::main","url":"https://web.gettoby.com/","path":"/lib/Social/Data/BOSS"},
{"name":"Google Account","url":"https://google.com/","path":"/lib/Social/Data/GOG"},
{"name":"Google Play","url":"https://play.google.com/store?hl=es-419","path":"/lib/Social/Data/GOG"},
{"name":"Messages Web","url":"https://messages.google.com/web/authentication?pli=1","path":"/lib/Social/Data/GOG"},
{"name":"Gmail::app","url":"https://mail.google.com/mail/u/0/#inbox","path":"/lib/Social/Data/GOG"},
{"name":"TasksBoard","url":"https://tasksboard.com/app","path":"/lib/Social/Data/GOG"},
{"name":"Google Meet::app","url":"https://meet.google.com/","path":"/lib/Social/Data/GOG"},
{"name":"Google Drive::main,app","url":"https://drive.google.com/drive/my-drive","path":"/lib/Social/Data/GOG"},
{"name":"Archivo de álbumes","url":"https://get.google.com/albumarchive/","path":"/lib/Social/Data/GOG"},
{"name":"Coleciones","url":"https://www.google.com/save","path":"/lib/Social/Data/GOG"},
{"name":"Contactos de Google::app","url":"https://contacts.google.com/","path":"/lib/Social/Data/GOG"},
{"name":"Google Calendario::app","url":"https://calendar.google.com/calendar/u/0/r?pli=1","path":"/lib/Social/Data/GOG"},
{"name":"Documentos de Google::app","url":"https://docs.google.com/","path":"/lib/Social/Data/GOG"},
{"name":"Formularios de Google","url":"https://docs.google.com/forms/u/0/","path":"/lib/Social/Data/GOG"},
{"name":"Google Keep","url":"https://keep.google.com/u/0/","path":"/lib/Social/Data/GOG"},
{"name":"Google Apps","url":"https://myaccount.google.com/permissions","path":"/lib/Social/Data/GOG"},
{"name":"Youtube Studio","url":"https://studio.youtube.com/","path":"/lib/Social/Data/GOG"},
{"name":"Inftab::main","url":"https://inftab.com/","path":"/lib/Social/Data/N0TE"},
{"name":"Instapaper::app","url":"https://www.instapaper.com/u","path":"/lib/Social/Data/N0TE"},
{"name":"NotesNook","url":"https://notesnook.com/","path":"/lib/Social/Data/N0TE"},
{"name":"Raindrop.io::app","url":"https://app.raindrop.io/","path":"/lib/Social/Data/N0TE"},
{"name":"Saved.io::app","url":"https://saved.io/","path":"/lib/Social/Data/N0TE"},
{"name":"@J.EM::main,locked","url":"https://notion.so/2777f2aea0a04f2fb1ccb701fafaa1bc","path":"/lib/Social/Data/N0TE"},
{"name":"@Wiki::main,locked","url":"https://pandadnap.notion.site/9edd4b82a05a440f893683ed4a9fdd31","path":"/lib/Social/Data/N0TE"},
{"name":"@Notes::main,locked","url":"https://pandadnap.notion.site/aa01c1d3b9c14757ba8cf29791aa37c9","path":"/lib/Social/Data/N0TE"},
{"name":"@LKS::main,locked","url":"https://pandadnap.notion.site/311b51ee88e543ada18235ecafce2d04","path":"/lib/Social/Data/N0TE"},
{"name":"Justpaste::app","url":"https://justpaste.it/","path":"/lib/Social/Data/N0TE"},
{"name":"Simplenote::app","url":"https://app.simplenote.com/","path":"/lib/Social/Data/N0TE"},
{"name":"Just Paste Me","url":"https://justpaste.me/","path":"/lib/Social/Data/N0TE"},
{"name":"I Just Paste","url":"https://img.justpaste.me/","path":"/lib/Social/Data/N0TE"},
{"name":"Coursera","url":"https://coursera.org/","path":"/lib/Social/Courses"},
{"name":"Crehana","url":"https://crehana.com/","path":"/lib/Social/Courses"},
{"name":"Garage Digital","url":"https://learndigital.withgoogle.com/activate/courses","path":"/lib/Social/Courses"},
{"name":"Edmodo","url":"https://new.edmodo.com/","path":"/lib/Social/Courses"},
{"name":"Goconqr","url":"https://goconqr.com/","path":"/lib/Social/Courses"},
{"name":"Aprende.org","url":"https://aprende.org/","path":"/lib/Social/Courses"},
{"name":"IBM SkillsBuild","url":"https://students.yourlearning.ibm.com/","path":"/lib/Social/Courses"},
{"name":"Capacítate para el empleo","url":"https://capacitateparaelempleo.org/","path":"/lib/Social/Courses"},
{"name":"Codecademy","url":"https://www.codecademy.com/","path":"/lib/Social/Courses"},
{"name":"youthSpark","url":"https://youth-spark.org/","path":"/lib/Social/Courses"},
{"name":"GCFGlobal","url":"https://edu.gcfglobal.org/es/","path":"/lib/Social/Courses"},
{"name":"Duolingo","url":"https://www.duolingo.com/learn","path":"/lib/Social/Courses"},
{"name":"Aprender Gratis","url":"https://aprendergratis.es/","path":"/lib/Social/Courses"},
{"name":"Píldoras Informáticas","url":"https://www.pildorasinformaticas.es/","path":"/lib/Social/Courses"},
{"name":"Fundación Carolina","url":"https://www.fundacioncarolina.es/","path":"/lib/Social/Courses"},
{"name":"Domestika","url":"https://www.domestika.org/","path":"/lib/Social/Courses"},
{"name":"Platzi","url":"https://platzi.com/home","path":"/lib/Social/Courses"},
{"name":"Edutin","url":"https://app.edutin.com/","path":"/lib/Social/Courses"},
{"name":"Jóvenes Nestle","url":"https://jovenesnestle.pe/","path":"/lib/Social/Courses"},
{"name":"Hackrocks","url":"https://hackrocks.com/","path":"/lib/Social/Courses"},
{"name":"Exercism","url":"https://exercism.org/","path":"/lib/Social/Courses"},
{"name":"Udemy::app","url":"https://udemy.com/","path":"/lib/Social/Courses"},
{"name":"Cisco","url":"https://www.netacad.com/","path":"/lib/Social/Courses"},
{"name":"Ed Team","url":"https://ed.team/","path":"/lib/Social/Courses"},
{"name":"INMAGINE","url":"https://accounts.inmagine.com/","path":"/lib/Social/Design"},
{"name":"Adobe","url":"https://adobe.com/","path":"/lib/Social/Design"},
{"name":"Techsmith","url":"https://techsmith.com/","path":"/lib/Social/Design"},
{"name":"SUE Recibo de agua por periodo","url":"https://www.epsel.com.pe/sue/SicdesaRpd","path":"/lib/Social/Pay"},
{"name":"Aliexpress","url":"https://aliexpress.com/","path":"/lib/Social/Pay"},
{"name":"Distriluz","url":"https://www.distriluz.com.pe/","path":"/lib/Social/Pay"},
{"name":"Eventbrite","url":"https://eventbrite.com.pe/","path":"/lib/Social/Pay"},
{"name":"Firebase admin","url":"https://console.firebase.google.com/u/0/","path":"/lib/Social/Host"},
{"name":"000Webhost","url":"https://000webhost.com/","path":"/lib/Social/Host"},
{"name":"Infiniuty FreeEpizy","url":"https://infinityfree.net/","path":"/lib/Social/Host"},
{"name":"000webhost File Manager","url":"https://files.000webhost.com/","path":"/lib/Social/Host"},
{"name":"Filemanager","url":"http://filemanager.ai/new/","path":"/lib/Social/Host"},
{"name":"Wordpress","url":"https://www.wordpress.com/","path":"/lib/Social/Host"},
{"name":"Site Ground","url":"https://es.siteground.com/hosting-web.htm","path":"/lib/Social/Host"},
{"name":"Name Cheap","url":"https://www.namecheap.com/hosting/shared/","path":"/lib/Social/Host"},
{"name":"Beget","url":"https://beget.com/en","path":"/lib/Social/Host"},
{"name":"HostGator","url":"https://www.hostgator.com/","path":"/lib/Social/Host"},
{"name":"Pinterest::app","url":"https://www.pinterest.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"Aki Frases","url":"https://akifrases.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"Ted","url":"https://www.ted.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"Pixabay","url":"https://www.pixabay.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"Instagram::app","url":"https://www.instagram.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"Memedroid","url":"https://es.memedroid.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"TikTok::app","url":"https://www.tiktok.com/","path":"/lib/Social/Image, meme, phrases"},
{"name":"AirDroid host","url":"http://192.168.2.8:8888/","path":"/lib/Social/Var"},
{"name":"AirDroid Web","url":"https://www.airdroid.com/es-es/","path":"/lib/Social/Var"},
{"name":"Homestyler","url":"https://homestyler.com/","path":"/lib/Social/Var"},
{"name":"Sonolibro","url":"https://sonolibro.com/","path":"/lib/Social/Var"},
{"name":"Campus USAT::main","url":"http://intranet.usat.edu.pe/campusestudiante/Default.aspx","path":"/lib/Estudios/USAT"},
{"name":"MS Teams","url":"https://teams.microsoft.com/","path":"/lib/Estudios/MSM"},
{"name":"Delve","url":"https://nam.delve.office.com/","path":"/lib/Estudios/MSM"},
{"name":"Correo Outlook::app","url":"https://outlook.office.com/mail/inbox","path":"/lib/Estudios/MSM"},
{"name":"Contactos Outlook","url":"https://outlook.office.com/people/","path":"/lib/Estudios/MSM"},
{"name":"Calendario Outlook","url":"https://outlook.office.com/calendar/view/week","path":"/lib/Estudios/MSM"},
{"name":"Microsoft 365::main,app","url":"https://www.office.com/","path":"/lib/Estudios/MSM"},
{"name":"page_blank","url":"data:text/html, <html contenteditable><Title>Notas</Title><style>*{font-family:monospace;font-size:1.2rem}</style>","path":"/lib/Apps/Write Editor"},
{"name": "Bard::app","url":"https://bard.google.com/","path":"/lib/Apps/Write Editor"},
{"name": "ChatGPT::app","url":"https://chat.openai.com/","path":"/lib/Apps/Write Editor"},
{"name":"Online Notepad","url":"https://onlinenotepad.org/notepad","path":"/lib/Apps/Write Editor"},
{"name":"Notes Online","url":"https://anotepad.com/","path":"/lib/Apps/Write Editor"},
{"name":"ZenPen","url":"https://zenpen.io/","path":"/lib/Apps/Write Editor"},
{"name":"Editor de Hemingway","url":"https://hemingwayapp.com/","path":"/lib/Apps/Write Editor"},
{"name":"Edit Pad","url":"https://www.editpad.org/","path":"/lib/Apps/Write Editor"},
{"name":"Pastebin","url":"https://pastebin.com/","path":"/lib/Apps/Write Editor"},
{"name":"Privnote | notas autodesechables","url":"https://privnote.com/","path":"/lib/Apps/Write Editor"},
{"name":"Editor.md","url":"https://pandao.github.io/editor.md/en.html","path":"/lib/Apps/Write Editor"},
{"name":"Overleaf","url":"https://www.overleaf.com/","path":"/lib/Apps/Write Editor"},
{"name":"UpMath.me | Markdown editor","url":"https://upmath.me/","path":"/lib/Apps/Write Editor"},
{"name":"Latex Convert","url":"https://www.tuhh.de/MathJax/test/sample-dynamic-2.html","path":"/lib/Apps/Write Editor"},
{"name":"Base Latex Editor","url":"https://latexbase.com/","path":"/lib/Apps/Write Editor"},
{"name":"Dillinger","url":"https://dillinger.io/","path":"/lib/Apps/Write Editor"},
{"name":"Codecogs Latex Generate","url":"https://www.codecogs.com/latex/eqneditor.php?lang=es-es","path":"/lib/Apps/Write Editor"},
{"name":"Latex equation","url":"https://latexeditor.lagrida.com/","path":"/lib/Apps/Write Editor"},
{"name":"StackEdit","url":"https://stackedit.io/app#","path":"/lib/Apps/Write Editor"},
{"name":"Talk to Transformer | InferKit","url":"https://app.inferkit.com/demo","path":"/lib/Apps/Student Tools/GPT"},
{"name":"Text Synth","url":"https://bellard.org/textsynth/","path":"/lib/Apps/Student Tools/GPT"},
{"name":"Write With Transformer","url":"https://transformer.huggingface.co/doc/gpt2-large","path":"/lib/Apps/Student Tools/GPT"},
{"name":"Business Name Generator","url":"https://namelix.com/","path":"/lib/Apps/Student Tools/GPT"},
{"name":"All about GPT3","url":"https://gpt3.website/","path":"/lib/Apps/Student Tools/GPT"},
{"name":"GPT3 Demos","url":"https://gpt3demo.com/","path":"/lib/Apps/Student Tools/GPT"},
{"name":"Estilector | Mejora la redacción","url":"http://www.estilector.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Conclusion Generator","url":"https://edubirdie.com/conclusion-generator","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Reescribe texto","url":"https://smodin.me/es/Reproduzca-autom%C3%A1ticamente-texto-en-espa%C3%B1ol-gratis","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Parafrasist | RESUMIDOR DE TEXTOS","url":"https://parafrasist.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Smmry | Resumir textos o páginas web","url":"https://smmry.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Paraphrasing tool | Prepostseo","url":"https://www.prepostseo.com/paraphrasing-tool","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Article rewriter | Prepostseo","url":"https://www.prepostseo.com/article-rewriter","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"rytr.me | best AI writing","url":"https://rytr.me/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"EssayTyper","url":"https://www.essaytyper.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Analizador sintáctico de oraciones","url":"https://sintaxis.org/analizador/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Estilector | Mejorar redacción de textos","url":"http://www.estilector.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Teleprompter | Leer texto","url":"https://es.teleprompter-online.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Lorca Editor | Escribe mejor","url":"http://lorcaeditor.com/","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"Article Spinner","url":"https://www.danielpinero.com/article-spinner-espanol","path":"/lib/Apps/Student Tools/rewrite"},
{"name":"ISBN | Biblioteca Nacional del Perú | BNP","url":"https://www.bnp.gob.pe/servicios/isbn/","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"Alicia","url":"https://alicia.concytec.gob.pe/","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"LA Referencia","url":"https://www.lareferencia.info/es/","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"AbeBooks","url":"https://www.abebooks.com/","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"DOI | Digital Object Identifier System","url":"https://www.doi.org/","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"Cybertesis","url":"https://cybertesis.unmsm.edu.pe/","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"International ISBN Agency","url":"https://www.isbn-international.org/es/content/agencia-internacional-del-isbn","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"IberLibro ISBN","url":"https://www.iberlibro.com/libros/Busqueda-numero-ISBN-10-13.shtml","path":"/lib/Apps/Student Tools/Research/View books"},
{"name":"IEEE Xplore","url":"https://ieeexplore.ieee.org/Xplore/home.jsp","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Sci Hub","url":"http://sci-hub.tw/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Google Académico","url":"https://scholar.google.com.pe/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Wiki books","url":"https://es.wikibooks.org/wiki/Portada","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Scopus preview","url":"https://www.scopus.com/home.uri","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"ScienceDirect","url":"https://www.sciencedirect.com/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"RENATI | Trabajos de Investigación","url":"http://renati.sunedu.gob.pe/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Repositorio Ecuador","url":"https://repositorio.usfq.edu.ec/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Scholarpedia","url":"http://www.scholarpedia.org/article/Main_Page","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Academia.edu","url":"https://www.academia.edu/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Docsity","url":"https://www.docsity.com/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Document Sharing Free Instantly","url":"https://dlscrib.com/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"JSTOR Home","url":"https://www.jstor.org/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"PLOS ONE","url":"https://journals.plos.org/plosone/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"TandFonline","url":"https://www.tandfonline.com/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"ResearchGate","url":"https://www.researchgate.net/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Online docs translator","url":"https://www.onlinedoctranslator.com/es/","path":"/lib/Apps/Student Tools/Research/Investigate"},
{"name":"Red de Revistas Científicas | Redalyc","url":"https://www.redalyc.org/","path":"/lib/Apps/Student Tools/Investigate"},
{"name":"Zotero","url":"https://www.zotero.org/","path":"/lib/Apps/Student Tools/Research/Cite"},
{"name":"Cite a Webpage | Scribbr Citation Generator","url":"https://www.scribbr.com/apa-citation-generator/","path":"/lib/Apps/Student Tools/Research/Cite"},
{"name":"Citation Machine","url":"https://www.citationmachine.net/apa","path":"/lib/Apps/Student Tools/Research/Cite"},
{"name":"MyBib","url":"https://www.mybib.com/#/","path":"/lib/Apps/Student Tools/Research/Cite"},
{"name":"Letras chidas","url":"http://fsymbols.com/es/letras/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Font Generator","url":"https://tell.wtf/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Adornos para tu Nick","url":"http://www.mundoxat.com/nicks/letrasycaracteresxat.html","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"CopyPasteCharacter.com","url":"http://www.copypastecharacter.com/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Generador de Letras para Nick","url":"http://conversorletras.com/letras-nick/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Font Generator","url":"https://fontgenerator.dev/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"TypeIt","url":"http://www.typeit.org/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Símbolo","url":"http://es.piliapp.com/symbol/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Alfabeto griego","url":"https://es.piliapp.com/symbol/greek/","path":"/lib/Apps/Student Tools/Caracters"},
{"name":"Free Plagiarism Checker | Plagly","url":"https://plagly.com/","path":"/lib/Apps/Student Tools/plagio"},
{"name":"DupliChecker","url":"https://www.duplichecker.com/es","path":"/lib/Apps/Student Tools/plagio"},
{"name":"PlagiarismDetector","url":"https://plagiarismdetector.net/es","path":"/lib/Apps/Student Tools/plagio"},
{"name":"Unicheck","url":"https://unicheck.com/es-es/free-plagiarism-checker-online","path":"/lib/Apps/Student Tools/plagio"},
{"name":"Zwibbler","url":"https://zwibbler.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"AutoDraw","url":"https://www.autodraw.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"My online blackboard","url":"https://myonlineblackboard.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"Canvas Chrome::app","url":"https://canvas.apps.chrome/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"Sketchpad::app","url":"https://sketch.io/sketchpad/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"Aggie.io","url":"https://aggie.io/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"Kleki | Paint Tool","url":"https://kleki.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"Whiteboard Miro","url":"https://webwhiteboard.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"Witeboard","url":"https://witeboard.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"NoteBookCast","url":"https://www.notebookcast.com/","path":"/lib/Apps/Student Tools/Whiteboard"},
{"name":"drawio","url":"https://app.diagrams.net/","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Creately","url":"https://creately.com/login/","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Whimsical","url":"https://whimsical.com/library-JzUCzVfu2BGN7uA4fcSvaY","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Beautiful.ai","url":"https://www.beautiful.ai/","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Genial.ly","url":"https://app.genial.ly/create","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Padlet","url":"https://padlet.com/dashboard","path":"/lib/Apps/Student Tools/presentation"},
{"name":"LucidChartApp","url":"https://lucid.app/documents#/dashboard","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Quizizz","url":"https://quizizz.com/","path":"/lib/Apps/Student Tools/presentation"},
{"name":"Pixton Comic","url":"https://www.pixton.com/","path":"/lib/Apps/Student Tools/presentation"},
{"name":"ALT Codes | Alt Codes for Maths","url":"https://usefulshortcuts.com/alt-codes/maths-alt-codes.php","path":"/lib/Apps/Student Tools/math"},
{"name":"Calcular Porcentaje","url":"http://www.calcularporcentaje.net/","path":"/lib/Apps/Student Tools/math"},
{"name":"OmniCalculator","url":"https://www.omnicalculator.com/","path":"/lib/Apps/Student Tools/math"},
{"name":"Microsoft Math Solver","url":"http://math.microsoft.com/es","path":"/lib/Apps/Student Tools/math"},
{"name":"WolframAlpha","url":"https://www.wolframalpha.com/","path":"/lib/Apps/Student Tools/math"},
{"name":"Symbolab","url":"https://es.symbolab.com/","path":"/lib/Apps/Student Tools/math"},
{"name":"FxSolver","url":"https://www.fxsolver.com/","path":"/lib/Apps/Student Tools/math"},
{"name":"CyMath","url":"https://www.cymath.com/sp/","path":"/lib/Apps/Student Tools/math"},
{"name":"QuickMath","url":"https://quickmath.com/","path":"/lib/Apps/Student Tools/math"},
{"name":"MathWay","url":"https://www.mathway.com/Algebra","path":"/lib/Apps/Student Tools/math"},
{"name":"Office Viewer Doc Word Lector","url":"https://word.online-reader.com/es/","path":"/lib/Apps/office tools/office app"},
{"name":"RedCoolMedia","url":"https://www.redcoolmedia.net/","path":"/lib/Apps/office tools/office app"},
{"name":"Tiny Wow","url":"https://tinywow.com/","path":"/lib/Apps/office tools/office app"},
{"name":"Docspal","url":"https://www.docspal.com/es/visor","path":"/lib/Apps/office tools/office app"},
{"name":"Fviewer","url":"https://www.fviewer.com/sp/view-office","path":"/lib/Apps/office tools/office app"},
{"name":"Aspose","url":"https://products.aspose.app/words/viewer","path":"/lib/Apps/office tools/office app"},
{"name":"OnlineDocumentViewer","url":"https://onlinedocumentviewer.com/Viewer/document.aspx","path":"/lib/Apps/office tools/office app"},
{"name":"Photo viewer and editor","url":"https://fengyuanchen.github.io/photo-editor/","path":"/lib/Apps/office tools/office app"},
{"name":"Web to PDF Converter","url":"https://www.web2pdfconvert.com/","path":"/lib/Apps/office tools/web office"},
{"name":"PrintWhatYouLike","url":"https://www.printwhatyoulike.com/","path":"/lib/Apps/office tools/web office"},
{"name":"OffiDocs","url":"https://www.offidocs.com/","path":"/lib/Apps/office tools/web office"},
{"name":"123apps","url":"https://123apps.com/es/","path":"/lib/Apps/office tools/web office"},
{"name":"Similarsites","url":"https://www.similarsites.com/","path":"/lib/Apps/office tools/comparative"},
{"name":"Alternative to","url":"https://alternativeto.net/","path":"/lib/Apps/office tools/comparative"},
{"name":"Alternative.me","url":"https://alternative.me/","path":"/lib/Apps/office tools/comparative"},
{"name":"Capterra","url":"https://www.capterra.pe/","path":"/lib/Apps/office tools/comparative"},
{"name":"Grabación webcam | Probar cámara","url":"https://es.webcamtests.com/recorder","path":"/lib/Apps/office tools/testing"},
{"name":"Prueba de micrófono","url":"https://es.mictests.com/","path":"/lib/Apps/office tools/testing"},
{"name":"Probar cámara","url":"https://es.webcamtests.com/","path":"/lib/Apps/office tools/testing"},
{"name":"MotionMark","url":"https://browserbench.org/MotionMark/","path":"/lib/Apps/office tools/testing"},
{"name":"Basemark","url":"https://web.basemark.com/","path":"/lib/Apps/office tools/testing"},
{"name":"HTML5 Test","url":"https://html5test.com/","path":"/lib/Apps/office tools/testing"},
{"name":"SpeedTest | Host Tools","url":"http://es.host-tools.com/test-velocidad-internet","path":"/lib/Apps/office tools/testing/speedtest"},
{"name":"Fast.com","url":"https://fast.com/es/","path":"/lib/Apps/office tools/testing/speedtest"},
{"name":"Speedtest by Ookla","url":"http://www.speedtest.net/","path":"/lib/Apps/office tools/testing/speedtest"},
{"name":"Speed Test","url":"https://openspeedtest.com/Get-widget.php","path":"/lib/Apps/office tools/testing/speedtest"},
{"name":"Internet Speed Test","url":"https://whatismyipaddress.com/speed-test","path":"/lib/Apps/office tools/testing/speedtest"},
{"name":"devhints | cheatsheets","url":"https://devhints.io/","path":"/lib/Apps/office tools/shorcuts"},
{"name":"UseTheKeyboard","url":"https://usethekeyboard.com/","path":"/lib/Apps/office tools/shorcuts"},
{"name":"KeyCombiner","url":"https://keycombiner.com/","path":"/lib/Apps/office tools/shorcuts"},
{"name":"Corrupt a file online","url":"https://pinetools.com/corrupt-a-file","path":"/lib/Apps/office tools/web software"},
{"name":"Bulk Resize Photos","url":"https://bulkresizephotos.com/en","path":"/lib/Apps/office tools/web software"},
{"name":"Image Resizer","url":"https://imageresizer.io/demo","path":"/lib/Apps/office tools/web software"},
{"name":"Windows 10","url":"https://dustinbrett.com/","path":"/lib/Apps/office tools/web software"},
{"name":"Emupedia Apps","url":"https://emupedia.net/beta/","path":"/lib/Apps/office tools/web software"},
{"name":"Monaco Editor v0.27.0","url":"https://emupedia.net/emupedia-app-monaco-editor/","path":"/lib/Apps/office tools/web software"},
{"name":"Method Draw | SVG editor","url":"https://emupedia.net/emupedia-app-svg-editor/","path":"/lib/Apps/office tools/web software"},
{"name":"Emupedia notepad","url":"https://emupedia.net/emupedia-app-notepad/","path":"/lib/Apps/office tools/web software"},
{"name":"Toolify","url":"https://www.toolify.ai/","path":"/lib/Apps/office tools/web software"},
{"name":"EmuOs Windows","url":"https://emupedia.net/beta/emuos/","path":"/lib/Apps/office tools/web software"},
{"name":"VS Code Web Dev","url":"https://emupedia.net/emupedia-app-vscode/","path":"/lib/Apps/office tools/web software"},
{"name":"Anonymizer | Generate photos to protect your identity","url":"https://generated.photos/anonymizer","path":"/lib/Apps/office tools/web software"},
{"name":"QrCode Monkey","url":"https://www.qrcode-monkey.com/","path":"/lib/Apps/office tools/generar"},
{"name":"QR GENERATOR","url":"https://www.the-qrcode-generator.com/","path":"/lib/Apps/office tools/generar"},
{"name":"QR scan","url":"https://sheeptester.github.io/javascripts/qr.html","path":"/lib/Apps/office tools/generar"},
{"name":"Slidesgo","url":"https://slidesgo.com/","path":"/lib/Apps/office tools/templates"},
{"name":"edit.org","url":"https://edit.org/","path":"/lib/Apps/office tools/templates"},
{"name":"cvapp","url":"https://cvapp.es/","path":"/lib/Apps/office tools/templates"},
{"name":"Plantillas De Curriculum","url":"https://plantillas-curriculum.com/","path":"/lib/Apps/office tools/templates"},
{"name":"Curriculum Vitae Modelos","url":"https://www.modelos-de-curriculum.com/plantillas-curriculum-vitae/","path":"/lib/Apps/office tools/templates"},
{"name":"Studywithart | Plantillas gratis y personalizables","url":"https://studywithart.com/","path":"/lib/Apps/office tools/templates"},
{"name":"CharDoc | Pantillas creativas","url":"https://chardoc.com/cd_browse.html","path":"/lib/Apps/office tools/templates"},
{"name":"Infograpia","url":"https://infograpia.com/","path":"/lib/Apps/office tools/templates"},
{"name":"FileInfo","url":"https://fileinfo.com/","path":"/lib/Apps/office tools/files"},
{"name":"FILExt","url":"https://filext.com/","path":"/lib/Apps/office tools/files"},
{"name":"OpenFile.me","url":"https://www.openfile.me/","path":"/lib/Apps/office tools/files"},
{"name":"TXT File","url":"https://file.org/extension/txt","path":"/lib/Apps/office tools/files"},
{"name":"File Extension.org","url":"https://www.file-extension.org/","path":"/lib/Apps/office tools/files"},
{"name":"Yandex.Translate","url":"http://translate.yandex.com/?lang=en-es","path":"/lib/Apps/office tools/languajes"},
{"name":"Google Traductor","url":"https://translate.google.com/?sl=en&tl=es&op=translate","path":"/lib/Apps/office tools/languajes"},
{"name":"Lingva","url":"https://lingva.ml/","path":"/lib/Apps/office tools/languajes"},
{"name":"English corrector | Reverso","url":"https://www.reverso.net/ortografia/corrector-ingles/","path":"/lib/Apps/office tools/languajes"},
{"name":"DeepL Translate","url":"https://www.deepl.com/translator","path":"/lib/Apps/office tools/languajes"},
{"name":"Free AI online text to speech software","url":"https://spik.ai/","path":"/lib/Apps/office tools/languajes"},
{"name":"Spanish Dict","url":"https://www.spanishdict.com/translation","path":"/lib/Apps/office tools/languajes"},
{"name":"The Free Dictionary","url":"https://www.thefreedictionary.com/","path":"/lib/Apps/office tools/languajes"},
{"name":"Ratatype | mecanografía","url":"https://www.ratatype.es/typing-test/","path":"/lib/Apps/office tools/languajes"},
{"name":"Prueba de mecanografía","url":"https://www.keyhero.com/prueba-mecanografia/test-gratuito/","path":"/lib/Apps/office tools/languajes"},
{"name":"Diccionario de la lengua española | DRAE","url":"https://dle.rae.es/","path":"/lib/Apps/office tools/languajes"},
{"name":"Diccionario de inglés | Duolingo","url":"http://www.duolingo.com/dictionary/en","path":"/lib/Apps/office tools/textos"},
{"name":"videograbber","url":"https://www.videograbber.net/es/","path":"/lib/Apps/office tools/textos"},
{"name":"Desgrabador","url":"https://chequeabot.chequeado.com/desgrabador/","path":"/lib/Apps/office tools/textos"},
{"name":"Desgrabador de videos online","url":"https://anthiago.com/desgrabador/","path":"/lib/Apps/office tools/textos"},
{"name":"happyscribe | Transcripción y Subtítulos","url":"https://www.happyscribe.com/es","path":"/lib/Apps/office tools/textos"},
{"name":"Palabras que","url":"http://www.palabrasque.com/","path":"/lib/Apps/office tools/textos"},
{"name":"Palabras con","url":"http://www.palabrascon.com/","path":"/lib/Apps/office tools/textos"},
{"name":"OCR Image to Text Converter","url":"http://www.developertoolkits.com/ocr/image-to-text-converter","path":"/lib/Apps/office tools/textos"},
{"name":"Screenshot OCR online","url":"http://www.structurise.com/screenshot-ocr/","path":"/lib/Apps/office tools/textos"},
{"name":"Prepostseo OCR","url":"https://www.prepostseo.com/es/image-to-text","path":"/lib/Apps/office tools/textos"},
{"name":"onlineOCR","url":"https://www.onlineocr.net/es/","path":"/lib/Apps/office tools/textos"},
{"name":"Ordenar lista online","url":"https://pinetools.com/es/ordenar-lista","path":"/lib/Apps/office tools/listas"},
{"name":"Ordenar alfabéticamente","url":"https://copywritely.com/es/alphabetizer/","path":"/lib/Apps/office tools/listas"},
{"name":"ÉchaloASuerte","url":"https://echaloasuerte.com/","path":"/lib/Apps/office tools/listas"},
{"name":"AppSorteos","url":"https://app-sorteos.com/es","path":"/lib/Apps/office tools/listas"},
{"name":"Sortea2","url":"https://www.sortea2.com/","path":"/lib/Apps/office tools/listas"},
{"name":"Bing Mapas","url":"https://www.bing.com/maps/","path":"/lib/Apps/office tools/cartografia"},
{"name":"Perú","url":"https://satellites.pro/mapa_de_Peru#-6.784157,-79.833441,14","path":"/lib/Apps/office tools/cartografia"},
{"name":"OpenStreetMap","url":"https://www.openstreetmap.org/#map","path":"/lib/Apps/office tools/cartografia"},
{"name":"MapQuest","url":"https://www.mapquest.com/","path":"/lib/Apps/office tools/cartografia"},
{"name":"Google Earth","url":"https://www.google.com/earth/","path":"/lib/Apps/office tools/cartografia"},
{"name":"Maps::app","url":"https://www.google.com/maps/","path":"/lib/Apps/office tools/cartografia"},
{"name":"Convertio","url":"https://convertio.co/es/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Convert my image","url":"https://convert-my-image.com/","path":"/lib/Apps/office tools/convert tools"},
{"name":"PDFescape | Edit PDF Online","url":"https://www.pdfescape.com/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Soda PDF","url":"https://www.sodapdf.com/jpg-to-pdf/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Convertir PDF a JPG","url":"https://www.pdf2go.com/es/pdf-a-jpg","path":"/lib/Apps/office tools/convert tools"},
{"name":"Rasterbator | Poster to multi pages PDF","url":"https://rasterbator.net/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Zamzar","url":"https://www.zamzar.com/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Online File converter","url":"https://convertf.com/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Red Ketchup","url":"https://redketchup.io/","path":"/lib/Apps/office tools/convert tools"},
{"name":"Online Converter","url":"https://www.onlineconverter.com/","path":"/lib/Apps/office tools/convert tools"},
{"name":"SVG to PNG","url":"https://image.online-convert.com/convert/svg-to-png","path":"/lib/Apps/office tools/convert tools"},
{"name":"Herramienta de reconocimiento de voz","url":"http://www.textfromtospeech.com/es/voice-to-text/","path":"/lib/Apps/office tools/speech"},
{"name":"Lector de texto | dictado","url":"http://www.textfromtospeech.com/es/text-to-voice/","path":"/lib/Apps/office tools/speech"},
{"name":"Voice Notepad","url":"https://dictation.io/speech","path":"/lib/Apps/office tools/speech"},
{"name":"Speechnotes","url":"https://speechnotes.co/es/","path":"/lib/Apps/office tools/speech"},
{"name":"Speech to Text Demo","url":"https://speech-to-text-demo.ng.bluemix.net/","path":"/lib/Apps/office tools/speech"},
{"name":"Snapdrop::app","url":"https://snapdrop.net/#","path":"/lib/Apps/office tools/share files"},
{"name":"Sharedrop","url":"https://www.sharedrop.io/","path":"/lib/Apps/office tools/share files"},
{"name":"Wormhole","url":"https://wormhole.app/","path":"/lib/Apps/office tools/share files"},
{"name":"Skynet","url":"https://siasky.net/","path":"/lib/Apps/office tools/share files"},
{"name":"MyAirBridge","url":"https://www.myairbridge.com/es/#!/","path":"/lib/Apps/office tools/share files"},
{"name":"WeTransfer","url":"https://wetransfer.com/","path":"/lib/Apps/office tools/share files"},
{"name":"Ufile.io","url":"https://ufile.io/","path":"/lib/Apps/office tools/share files"},
{"name":"Easyupload.io","url":"https://www.easyupload.io/","path":"/lib/Apps/office tools/share files"},
{"name":"Upload Files | Upload Share","url":"https://uploadshare.net/","path":"/lib/Apps/office tools/share files"},
{"name":"UsersDrive","url":"https://usersdrive.com/","path":"/lib/Apps/office tools/share files"},
{"name":"FilePost","url":"https://filepost.io/","path":"/lib/Apps/office tools/share files"},
]