const _tech = [
    {"name":"@LKS","url":"https://pandadnap.notion.site/311b51ee88e543ada18235ecafce2d04","path":"/lib/Apps/tech"},
    {"name":"Let Me Google That","url":"https://letmegooglethat.com/","path":"/lib/Apps/tech/noob"},
    {"name":"LMGTFY EN","url":"https://es.lmgtfy.app/","path":"/lib/Apps/tech/noob"},
    {"name":"LMGTFY | Noob search","url":"https://www.lmgtfy.es/","path":"/lib/Apps/tech/noob"},
    {"name":"Don't ask to ask, just ask","url":"https://dontasktoask.com/","path":"/lib/Apps/tech/noob"},
    {"name":"Visual Studio Code Online | VSC::app","url":"https://vscode.dev/","path":"/lib/Apps/tech/code"},
    {"name":"Prettier code","url":"https://prettier.io/playground/","path":"/lib/Apps/tech/code"},
    {"name":"JavaScript Beautifier | format","url":"https://beautifier.io/","path":"/lib/Apps/tech/code"},
    {"name":"Essential JavaScript Playground | Syncfusion","url":"https://jsplayground.syncfusion.com/zf2kayte","path":"/lib/Apps/tech/code"},
    {"name":"W3C online editor","url":"https://www.w3docs.com/tools/editor","path":"/lib/Apps/tech/code"},
    {"name":"HTML Tryit Editor","url":"https://www.w3schools.com/tryit/tryit.asp?filename=tryhtml_default","path":"/lib/Apps/tech/code"},
    {"name":"PHP Tryit Editor","url":"https://www.w3schools.com/php/phptryit.asp?filename=tryphp_compiler","path":"/lib/Apps/tech/code"},
    {"name":"Code.In online code editor","url":"https://new.code.in/","path":"/lib/Apps/tech/code"},
    {"name":"Online SVG Code Editor","url":"https://editsvgcode.com/","path":"/lib/Apps/tech/code"},
    {"name":"Codeshare","url":"https://codeshare.io/","path":"/lib/Apps/tech/code"},
    {"name":"Essential JavaScript Playground | Syncfusion","url":"https://jsplayground.syncfusion.com/zf2kayte","path":"/lib/Apps/tech/code"},
    {"name":"JSFiddle | Code Playground","url":"https://jsfiddle.net/","path":"/lib/Apps/tech/code"},
    {"name":"PLAYCODE | Javascript Playground","url":"https://playcode.io/","path":"/lib/Apps/tech/code"},
    {"name":"CodersEditor","url":"https://coderseditor.com/","path":"/lib/Apps/tech/code"},
    {"name":"Online Css Compilere","url":"https://www.tutorialspoint.com/online_css_editor.php","path":"/lib/Apps/tech/code"},
    {"name":"JS Bin | JavaScript Debugging","url":"https://jsbin.com/?html,output","path":"/lib/Apps/tech/code"},
    {"name":"Code Editor | p5js","url":"https://editor.p5js.org/","path":"/lib/Apps/tech/code"},
    {"name":"CodeSandbox | Online Code Editor","url":"https://codesandbox.io/","path":"/lib/Apps/tech/code"},
    {"name":"New Pen on Codepen","url":"https://codepen.io/pen","path":"/lib/Apps/tech/code"},
    {"name":"Jquery to Javascript Pure","url":"https://properprogramming.com/tools/jquery-to-javascript-converter/","path":"/lib/Apps/tech/code"},
    {"name":"Transform web converters","url":"https://transform.tools/","path":"/lib/Apps/tech/code"},
    {"name":"Regex Replace","url":"https://coding.tools/regex-replace","path":"/lib/Apps/tech/regex"},
    {"name":"Regex Tester and Debugger","url":"https://www.regextester.com/","path":"/lib/Apps/tech/regex"},
    {"name":"Pythex","url":"https://pythex.org/","path":"/lib/Apps/tech/regex"},
    {"name":"regex101","url":"https://regex101.com/","path":"/lib/Apps/tech/regex"},
    {"name":"UnitConverters","url":"https://www.unitconverters.net/","path":"/lib/Apps/tech/min software"},
    {"name":"reverse video","url":"https://www.kapwing.com/editor/reverse-video","path":"/lib/Apps/tech/min software"},
    {"name":"Cortar y descargar vídeos de YouTube","url":"https://ytcutter.com/es/","path":"/lib/Apps/tech/min software"},
    {"name":"GenerateData","url":"https://generatedata.com/","path":"/lib/Apps/tech/min software"},
    {"name":"Key Combiner | ShortCuts","url":"https://keycombiner.com/collections/","path":"/lib/Apps/tech/min software"},
    {"name":"DataFakeGenerator","url":"https://datafakegenerator.com/","path":"/lib/Apps/tech/min software"},
    {"name":"Funciones de calendario","url":"https://www.topster.es/calendario/","path":"/lib/Apps/tech/min software"},
    {"name":"Url Parse | parse url Online","url":"https://www.b254.com/tools/url-parse.php","path":"/lib/Apps/tech/min software"},
    {"name":"getdisplay media","url":"https://getdisplay.media/","path":"/lib/Apps/tech/min software"},
    {"name":"Online Screen Recorder","url":"https://screenapp.io/#/","path":"/lib/Apps/tech/min software"},
    {"name":"Voice Recorder","url":"https://online-voice-recorder.com/es","path":"/lib/Apps/tech/min software"},
    {"name":"Online Alarm Clock","url":"https://military.onlineclock.net/","path":"/lib/Apps/tech/min software"},
    {"name":"Checksum files","url":"https://emn178.github.io/online-tools/sha256_checksum.html/","path":"/lib/Apps/tech/min software"},
    {"name":"Timestamp converter","url":"https://timestamp.online/","path":"/lib/Apps/tech/html software"},
    {"name":"Encrypt HTML","url":"https://www.smartgb.com/free_encrypthtml.php","path":"/lib/Apps/tech/html software"},
    {"name":"Uni Chart | HTML Characters","url":"https://unichar.app/web/","path":"/lib/Apps/tech/html software"},
    {"name":"Favorite JavaScript utilities","url":"https://1loc.dev/","path":"/lib/Apps/tech/html software"},
    {"name":"Character Entity Reference Chart","url":"https://dev.w3.org/html5/html-author/charref","path":"/lib/Apps/tech/html software"},
    {"name":"Web developer tools","url":"https://mothereff.in/","path":"/lib/Apps/tech/html software"},
    {"name":"JavaScript Event KeyCodes","url":"https://www.toptal.com/developers/keycode","path":"/lib/Apps/tech/html software"},
    {"name":"JavaScript variable name validator","url":"https://mothereff.in/js-variables","path":"/lib/Apps/tech/html software"},
    {"name":"Escaping Special Characters JavaScript","url":"https://www.the-art-of-web.com/javascript/escape/","path":"/lib/Apps/tech/html software"},
    {"name":"ASCII CODE TABLE","url":"https://ascii-code.net/","path":"/lib/Apps/tech/html software"},
    {"name":"Latín básico | Caracteres Unicode","url":"https://unicode-table.com/es/","path":"/lib/Apps/tech/html software"},
    {"name":"El código ASCII Completo","url":"https://elcodigoascii.com.ar/","path":"/lib/Apps/tech/html software"},
    {"name":"Best online chat bots and assistants","url":"https://botostore.com/","path":"/lib/Apps/tech/bots"},
    {"name":"Telegram Channels and Bots","url":"https://telegramchannels.me/bots","path":"/lib/Apps/tech/bots"},
    {"name":"Telegram bot list","url":"https://telegrambotlist.com/","path":"/lib/Apps/tech/bots"},
    {"name":"BotsArchive","url":"https://botsarchive.com/","path":"/lib/Apps/tech/bots"},
    {"name":"StoreBot","url":"https://storebot.me/","path":"/lib/Apps/tech/bots"},
    {"name":"URL Decode and Encode","url":"https://www.urldecoder.org/","path":"/lib/Apps/tech/strings"},
    {"name":"ASCII to Hex and more | cipher","url":"https://www.asciitohex.com/","path":"/lib/Apps/tech/strings"},
    {"name":"Cryptii | cipher","url":"https://cryptii.com/pipes/text-decimal","path":"/lib/Apps/tech/strings"},
    {"name":"Encoding and Decoding","url":"https://dencode.com/","path":"/lib/Apps/tech/strings"},
    {"name":"CyberChef","url":"https://gchq.github.io/CyberChef/","path":"/lib/Apps/tech/strings"},
    {"name":"Us Proxy free","url":"https://us-proxy.org/","path":"/lib/Apps/tech/conecction"},
    {"name":"Hide my name","url":"https://hidemy.name/es/proxy-list/","path":"/lib/Apps/tech/conecction"},
    {"name":"ipvoid website screenshot","url":"https://www.ipvoid.com/capture-website-screenshot/","path":"/lib/Apps/tech/web capture"},
    {"name":"Web capture","url":"https://web-capture.net/","path":"/lib/Apps/tech/web capture"},
    {"name":"pikwy","url":"https://pikwy.com/","path":"/lib/Apps/tech/web capture"},
    {"name":"apiflash","url":"https://apiflash.com/","path":"/lib/Apps/tech/web capture"},
    {"name":"IP DATA Geolocation API","url":"http://ipdata.co/","path":"/lib/Apps/tech/IP adress"},
    {"name":"IP Address Information","url":"http://www.ip-adress.com/ip-address/ipv4/132.184.128.82","path":"/lib/Apps/tech/IP adress"},
    {"name":"Public IP Address","url":"http://www.ipaddress.com/ipv4/132.184.128.82","path":"/lib/Apps/tech/IP adress"},
    {"name":"WhatIsMiIpAddress","url":"http://whatismyipaddress.com/ip/132.184.128.82","path":"/lib/Apps/tech/IP adress"},
    {"name":"Trace An IP","url":"http://www.ip-adress.com/ip-address/lookup","path":"/lib/Apps/tech/IP adress"},
    {"name":"ipapi","url":"http://ipapi.co/","path":"/lib/Apps/tech/IP adress"},
    {"name":"IPinfo.io","url":"http://ipinfo.io/","path":"/lib/Apps/tech/IP adress"},
    {"name":"Temporary phone numbers | Tempophone","url":"https://tempophone.com/","path":"/lib/Apps/tech/Temp mail/Temp phone"},
    {"name":"Free Texting","url":"https://www.textnow.com/","path":"/lib/Apps/tech/Temp mail/Temp phone"},
    {"name":"Receive SMS Online | Temporary and Disposable Phone Numbers","url":"https://smsreceivefree.com/","path":"/lib/Apps/tech/Temp mail/Temp phone"},
    {"name":"BugMeNot | Fake Account","url":"http://bugmenot.com/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Lifetime tempmail","url":"http://tempmailgen.com/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Temporary Email","url":"http://tempail.com/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"EmailOnDeck","url":"https://www.emailondeck.com/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Send anonymous email","url":"http://tempmail.ninja/send-anonymous-email","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Temp Emails | Temporary Email Generator","url":"http://www.tempemails.net/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Temp Mail ORG","url":"http://temp-mail.org/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"MAIL TM","url":"http://mail.tm/en/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Temp Mail IO","url":"http://temp-mail.io/es/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"SMAIL PRO","url":"http://smailpro.com/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"Mail Poof","url":"http://mailpoof.com/","path":"/lib/Apps/tech/Temp mail"},
    {"name":"BIN Generator","url":"http://www.bingenerator.com/","path":"/lib/Apps/tech/BINS"},
    {"name":"Bin Generator","url":"http://www.bingenerator.net/","path":"/lib/Apps/tech/BINS"},
    {"name":"BIN Generator","url":"http://sourcebincc.net/ccgen","path":"/lib/Apps/tech/BINS"},
    {"name":"Bin Checker | Generator","url":"http://www.bingenerator.net/bin-checker","path":"/lib/Apps/tech/BINS"},
    {"name":"Random Credit Card Numbers Generator | NamsoGen","url":"http://namso-gen.com/","path":"/lib/Apps/tech/BINS"},
    {"name":"Namso gen","url":"http://namso-gen.co/","path":"/lib/Apps/tech/BINS"},
    {"name":"Namso CCGen","url":"http://namso-gen.net/","path":"/lib/Apps/tech/BINS"},
    {"name":"Namso Gen","url":"http://namsogen.me/","path":"/lib/Apps/tech/BINS"},
    {"name":"Dr.Web","url":"https://vms.drweb-av.es/online/?lng=es","path":"/lib/Apps/tech/Linkfo/Virus"},
    {"name":"PhishTank","url":"https://phishtank.org/","path":"/lib/Apps/tech/Linkfo/Virus"},
    {"name":"Kaspersky","url":"https://opentip.kaspersky.com/","path":"/lib/Apps/tech/Linkfo/Virus"},
    {"name":"VirusTotal","url":"https://www.virustotal.com/gui/","path":"/lib/Apps/tech/Linkfo/Virus"},
    {"name":"IP Logger","url":"https://iplogger.org/url-checker/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"Grabify","url":"https://grabify.link/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"URL shortener | is.gd","url":"https://is.gd/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"URL Shortener","url":"http://gg.gg/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"Ow.ly","url":"https://www.hootsuite.com/pages/owly","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"n9 cl","url":"https://n9.cl/es","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"6ke.ru","url":"https://6ke.ru/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"git.io","url":"https://git.io/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"url.rw","url":"https://url.rw/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"0se.co","url":"https://0se.co/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"acortar.link","url":"https://acortar.link/","path":"/lib/Apps/tech/Linkfo/Short"},
    {"name":"UrlScan.io","url":"http://urlscan.io/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"ScanURL.net","url":"https://scanurl.net/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"Dr web url","url":"https://vms.drweb.ru/online/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"CheckShortURL","url":"https://checkshorturl.com/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"LongUrl","url":"https://longurl.info/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"Expand Url","url":"https://www.expandurl.net/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"VirusTotal","url":"https://www.virustotal.com/gui/home/url","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"Trustscam","url":"https://trustscam.es/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"GetLinkInfo","url":"https://getlinkinfo.com/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"Unshorten URLS","url":"https://unshorten.me/","path":"/lib/Apps/tech/Linkfo/URL info"},
    {"name":"Site report | Netcraft","url":"https://sitereport.netcraft.com/","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"WHOIS, DNS, & Domain Info | DomainTools","url":"https://whois.domaintools.com/t.me","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"Navegación segura de Google | Informe de transparencia","url":"https://transparencyreport.google.com/safe-browsing/search","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"Website Traffic | Analyze Any Website | Similarweb","url":"https://www.similarweb.com/","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"Traffic Trends, Reports and Analysis | URLTrends","url":"https://www.urltrends.com/","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"SE Ranking","url":"https://online.seranking.com/","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"AlienVault | Open Threat Exchange","url":"https://otx.alienvault.com/","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"Web Archive | Backup site","url":"https://web.archive.org/","path":"/lib/Apps/tech/Linkfo/site info"},
    {"name":"Open URLS","url":"https://www.websiteplanet.com/es/webtools/multiple-url/","path":"/lib/Apps/tech/Linkfo"},
    {"name":"JSON Verify & Validatorx","url":"https://jsonformatter.curiousconcept.com/#","path":"/lib/Apps/tech/JSON"},
    {"name":"JSON Viewer | View & Edit","url":"http://jsononline.net/json-viewer","path":"/lib/Apps/tech/JSON"},
    {"name":"Online JSON Viewer","url":"http://jsonviewer.stack.hu/","path":"/lib/Apps/tech/JSON"},
    {"name":"JSON Generator random","url":"https://next.json-generator.com/","path":"/lib/Apps/tech/JSON"},
    {"name":"Best JSON Viewer","url":"https://jsonformatter.org/json-viewer","path":"/lib/Apps/tech/JSON"},
    {"name":"JSON To CSV Converter","url":"http://convertcsv.com/json-to-csv.htm","path":"/lib/Apps/tech/JSON"},
    {"name":"JSON to CSV Converter Online","url":"https://json-csv.com/","path":"/lib/Apps/tech/JSON"},
    {"name":"Json prettify live","url":"http://jsonprettify.com/","path":"/lib/Apps/tech/JSON"},
    {"name":"metadata and exif viewer","url":"http://metapicz.com/#landing","path":"/lib/Apps/tech/image info"},
    {"name":"View and remove EXIF data","url":"https://www.verexif.com/en/","path":"/lib/Apps/tech/image info"},
    {"name":"TinEye Reverse Image Search","url":"https://tineye.com/","path":"/lib/Apps/tech/image info"},
    {"name":"Firefox Monitor","url":"https://monitor.firefox.com/","path":"/lib/Apps/tech/Check Account"},
    {"name":"Have I Been Pwned","url":"https://haveibeenpwned.com/","path":"/lib/Apps/tech/Check Account"},
    {"name":"Check Email Breach","url":"https://whatismyipaddress.com/breach-check","path":"/lib/Apps/tech/Check Account"},
    {"name":"Breach Checker","url":"https://breachchecker.com/?language=es","path":"/lib/Apps/tech/Check Account"},
    {"name":"Ruin My Search History","url":"https://proprivacy.com/tools/ruinmysearchhistory","path":"/lib/Apps/tech/Check Account"},
    {"name":"¿Quién me llama?","url":"https://quienmellama.com/","path":"/lib/Apps/tech/People info"},
    {"name":"Números de teléfono de Perú","url":"https://www.numerostelefono.com/pe/","path":"/lib/Apps/tech/People info"},
    {"name":"Find My Facebook ID","url":"https://commentpicker.com/find-facebook-id.php","path":"/lib/Apps/tech/People info"},
    {"name":"Codigo postal","url":"http://www.codigopostal.gob.pe/pages/invitado/consulta.jsf","path":"/lib/Apps/tech/People info"},
    {"name":"DNI Perú","url":"https://eldni.com/pe/buscar-por-nombres","path":"/lib/Apps/tech/People info"},
    {"name":"SUNAT Consulta Ruc","url":"https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias","path":"/lib/Apps/tech/People info"},
    {"name":"Seguro de Salud","url":"http://ww4.essalud.gob.pe:7777/acredita/","path":"/lib/Apps/tech/People info"},
    {"name":"Páginas Blancas","url":"http://www.paginasblancas.pe/","path":"/lib/Apps/tech/People info"},
    {"name":"Organización Política","url":"http://aplicaciones007.jne.gob.pe/srop_publico","path":"/lib/Apps/tech/People info"},
    {"name":"Numeros verifica | Osiptel","url":"https://verifica.osiptel.gob.pe/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Buscador celulares","url":"https://www.soporte-voip.com/buscador-celulares-peru/buscar.php","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Consulta de operador móvil","url":"https://console.dialogflow.com/api-client/demo/embedded/4ab8ae63-64b6-470d-b1c3-eed1aa28e35a","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Numeros | Movistar","url":"https://www.movistar.com.pe/movil/conoce-tus-numeros-moviles","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Numeros | Claro","url":"https://www.claro.com.pe/consulta-de-numero/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Numeros | Bitel","url":"https://bitel.com.pe/asistencia/consulta-linea","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Numeros | Entel","url":"https://www.entel.pe/app-privado/?app=consulta_lineas","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Sistema de Licencias de Conducir por Puntos","url":"https://slcp.mtc.gob.pe/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Colegiatura Veternario","url":"http://panel.cmvp.org.pe/buscador/index.html","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Conoce a tu médico | CMP","url":"http://www.cmp.org.pe/conoce-a-tu-medico/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"consulta vehicular SUNARP","url":"https://www.sunarp.gob.pe/seccion/servicios/detalles/0/c3.html","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Colegio de profesores","url":"http://sistema.cppe.org.pe/view/Colegiado/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Expedientes | SUCAMEC","url":"http://www.sucamec.gob.pe/web/index.php/consulta-expedientes/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"SUNEDU en línea","url":"http://enlinea.sunedu.gob.pe/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Consulta de títulos insituto MINEDU","url":"https://titulosinstitutos.minedu.gob.pe/","path":"/lib/Apps/tech/People info/asignaciones"},
    {"name":"Popular Name Searches | Zabasearch","url":"http://www.zabasearch.com/","path":"/lib/Apps/tech/People info"},
    {"name":"EsSalud | mesa de partes","url":"https://mpv.essalud.gob.pe/Login/Index","path":"/lib/Apps/tech/People info"},
    {"name":"Consulta SIS","url":"http://app.sis.gob.pe/SisConsultaEnLinea/Consulta/frmConsultaEnLinea.aspx","path":"/lib/Apps/tech/People info"},
    {"name":"Colegio de Ingenieros | CIP","url":"http://cipvirtual.cip.org.pe/sicecolegiacionweb/externo/consultaCol/","path":"/lib/Apps/tech/People info"},
    {"name":"OSINT Framework","url":"http://osintframework.com/","path":"/lib/Apps/tech/People info"},
    {"name":"Free Email Verification & Validator","url":"https://www.cleancss.com/email-validator/","path":"/lib/Apps/tech/People info"},
    {"name":"Full Fake Identify | OutPutter","url":"https://outputter.io/full-identity/","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"USA Fake Name Generator","url":"https://fake-it.ws/us/","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"Fake Identity Generator","url":"https://datafakegenerator.com/generador.php","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"Fake Name Generator | FauxID.com","url":"https://fauxid.com/","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"4Devs | Ferramentas Online Grátis","url":"https://www.4devs.com.br/","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"User Identity | Account and Profile Generator","url":"https://www.fakepersongenerator.com/","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"ElfQrin","url":"https://www.elfqrin.com/fakeid.php","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"UI Faces | Avatars","url":"https://uifaces.co/","path":"/lib/Apps/tech/GEN/people gen"},
    {"name":"Generador de nicks","url":"https://plarium.com/es/resource/generator/nickname-generator/","path":"/lib/Apps/tech/GEN/nicks"},
    {"name":"Letras Nick","url":"https://letrasnick.com/","path":"/lib/Apps/tech/GEN/nicks"},
    {"name":"Creador de nicks","url":"https://www.mundoxat.com/nicks/letrasnick.html","path":"/lib/Apps/tech/GEN/nicks"},
    {"name":"Generador de nombres de usuario | LastPass","url":"https://www.lastpass.com/es/username-generator","path":"/lib/Apps/tech/GEN/nicks"},
    {"name":"Random Name Generator","url":"https://www.random-name-generator.com/","path":"/lib/Apps/tech/GEN/names gen"},
    {"name":"Random Names Generator","url":"http://www.randomnamesgenerator.com/generate-name","path":"/lib/Apps/tech/GEN/names gen"},
    {"name":"Gen nombres aleatorios","url":"https://generadordenombres.online/","path":"/lib/Apps/tech/GEN/names gen"},
    {"name":"Fake Name Generator","url":"https://es.fakenamegenerator.com/gen-random-us-us.php","path":"/lib/Apps/tech/GEN/names gen"},
    {"name":"Password Check | Kaspersky","url":"https://password.kaspersky.com/es/","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"Free Online Hash Generator","url":"https://www.sordum.org/hashgenerator/","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"Online Hash Generator | Password Hash Generator","url":"https://www.onlinewebtoolkit.com/hash-generator","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"Generador de contraseñas | LastPass","url":"https://www.lastpass.com/es/password-generator","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"Strong Random Password Generator","url":"https://passwordsgenerator.net/","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"Random Password Generator","url":"https://www.browserling.com/tools/random-password","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"RANDOM.ORG | Password Generator","url":"https://www.random.org/passwords/","path":"/lib/Apps/tech/GEN/hash gen"},
    {"name":"¿Cuál es mi navegador?","url":"https://www.whatsmybrowser.org/","path":"/lib/Apps/tech/Device info"},
    {"name":"What browser am I using?","url":"https://www.whatismybrowser.com/","path":"/lib/Apps/tech/Device info"},
    {"name":"Device Info","url":"https://www.deviceinfo.me/","path":"/lib/Apps/tech/Device info"},
    {"name":"Device Size Screen","url":"http://howbigismybrowser.com/","path":"/lib/Apps/tech/Device info"}
]