var json_data_serie = {
    data_serie: {
        serie: 'Mr. Robot',
        tipo: "Temporada",
        favic: 'https://ih1.redbubble.net/image.2129448608.3460/flat,128x128,075,t.jpg',
        logot: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/MR_Robot.svg',
        // exter: 'https://pelisplus.me/serie/mr-robot/',
        exter: 'https://cuevana3.io/serie/mr-robot',
        prima: 'rgb(103, 142, 202)',
        secun: 'rgb(242, 26, 36)',
        porta: 'https://images-na.ssl-images-amazon.com/images/I/51vf4J0HCML._AC_SL1006_.jpg',
        ath: 'skt'
    },
    caps: [
        {url: "https://uqload.com/embed-2dpr8qbwppb1.html", tem: 1, epi: 1, tit: "Hola amigo"},
        {url: "https://uqload.com/embed-c6shza03z075.html", tem: 1, epi: 2, tit: "Unos y Ceros"},
        {url: "https://uqload.com/embed-3ocln53ul4js.html", tem: 1, epi: 3, tit: "Depurar"},
        {url: "https://uqload.com/embed-3ce6s0cjbqhi.html", tem: 1, epi: 4, tit: "Demonios"},
        {url: "https://uqload.com/embed-e3f2azd0e2ae.html", tem: 1, epi: 5, tit: "Exploits"},
        {url: "https://uqload.com/embed-5wumxr40lne3.html", tem: 1, epi: 6, tit: "Viajero valiente"},
        {url: "https://uqload.com/embed-ponuyf5gemal.html", tem: 1, epi: 7, tit: "Ver fuente"},
        {url: "https://uqload.com/embed-pfkzhpqulwqh.html", tem: 1, epi: 8, tit: "Rosa blanca"},
        {url: "https://uqload.com/embed-4v69vvitynkm.html", tem: 1, epi: 9, tit: "Espejado"},
        {url: "https://uqload.com/embed-i1wc5acng7px.html", tem: 1, epi: 10, tit: "Día Cero"},
        {url: "https://uqload.com/embed-9ghzxmoyqt44.html", tem: 2, epi: 1, tit: "Unmask (Part 1)"},
        {url: "https://uqload.com/embed-9ghzxmoyqt44.html", tem: 2, epi: 2, tit: "Unmask (Part 1)"},
        {url: "https://uqload.com/embed-o3tvo75xvnlr.html", tem: 2, epi: 3, tit: "Kernel Panic"},
        {url: "https://uqload.com/embed-fkg0k2dol9nq.html", tem: 2, epi: 4, tit: "Init 1"},
        {url: "https://uqload.com/embed-ddcim3g6tkkj.html", tem: 2, epi: 5, tit: "Logic Bomb"},
        {url: "https://uqload.com/embed-pjqwzd4c5q3e.html", tem: 2, epi: 6, tit: "Master Slave"},
        {url: "https://uqload.com/embed-gjjh3s0ov72x.html", tem: 2, epi: 7, tit: "Handshake"},
        {url: "https://uqload.com/embed-1lzkwh4igign.html", tem: 2, epi: 8, tit: "Successor"},
        {url: "https://uqload.com/embed-0p3bwgyvmfi2.html", tem: 2, epi: 9, tit: "Init 5"},
        {url: "https://uqload.com/embed-z7dyohu8k1qy.html", tem: 2, epi: 10, tit: "Hidden Process"},
        {url: "https://uqload.com/embed-u45um0fdija1.html", tem: 2, epi: 11, tit: "Python (Part1)"},
        {url: "https://uqload.com/embed-qee0m6mpqne4.html", tem: 3, epi: 1, tit: "eps3.0_power-saver-mode.h"},
        {url: "https://uqload.com/embed-o437m2gb4wd8.html", tem: 3, epi: 2, tit: "eps3.1_undo.gz"},
        {url: "https://uqload.com/embed-prr3nuq8onte.html", tem: 3, epi: 3, tit: "eps3.2_legacy.so"},
        {url: "https://uqload.com/embed-t2fzo62lz6bz.html", tem: 3, epi: 4, tit: "eps3.3_m3tadatapar2"},
        {url: "https://uqload.com/embed-0r6tslj1eadq.html", tem: 3, epi: 5, tit: "eps3.4_runtime-err0r,r00"},
        {url: "https://uqload.com/embed-ex4paedaryw8.html", tem: 3, epi: 6, tit: "eps3.5_kill-pr0cess.inc"},
        {url: "https://uqload.com/embed-2h8pd14h2fio.html", tem: 3, epi: 7, tit: "eps3.6_fredrick+tanya.chk"},
        {url: "https://uqload.com/embed-b6skctdfyx08.html", tem: 3, epi: 8, tit: "eps3.7_dont-delte-me.ko"},
        {url: "https://uqload.com/embed-bpwdmt84n3kp.html", tem: 3, epi: 9, tit: "eps3.8_stage3.torrent"},
        {url: "https://uqload.com/embed-n2w57uw45kgi.html", tem: 3, epi: 10, tit: "eps3.9_shutdown-r"},
    ]
}